### ISSUE TITLE
可不可以增加一种`JS CustomEvent` 触发方式，传递整个`xxx.automa.json`或者`https://xxx.automa.json`

### ISSUE THREAD

**Issue by AprildreamMI** [AutomaApp/automa#1000]
增加一种`JS CustomEvent` 触发方式，传递整个`xxx.automa.json`，或者`https://xxx.automa.json`
```
在页面中
window.dispatchEvent(new CustomEvent('automa:execute-workflow', {
	workflow: <JSON> || https://xxx.automa.json
}));
```

**Comment by Kholid060** [comment]
I don't think I'll add this feature because this could lead to a security risk

**Comment by AprildreamMI** [comment]
这个需求对开发者很有用，可以动态生成`xxx.automa.json`并且传递给automa执行
如果担心安全问题，可以让用户主机上的automa生成唯一密钥，在dispatchEvent时，传递密钥，对比密钥，排除恶意行为

**Comment by Kholid060** [comment]
Sure, I'll think about it.

**Comment by mrlink99** [comment]
我也需要这个，我自己的程序可以自定义指定使用某一个脚本。
比如：我要同时打开多个浏览器，每个浏览器调用不通的脚本。
什么时候可以增加这个功能？

**Comment by workcheng** [comment]
可以用程序调用自己写的workflow脚本吗？怎么调用呢？有没有例子看下，感谢！

**Comment by Kholid060** [comment]
https://docs.automa.site/blocks/trigger.html#trigger-using-js-customevent
