### ISSUE TITLE
iframe selector not working

### ISSUE THREAD

**Issue by george-martinec** [AutomaApp/automa#1001]
**Describe the bug**
cannot click inside form on passbolt.com in auth page iframe

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v0.12.0]

**Additional context**

**Comment by Kholid060** [comment]
Can you show the selector you use and the full URL of the website?

**Comment by simtuzi1** [comment]
When I have sometimes trouble with selectors. I use development tools on chrome browser to record the action I would take. And then use those selectors in Automa.  Default keybindings to open Chrome dev tools is <Ctrl>+<shift>+<i>
