### ISSUE TITLE
form for contenteditable="true"  is disable

### ISSUE THREAD

**Issue by hqfeijian** [AutomaApp/automa#1033]
selector for element by :  div[@contenteditable='true']
set form value  ,but input fail

for example [www.zhihu.com](http://www.zhihu.com/) ，answer question

**Comment by hqfeijian** [comment]
for example www.zhihu.com ，answer question

**Comment by Kholid060** [comment]
Try  to enable the "Debug mode" in the block settings of the Forms block

![image](https://user-images.githubusercontent.com/22908993/209504203-8649f61a-1d85-435d-9a6a-d81e626c70e8.png)

**Comment by hqfeijian** [comment]
resolved, thankyou ~
