### ISSUE TITLE
desktop shortcuts

### ISSUE THREAD

**Issue by zouhirdev** [AutomaApp/automa#1036]
hey i just wonder if you can please add the ability to create a desktop shortcut to workflaws 
ar at least make an api to interect with the extension .
thanks in advence

**Comment by Kholid060** [comment]
> hey i just wonder if you can please add the ability to create a desktop shortcut to workflaws
ar at least make an api to interect with the extension .

I don't think that's possible, because an extension can't add a shortcut to the desktop. And what do you mean by API?

**Comment by simtuzi1** [comment]
You can kinda work around that. Add html file to your desktop. it does not need anything special inside it.
Then open automa
Then specify the workflow you want to add, open it and  add a new workflow trigger. `When visiting a website``.
Then paste the filepath to the created html file. Now you can run a workflow using a file in desktop.

**Comment by zouhirdev** [comment]
nice thank you so much
