### ISSUE TITLE
Incorrect variable

### ISSUE THREAD

**Issue by njkhanh** [AutomaApp/automa#1037]
Javascript block
`const data = automaRefData('loopData', 'bouclesheet');
console.log(data.data[0])
console.log(typeof data.data[0])
automaNextBlock(data.data[0])`

console.log(data.data[0]) -> abcxyz
console.log(typeof data.data[0]) -> string 

I use {{ prevBlockData}} in form output "abcxyz", i want it is abcxyz

![](https://prnt.sc/IGspKAHyq6Zy)
![](https://prnt.sc/cO7heZu4VPzr)

**Comment by njkhanh** [comment]
![](https://img001.prntscr.com/file/img001/vMn3nYc_S-e-pSRz1Zx-Ng.jpeg)
![](https://img001.prntscr.com/file/img001/80Ww-UIKSwS4Pyqg5KOQkA.jpeg)

**Comment by Kholid060** [comment]
Can you show the data you loop and how you write it in the forms block?

**Comment by njkhanh** [comment]
Data get from google sheet
`[
  [
    "a2a7:3169:e3b2"
  ],
  [
    "1aba:ef33:e857"
  ]
]`
if not use javascript block {{ loopData@bouclesheet }} value : ["abcxyz"]

![](https://img001.prntscr.com/file/img001/ADTnNmBMSsKRBVa0bdpStw.jpeg)

**Comment by Kholid060** [comment]
You can input it in the forms block like `{{ loopData@bouclesheet.0 }}`

**Comment by njkhanh** [comment]
> You can input it in the forms block like `{{ loopData@bouclesheet.0 }}`

Ok, it's working. Thank you
