### ISSUE TITLE
请问automaFetch 如何获取Response.body(ReadableStream)对象

### ISSUE THREAD

**Issue by hhuimie** [AutomaApp/automa#1038]
fetch在处理大文件的时候需要ReadableStream

**Comment by Kholid060** [comment]
The `automaFetch` doesn't support that, it only supports text and JSON.

**Comment by hhuimie** [comment]
HTTP Request Block有base64, 请问`automaFetch`后续有可能添加吗?

**Comment by hhuimie** [comment]
另外, 通过http request block 将超长数据(测试是base64)存入variable是会错误, 打开log中的variables界面也会报错
![image](https://user-images.githubusercontent.com/4830177/209961931-c09f3148-fe2a-4d96-9641-1eebf12384d3.png)
