### ISSUE TITLE
trigger block input 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#1078]
**Describe the bug**
v1.25.3
![image](https://user-images.githubusercontent.com/20383505/211543928-4a9a0ef0-0943-48ac-a08b-7808a88faf9c.png)
trigger block about  first  Parameters

**Comment by Kholid060** [comment]
Have you tried to remove the parameter and add it?

**Comment by whwh656** [comment]
> Have you tried to remove the parameter and add it?

I find that secone parameters is work ,but only first parameters is not work
