### ISSUE TITLE
Questions about $replace

### ISSUE THREAD

**Issue by 100FZH** [AutomaApp/automa#1087]
Can $replace("hello world!", "world", "everyone") only replace one place at a time? How do I write it if I want to replace more than one place at a time?

**Comment by Kholid060** [comment]
> How do I write it if I want to replace more than one place at a time?

The `$replace` function only replaces one place at a time.

> How do I write it if I want to replace more than one place at a time?

It's currently not possible

**Comment by 100FZH** [comment]
> 

The $replace function only replaces one place at a time. 
For example, I want to replace all the spaces in the above sentence with "_", but currently automa can't do that, right?

**Comment by 100FZH** [comment]
The $replace function only replaces one place at a time. 
For example, I want to replace all the spaces in the above sentence with "_", but currently automa can't do that, right?

**Comment by 100FZH** [comment]
Also, where can I see all the built-in functions supported by automa?

**Comment by Kholid060** [comment]
> The $replace function only replaces one place at a time.
> For example, I want to replace all the spaces in the above sentence with "_", but currently automa can't do that, right?

Correct



> Also, where can I see all the built-in functions supported by automa?

You can find it in the [Expressions](https://docs.automa.site/workflow/expressions.html#functions) section in Automa documentation.

**Comment by 100FZH** [comment]
> You can find it in the [Expressions](https://docs.automa.site/workflow/expressions.html#functions) section in Automa documentation.
Thank you very much.
