### ISSUE TITLE
How to implement multiple workflows in the specified sequence with one key without manual execution

### ISSUE THREAD

**Issue by carls96** [AutomaApp/automa#1092]
How to implement multiple workflows in the specified sequence with one key without manual execution

![image](https://user-images.githubusercontent.com/59246551/212217884-633c0dfb-27b8-4e44-b7fd-57c2fb55c09b.png)

**Comment by Kholid060** [comment]
You can create another workflow and use the Execute workflow block inside that workflow.
![image](https://user-images.githubusercontent.com/22908993/212224630-bee68e1e-3b4b-4a9f-a9d5-94075b3fd512.png)
