### ISSUE TITLE
Clipboard block is not supported in background execution

### ISSUE THREAD

**Issue by LinggaID** [AutomaApp/automa#1096]
Clipboard block is not supported in background execution. Not sure if this is bug, but previously it is possible to work well, but what happen that make this limitation.

**Screenshots**
<img width="419" alt="image" src="https://user-images.githubusercontent.com/88594638/212393615-5ee4917c-8c72-4f89-8384-ef4b41d00b73.png">

**Comment by standingflower0607** [comment]
I have the same issue.
