### ISSUE TITLE
Can't get clipboard to function on newest patch (1.26.1)

### ISSUE THREAD

**Issue by simtuzi1** [AutomaApp/automa#1103]
**Describe the bug**
Log says: "Clipboard block is not supported in background execution"

It happens if some execution contexts of javascripts are marked as background. It doesn't matter if they are connected to clipboard nor before or after the clipboard block.

Is this intended?

**To Reproduce**
1. Make new workflow
2.  Add clipboard block to workflow, and draw line from trigger to clipboard.
3. Add Javascript code block to workflow. Switch execution context to "Background".  You do not have to draw any lines
4. Executing workflow fails.
5. Changing Javascript code block back to active does not change the situation.

**Expected behavior**
Workflow runs as planned from start to finish.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 
 - Browser: Google Chrome 109.0.5414.75 
 - Extension Version: Automa 1.26.1

**Comment by Kholid060** [comment]
Fixed in [v1.26.2](https://github.com/AutomaApp/automa/releases/tag/v1.26.2)
