### ISSUE TITLE
I am a beginner. I need a help in creating a workflow.

### ISSUE THREAD

**Issue by vkladha** [AutomaApp/automa#1117]
I am a total beginner. I need help in creating a workflow. I have my concept in mind but i don't know how to connect blocks in proper order and make it work.

**Comment by simtuzi1** [comment]
I can maybe help, what is exactly that you need? Provide some info.

**Comment by vkladha** [comment]
Hey AutomaApp/automa,

Thank you for your reply.

Here is my Concept -

There’s a canva template and there is a google sheet with two columns named
A and B

Now there’s a 300 slides in canva template.

In every slide, there is text X and Y

I want to replace text X and Y in each slide with the values available in
Row A and B from google sheets correspondence to each other.

I am attaching a google drive link containing a video of the manual process
which will help you understand better what I want from automa workflow.

https://drive.google.com/file/d/1gxbzowyV6pj2VM5nHb50dqEy5_9wjlOF/view?usp=share_link

Let me know if you have any questions.

Thanks!

**Comment by vkladha** [comment]
> I can maybe help, what is exactly that you need? Provide some info.

Any Update on this?
