### ISSUE TITLE
Is automa still working?

### ISSUE THREAD

**Issue by datatalking** [AutomaApp/automa#1121]
**Describe the bug**
When I follow the instruction on his first video the options don't show "existing workflow" it just zooms me to the dashboard. So again on his video when he says "go click the record workflow" then shows a menu comming up, when I click record it opens up the docs page for recording, so did the GUI change since the video was recorded?

**To Reproduce**
I watch the video and once you click on RECORD WORKFLOW... none of the menu options match what is in the video.

In the video it starts recording but my extension loads a whole new browser for the dashboard, and I can't record, nor does it give the option to select the CSS with the same options as the video.

MacOS, Chrome 109.0.5414.119

<img width="351" alt="Screen Shot 2023-01-24 at 4 41 42 PM" src="https://user-images.githubusercontent.com/11813209/214454346-23abdddf-612b-4b99-857d-89a92fd457d5.png">

**Comment by datatalking** [comment]
Then when I create a workflow using the extension, it lets me click record, then it only opens a new browser that looks like this.

<img width="716" alt="Screen Shot 2023-01-24 at 4 46 45 PM" src="https://user-images.githubusercontent.com/11813209/214454698-e1b42ee7-f002-4d7f-affb-99810ad64f5f.png">

**Comment by Kholid060** [comment]
We move the record workflow feature because of some changes on the browser API side why we made some adjustments to it. If you follow [the documentation](https://docs.automa.site/guide/quick-start.html#recording-actions) you'll get the same result as the video.

**Comment by datatalking** [comment]
> We move the record workflow feature because of some changes on the browser API side why we made some adjustments to it. If you follow [the documentation](https://docs.automa.site/guide/quick-start.html#recording-actions) you'll get the same result as the video.

The documentation isn't giving the same result, there is something you know as a software developer that I don't know as an analyst. i would like to use your scraper and add to it but there is probably only two or three "little steps or things" that the instructions are missing.

**Comment by aldrinjenson** [comment]
hi, having the same issue. how exactly to scrape some data and save it to some csv? the recording tab shows logs of only tab switches. 
firefox
