### ISSUE TITLE
[Loop elements] Support paginated redirects

### ISSUE THREAD

**Issue by n1xn** [AutomaApp/automa#1126]
**Is your feature request related to a problem? Please describe.**

_Yes. `Load more elements` within a `Loop Elements Block` is expecting to load more on the same site when a selector is passed, resulting in not loading more elements when the pagination redirects. It is pretty frustrating that we have this option but only for SPA's._

**Describe the solution you'd like**

_`Loop elements` should listen for redirects on active tab if `load more elements` selector is given and extend the `loopData` after page load._ 

**Describe alternatives you've considered**

_Creating an additional loop that wraps the `Loop elements Block` and feeds it with new data._

**Additional context**

_Description is clear, try it with any website where pagination redirects you. I can validate that all selectors are working independently and are recognised if executed from any paginated results page._

![image](https://user-images.githubusercontent.com/30150915/214784999-1a14d901-4cd8-42af-8112-0213f369213c.png)
![image](https://user-images.githubusercontent.com/30150915/214785078-ce13dfc1-2e4e-4918-b159-3fa3db208aee.png)

**Comment by Kholid060** [comment]
Can you send the workflow file? So I can reproduce the issue you have.

**Comment by n1xn** [comment]
Sure! Execute `Main` and don't pass in any arguments.

**Note**
_I am immediately closing `Productitem` to decrease waiting time for you - the functionality is the same as having operations inside this workflow._

https://tempfile.io/en/kZ39D7I4pygBDgA/file
https://tempfile.io/en/m5lkMFWJOaxroby/file
https://tempfile.io/en/fdmzvs9Vi5NKP1d/file
https://tempfile.io/en/3rGr0p9k5YuLCd6/file

**Comment by n1xn** [comment]
@Kholid060 may allow me to ask you before I have to create a new issue...

As you see I am writing all results to `storage` but actually the export in `Main` has no data within its CSV. I think it is because it always get overwritten by the last execution of a loop within the chain. I digged into the docs once again and couldn't find any description about overwrites. My assumption is to use global storage if you have nested loops and separated workflows, but I don't asumpt that every parent iteration is overwriting the added child data.
