### ISSUE TITLE
Data export block in Firefox

### ISSUE THREAD

**Issue by actus-shiekho** [AutomaApp/automa#1142]
**Describe the bug**
I'm trying to use the download data block in Firefox. my project has the following blocks: trigger ->http request -> New Tab -> JS Code -> download block. 
The download block throws always an Type error.I already found the same Bug in a stackoverflow question. 
[https://stackoverflow.com/q/40269862](https://stackoverflow.com/q/40269862)

It seem to be a security feature von Firefox

**To Reproduce**
1. Create a Project
2. Add and fill some Variables to Download it.
3. Add Data export block
4. Add Variable/ Table to download block
5. Try download it as CSV
7. See logs

**Expected behavior**

The CSV should be downloaded as in Chrome

**Screenshots**

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/110545346/215820211-88354740-f7fc-4820-b740-333d991ddc2a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: FireFox
 - Extension Version: 1.27.2

**Comment by Kholid060** [comment]
Use the Save Assets block if you want to download a file from an URL. Or can you provide the workflow file to reproduce this issue?
![image](https://user-images.githubusercontent.com/22908993/218641866-0039bda7-32ef-4be0-8448-1e588814ec14.png)

**Comment by actus-shiekho** [comment]
As i already metioned, I'm using a fetch request to get the data.
[Bitquery CSV Export.automa (2).json.zip](https://github.com/AutomaApp/automa/files/10729619/Bitquery.CSV.Export.automa.2.json.zip)
