### ISSUE TITLE
log data of variables do not change after delete data block

### ISSUE THREAD

**Issue by wohenbushuang** [AutomaApp/automa#1147]
**Describe the bug**
The log data of variables do not change after delete data block.

Demo workflow:
![image](https://user-images.githubusercontent.com/15613184/216825568-3abd6c7d-6320-403f-bba9-bdd5af307499.png)
![image](https://user-images.githubusercontent.com/15613184/216825592-5656a050-c4c9-484a-b2ce-34d68bf26725.png)
![image](https://user-images.githubusercontent.com/15613184/216825604-5bd696d0-fdd0-4a49-896e-1ec73c93ba2d.png)

The variable `foo` appears after 'insert data' block:
![image](https://user-images.githubusercontent.com/15613184/216825742-0d84501a-1474-47a2-9433-177b18a48fc3.png)

After 'delete data' block, the variable `foo` still exists:
![image](https://user-images.githubusercontent.com/15613184/216825747-0b52b481-3fb7-40de-8aaa-ee5e9183f63c.png)

The variable `foo` was indeed deleted at last:
![image](https://user-images.githubusercontent.com/15613184/216825667-bf879a07-cde8-434d-85ad-d3c6dc80a637.png)

BTW, I'd like to know how to debug my workflow, more specifically, how to monitor the variables' value during the workflow running step by step (block by block)? Now I only can print the variables via 'send notification' block ...

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.27.2

**Comment by Kholid060** [comment]
The log data you see when clicking a block in the log is the data the workflow has when the block is executed.

> how to monitor the variables' value during the workflow running step by step (block by block)? Now I only can print the variables via 'send notification' block 

Automa doesn't have a feature for debugging a workflow at the moment. But I'll try to add it in the future.

**Comment by wohenbushuang** [comment]
> The log data you see when clicking a block in the log is the data the workflow has when the block is executed.

@Kholid060  The log data display still remains after the deleta data block executed, e.g., in the finish step:

![image](https://user-images.githubusercontent.com/15613184/218658727-24bdce8b-84a6-4dcb-99d8-27d2ebe21798.png)
