### ISSUE TITLE
HTTP Request bug Form Data: File not found

### ISSUE THREAD

**Issue by marcelocecin** [AutomaApp/automa#1148]
**Describe the bug**
HTTP Request bug Form Data: File not found

**To Reproduce**
Steps to reproduce the behavior: https://docs.automa.site/blocks/webhook.html#form-data

**Expected behavior**
File to be found

**Screenshots**
![Captura_de_Tela_2023-02-01_as_14 45 28](https://user-images.githubusercontent.com/2955762/217885655-0ba8ad41-54d9-4f7c-9c5a-0399d7e1d6cc.png)
![Captura_de_Tela_2023-02-01_as_14 46 00](https://user-images.githubusercontent.com/2955762/217885659-67247912-6cf6-42ce-aa80-655932332b5f.png)
![Captura_de_Tela_2023-02-01_as_14 46 20](https://user-images.githubusercontent.com/2955762/217885663-61fe5652-a098-4b89-9c71-ce2b8f2e627a.png)
![Captura_de_Tela_2023-02-01_as_14 46 35](https://user-images.githubusercontent.com/2955762/217885666-1d719381-1065-46ba-ac64-edeae81d1158.png)

**Desktop (please complete the following information):**
 - OS: macOS 13.2 (22D49)
 - Browser: Google Chrome 109.0.5414.119
 - Extension Version: 1.27.3

**Comment by Kholid060** [comment]
I think it's throwing that error because you're using a double slash `//` in the file path. Try to write the file path like this instead `file://Users/name/Downloads/filename.jpg`;

**Comment by harryfear** [comment]
Works okay on MacOS but not on Windows in my testing.

**Comment by marcelocecin** [comment]
after removing the third line `[filename]` it worked
thanks
