### ISSUE TITLE
Can I set a random value for the delay block?

### ISSUE THREAD

**Issue by 100FZH** [AutomaApp/automa#1152]
Hello, can I set a random value for the delay block?

**Comment by nick0zer** [comment]
I'm looking for this function as well, any idea how to do random delay time?

**Comment by nick0zer** [comment]
Never mind I found this in the discussion section.

You can use the Delay block and input {{ $randint(2000, 9000) }} as the value. It will randomize the workflow delay between 2 to 9 seconds.

**Comment by 100FZH** [comment]
Great, finally found a way, thanks a lot!
