### ISSUE TITLE
 v1.27.2 http block url not support {{global@key}}

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#1157]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/20383505/218982143-d104fbec-d319-4835-ae8b-f26e350d180b.png)
**Describe alternatives you've considered**

**Additional context**

**Comment by Kholid060** [comment]
The `global` key is not a valid source of data, you can see [the documentation](https://docs.automa.site/workflow/expressions.html) for all the keys that Autom supported.
