### ISSUE TITLE
AUTOMA automaticly change the time of a delay time that i have set in my workflow

### ISSUE THREAD

**Issue by tunglam95** [AutomaApp/automa#116]
I have write a workflow and run it sometime. Basically, my workflow running ok. But lastime i run it, it automaticly change the Delay time that i have set before
I dont know why it break like that, please help me!

**Screenshots**
https://2.pik.vn/2021ac37fb70-f29c-4b69-ac6a-c8c29e10243c.png

**Desktop **
 - WINDOW7

**Comment by Kholid060** [comment]
That weird, I'll try to find out what actually happened

**Comment by tunglam95** [comment]
yeah, i have lost about 50k$ because of this issue T.T

**Comment by Kholid060** [comment]
Really? Sorry to hear that

**Comment by Jiuhk** [comment]
> yeah, i have lost about 50k$ because of this issue T.T

Just curious: How did you lose 50k$ from having an unexpected delay?
