### ISSUE TITLE
Google Chrome 110.0.5481.100 Virtually Unusable running Workflow on 1.28.0

### ISSUE THREAD

**Issue by ooglek** [AutomaApp/automa#1168]
**Describe the bug**
I've been running two or three workflows at the same time since Automa 1.24 without issue in Google Chrome on MacOS.

Today, after Automa updated to 1.28.0, Google Chrome hangs every 1-2 seconds with the beach ball of death when running a workflow, even just one. CPU jumps to 25% for Chrome, and the Automa tab jumps as well, but so do a bunch of all the other tabs in the Google Chrome Task manager. 

As soon as I hit "STOP" in Automa on the running workflow, all CPU on the tabs return to what I would consider reasonable / nominal levels. 

I was running the version prior to Google Chrome 110.0.5481.100, but updated when I had this issue. 

My Javascript blocks are set in "Background" to avoid the DOM issues in the "Active Tab." 

It is possible that a Google Chrome change occurred, but it seems more like Automa may have changed

**To Reproduce**
1. Run a Workflow that contains Javascript Code
2. Watch the CPU usage spike for Google Chrome and ALL Open Tabs (have at least 50 tabs open)

**Expected behavior**
Multiple Workflows can run at the same time without affecting all other tabs.

**Screenshots**
Before Starting Automa
![automa-bug-before-starting](https://user-images.githubusercontent.com/100755/219799961-1a41d05e-e2ff-4761-903c-2df02578809b.jpg)

While running Automa
![automa-bug-while-running](https://user-images.githubusercontent.com/100755/219799987-9e1a932a-21ad-491c-8d45-834a3144417b.jpg)

After Stopping Automa Workflow
![automa-bug-after-stopping](https://user-images.githubusercontent.com/100755/219800024-824e2f10-f59b-4a2c-a736-fb09358200c0.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Browser: Google Chrome 110.0.5481.100
 - Extension Version: 1.28.0

**Additional context**
none

**Comment by ooglek** [comment]
Just confirming that this is still happening -- all tabs see a 10-30% increase in CPU usage, slowing Chrome entirely to a crawl.

**Comment by ooglek** [comment]
Still happening in Google Chrome Version 111.0.5563.110 (Official Build) (x86_64)

I believe a change between 1.27.2 and 1.28.0 is causing these issues.

**Comment by Zilax34** [comment]
Hey man
Did you find any solution to your problem ?
I'm having the same issue here. When I launch Automa, Chrome become very slow. And after 1 hour or so of workflow going, Automa doesn’t even function anymore.

**Comment by bantza** [comment]
I may have had the same happening to me. When creating new workflow and debugging it, it was very slow, like two seconds to read a text from element and it all other tabs were slow also. Task manager showed much cpu usage in multiple tabs. What helped was to restrict site access of Automa from extension manager.

**Comment by ooglek** [comment]
I'd like to re-open this, as I have re-confirmed that this bug continues to occur when running multiple Automa workflows at the same time.

This seems to exist when running multiple Automa workflows at the same time. Maybe a race condition or a locking issue?

Google Chrome 117.0.5938.149
MacOS Ventura 13.5.2
Automa 1.28.15

This seems to have been introduced between 1.27 and 1.28, but I do not know for sure. 

**BACKGROUND WORKFLOW**

I have a website that has a list of items. There are different categories. My Workflow is started on the "Active Tab" so I pre-select the 2 or 3 categories I want to watch, then start Automa Workflow to reload, check to see if there are any new items added to the page, if not, sleep/Delay() for a random interval, then reload and repeat.

The Workflow is written such that it will work on most any page of the site with item listings, so there's no reason to have multiple different Workflows, since they should be able to run and operate completely independently (maybe a wrong assumption?).

I have attached the Page Monitor Workflow. 

[Item Page Monitor.automa.json.txt](https://github.com/AutomaApp/automa/files/12836330/Item.Page.Monitor.automa.json.txt)
