### ISSUE TITLE
http response is array

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#1180]
http response is array []

eg：[{"a":1,"b":2},{"a":3,"b":4}]

how can i get the second object of key a?

**Comment by ooglek** [comment]
`httpResponse[1].a` I'd think. -- you're getting the second item of the array (first is `0`, second is `1`), then `a` is the key.

<img width="438" alt="Screenshot 2023-03-23 at 3 47 15 PM" src="https://user-images.githubusercontent.com/100755/227334463-8cb01942-9d18-4039-beff-5dcc66bab7d1.png">

**Comment by Kholid060** [comment]
`1.a`
![image](https://github.com/AutomaApp/automa/assets/22908993/3363f0e6-aa7f-4fee-a9e1-5477c592b485)
