### ISSUE TITLE
Cannot delete schedualed workflows

### ISSUE THREAD

**Issue by opsnite** [AutomaApp/automa#1181]
**Describe the bug**
As titile described, there is no such delete buttom over the page. Cannot delete or deactivate.
![image](https://user-images.githubusercontent.com/24548110/221816874-d4ca664f-36f0-454c-a6f9-62c943180bd1.png)

**Comment by galactica1983** [comment]
I have the same issue with you, so I use "disable" to disable the workflow from being executed.

**Comment by pathboot** [comment]
and i think this issue was already resolved here by other way
https://github.com/AutomaApp/automa/issues/1020#issuecomment-1351681100
