### ISSUE TITLE
how can i use Insert Data Block , To insert multiple rows of data

### ISSUE THREAD

**Issue by Sigsawaii** [AutomaApp/automa#1182]
### Example：
_want to like this_
![image](https://user-images.githubusercontent.com/45675312/222023321-22d63ca1-6fdc-458e-b3b6-d61a98e478d0.png)

_use Insert Data Block_
![image](https://user-images.githubusercontent.com/45675312/222024064-77f28494-b248-4ed8-ab09-0c85bd548000.png)

_but it is not multiple rows_
![image](https://user-images.githubusercontent.com/45675312/222024004-39e99fd7-c385-4d8d-9188-5cbea07ce9d5.png)

### The ideal result like：
![image](https://user-images.githubusercontent.com/45675312/222025203-948c3456-ffd8-4c93-92dd-a09eae10182b.png)

Thank you very much for any help！

**Comment by stormslayerwd** [comment]
解决了么，我也想知道咋解决

**Comment by Anticope12** [comment]
following

**Comment by terryliu1003** [comment]
这个插入数据模块，我也搞不明白怎么使用插入额外数据到表格。插入到变量倒是弄懂了。实在不行就把表格弄成数组对象，插入到变量里，然后再在循环里面调用。
