### ISSUE TITLE
How to set a variable to the number input field in blocks?

### ISSUE THREAD

**Issue by 5730447921-PW** [AutomaApp/automa#1190]
I would like to switch tab to the index that has been specified from parameters. Is there anyway to achieve this?
![ภาพ](https://user-images.githubusercontent.com/13799322/222953393-e7e250cd-3eb4-49f1-93ba-7142b97fa03b.png)
![ภาพ](https://user-images.githubusercontent.com/13799322/222953251-6d23ef13-9e23-4b1e-ae1f-3fbb0b9cc198.png)

**Comment by ooglek** [comment]
Look at the docs for "Switch Tab" block -- https://docs.automa.site/blocks/switch-tab.html

> Switch to tab based on its index position. For example, there are 4 tabs in a browser window (Google, GitHub, Chess, and Microsoft), to switch to the Google tab you can input 0, to the GitHub tab input 1, and so on.
