### ISSUE TITLE
How can i set the variable name with Loopdata.$index?

### ISSUE THREAD

**Issue by FONGKA2** [AutomaApp/automa#1197]
Hello!

How can i set the variable name with the Loopdata.$index?
i found that seems the variable name cannot be in dynamic?
i like to set the variable name with other value
is the way to do that i can set variable name in loopindex/variable.value please?

![howto](https://user-images.githubusercontent.com/1371202/223329703-a3737132-9927-4103-9ac7-5d2a46f3834b.png)

With Thanks!

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/223611933-6d588654-bdbf-4796-b106-75743ae5cbf4.png)
loopData is right,     not loopDate
