### ISSUE TITLE
100% CPU usage after update

### ISSUE THREAD

**Issue by dzeto** [AutomaApp/automa#1208]
I noticed that whole computer freeze when using Automa (latest version). Before update it was possible to run 10 Brave profiles with 10 Automa addons, but now it's impossible to do it - it's way too much resurse eating right now. It's possible to get older version somehow?

Keep in mind that i run software on 32 CPU high-end server.
Thank you for help!

**Comment by dzeto** [comment]
Using those blocks:
- Google Sheets
- Proxy
- Element click
- Get text
- Form

**Comment by ooglek** [comment]
Duplicate https://github.com/AutomaApp/automa/issues/1168 #1168

**Comment by mzaini30** [comment]
https://github.com/AutomaApp/automa/issues/1250#issuecomment-1614575057
