### ISSUE TITLE
New Tab Block support variables

### ISSUE THREAD

**Issue by zhangwei911** [AutomaApp/automa#1209]
**Is your feature request related to a problem? Please describe.**
when i have some urls in globalData,i can not use it in new tab block,it will show invalid url

**Describe the solution you'd like**
i hope new tab block can use variables

**Describe alternatives you've considered**

**Additional context**

**Comment by whwh656** [comment]
可以支持的你再试一下

**Comment by zhangwei911** [comment]
> 

哪个版本的呢

**Comment by zhangwei911** [comment]
能提供一下最新版的国内可访问的地址吗

**Comment by skypesky** [comment]
@zhangwei911 
文档地址: https://docs.automa.site/workflow/global-data.html
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/33124160/230699516-6ccf8e92-7286-4c49-8401-c4a9c082f20a.png">
github 文档地址: https://github.com/AutomaApp/documentation/blob/main/docs/workflow/global-data.md

**Comment by happyTonakai** [comment]
Automa's documentation is quite simple and unclear. If anyone needs to use variables and loop data when opening a new tab, here's an example.

Variables should be written as `{{ variables.your_var_name }}`, and loop data should be written as `{{ loopData.loop_id }}`. When combined, they should look like this: `{{ variables.base_url }}&pp={{ loopData.pages }}`.
