### ISSUE TITLE
automaRefData is not defined v1.28.0

### ISSUE THREAD

**Issue by zhangwei911** [AutomaApp/automa#1217]
**Describe the bug**
when i create an new element,cannot find automaRefData

**To Reproduce**
1. Create Element Block
2. edit element
3. select JavaScript
4. input automaRefData('variables', 'xx')

**Expected behavior**
i can get the variables xx

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Extension Version: v1.28.0

**Additional context**

**Comment by edwyn-amador** [comment]
I just noticed this issue., a workaround for now would be saving all data to cookies and access it through JavaScript in the Create Element block.
