### ISSUE TITLE
商品列表的链接打开有一个tab之后，无法激活这个tab

### ISSUE THREAD

**Issue by shiliu2023** [AutomaApp/automa#1231]
商品列表的链接类似这样：
<a class="edit-link" href="javascript:void(0)" data-volta="8929ae05-dd5d-4fd6-a160-e2566cd6a487">编辑</a>

这是一个编辑商品的链接，点开后会打开一个tab。比如：https://mms.pinduoduo.com/goods/goods_add/index?id=108543014746&goods_id=464513103253&type=edit

但是这个tab无法被设置成激活的标签，导致后面的步骤都无法操作了。javascript:void(0)。这个链接实际藏在了network里的js里。

这种问题该怎么办啊？id和goods_id都是活的，因为一个商品列表有会多个商品。

**Comment by skypesky** [comment]
@shiliu2023 你说的没看懂，可以发演示录屏看看。
录屏1: 你手动的时候是怎么点击的
录屏2: automa 执行的时候是什么样子的

另外 automa 支持编写自定义 js 脚本
<img width="301" alt="image" src="https://user-images.githubusercontent.com/33124160/230699157-c653bca3-d24d-4ddd-b5e3-9bb2fe4fd3a9.png">

**Comment by khhf** [comment]
你是用的循环，然后点击每个页面，打开之后不能操作对吧；
不能用循环点击，先获取每个链接中的地址，然后循环地址，新建tab页打开，在操作后面的
