### ISSUE TITLE
Docs: clarify the mode of execution in blocks group

### ISSUE THREAD

**Issue by cubical8569** [AutomaApp/automa#1234]
**Is your feature request related to a problem? Please describe.**
The [documentation page about blocks group](https://docs.automa.site/blocks/blocks-group.html) does not clarify if blocks inside a group are executed sequentially or maybe in some other way.  

**Describe the solution you'd like**
I'd like the docs to clarify the mode of execution.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by Kholid060** [comment]
Fixed
