### ISSUE TITLE
Is there a way to set a certain script as a trigger that will start the workflow?

### ISSUE THREAD

**Issue by aunicorn111** [AutomaApp/automa#1236]
So, hear me out. I had an idea of a script that will start Automa workflow in a browser, while the script itself is summoned via terminal. :) It would be awesome if Automa also could take variables from the script and import those into its flow, or bring end value back into script as a variable 

Not sure if Automa already has a way of doing so, I'll just leave it here :smile_cat:

**Comment by workcheng** [comment]
I am looking for a way to invoke this workflow through command-line arguments and get the results. Have you found a suitable solution to this problem?

**Comment by aunicorn111** [comment]
Sadly no. I mean, I suppose there is a way if you interact with firefox via console or maybe bash script. But to this day I haven't found a way to get the end value as a variable black. Maybe only as a text file or something... 
All I can say is using selenium directly much easier xD

**Comment by aunicorn111** [comment]
However, if you want to use automa specifically, you can set up a profile that will start automa script on bootup and trigger the start of that profile via bash :eyes:

**Comment by aunicorn111** [comment]
Still not sure about variable part though...

**Comment by Kholid060** [comment]
You can actually run automa workflow via the browser console by dispatching the `automa:execute-workflow` custom event like below.

```js
const customEvent = new CustomEvent('automa:execute-workflow', {
  detail: {
    id: 'automa-workflow-id',
    data: {
       variables: {
           variableName: 'variableValue'
       }
    }
  }
})
window.dispatchEvent(customEvent)
```

https://docs.automa.site/blocks/trigger.html#trigger-using-js-customevent

For getting the result from the workflow, it's current not supported.
