### ISSUE TITLE
Infinite delay

### ISSUE THREAD

**Issue by Ranamzes** [AutomaApp/automa#1250]
**Describe the bug**
A delay of more than 45000 milliseconds leads to an infinite delay. 

**To Reproduce**
1. Install this workflow https://www.automa.site/workflow/8LZJNVO1tF7Dph9qRPDc5
2. Change the first delay from, 22500 to 45000
![изображение](https://user-images.githubusercontent.com/88456236/233488017-111cb8c1-2732-4a73-a86a-040476f78414.png)
3. Start workflow

**Expected behavior**
The execution will hang on this delay forever

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox 112.0.1 (64-bit)
 - Extension Version: 1.28.1

**Comment by mzaini30** [comment]
I think this is a bug in Automa. In workflows with a looping process, the execution time of the loop keeps increasing. Even for the "open new tab" action, which usually takes 0 seconds, it keeps increasing and can even reach 10 seconds.

The solution is to break it down into multiple workflows:

Main workflow -> at the end of the workflow -> execute workflow A

Workflow A -> at the end of the workflow -> execute workflow B

Workflow B -> at the end of the workflow -> stop all workflows (except this workflow) -> execute the main workflow

By doing this, no matter how many workflows you run, the execution time will always remain constant.
