### ISSUE TITLE
Sorry, I didn't realize there was a undo function

### ISSUE THREAD

**Issue by codePigPig** [AutomaApp/automa#1258]
**Describe the bug**
I'm not sure if this is a bug or not.
I'm currently using version v1.28.0, but I don't see the undo function in the keyboard shortcuts.

**Expected behavior**

**Screenshots**
<img width="796" alt="image" src="https://user-images.githubusercontent.com/67849873/234526706-c5eb4c7c-520d-428f-9ea7-c3c83b5a302f.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - Extension Version: v1.28.0
 
 I hope someone can reply to me, thank you very much

**Comment by Kholid060** [comment]
The undo or redo keyboard shortcuts can't be edited.
