### ISSUE TITLE
 "Insert Data" to import 

### ISSUE THREAD

**Issue by qxlwx666** [AutomaApp/automa#1259]
Use "Insert Data" to import the local CSV format file, the data in 2 columns and 5 rows, the data obtained by the loop module, there are [""] symbols on both sides, how to delete this character?

**Comment by Kholid060** [comment]
It is most likely that the data is [array data type](https://en.wikipedia.org/wiki/Array_(data_type)#:~:text=In%20computer%20science%2C%20array%20is,array%20variable%20or%20array%20value.). Thus you need to add `.0` at the end of the expression, for example 
Before:
`loopData.loopId`

After:
`loopData.loopId.0`
