### ISSUE TITLE
Run a workflow every month 

### ISSUE THREAD

**Issue by salicius** [AutomaApp/automa#1263]
How can i run a workflow every month on a certain day ?

**Comment by REFLEXGAMING007** [comment]
Trigger < Edit Triggers < Add Trigger < On a Specific Date < Done (customize to your choice)

**Comment by Kholid060** [comment]
In the trigger block, add "Cron Job", and insert `0 0 1 * *`

![image](https://github.com/AutomaApp/automa/assets/22908993/82a62f56-5e1a-4e98-8f8c-8226ef695fcd)
