### ISSUE TITLE
we need a feature to control log consume

### ISSUE THREAD

**Issue by cfsego** [AutomaApp/automa#1266]
**Is your feature request related to a problem? Please describe.**
we use AutoMa as a server driven crawler. we retrieve the task from servers, and save in a variable in our flow for the next loop.
when the crawler run for some time, we notice it becomes slower and slower, and we notice from os monitor the log write rate is over 10M/s from the crawler, so the whole system is unstable(we use SATA disks) and the crawler works slow.

**Describe the solution you'd like**
give us a option to disable logs

**Describe alternatives you've considered**
we tried to use timer splitting our long task to small tasks but it made no difference.

**Comment by mzaini30** [comment]
https://github.com/AutomaApp/automa/issues/1250#issuecomment-1614575057
