### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by namanRP** [AutomaApp/automa#1270]
I've built an app that loops through a LinkedIn list of profiles, opens them, and collects data. The first profile is loaded, and data is collected fast, but it slows down as we eventually load and collect more data. I've deleted the variables that it is storing using the delete block, but still, the performance slows down as the loop progresses.

Is there anything that I might be doing wrong here? I'm using many variables and getting text blocks.

**Comment by mzaini30** [comment]
https://github.com/AutomaApp/automa/issues/1250#issuecomment-1614575057
