### ISSUE TITLE
Ask how to control the execution speed of the case

### ISSUE THREAD

**Issue by 23olddog** [AutomaApp/automa#1273]
**Describe the bug**
Hello, when I use the Automa Google plugin to record the case, I find that the recorded case executes too fast. It is difficult for me to see what the case operates. How to set the execution speed of the case? Do you need to modify the source code? If so, which file should I go to find the logic code for this part?

**Additional context**

**Comment by Kholid060** [comment]
You can go to the workflow settings on top right of the workflow and on the "Blocks" section input the "block delay"

![image](https://github.com/AutomaApp/automa/assets/22908993/942741bb-8090-47b7-a5c2-74f4cfc4d35b)
