### ISSUE TITLE
Cant use VPN extension while automa is enabled

### ISSUE THREAD

**Issue by markowen4** [AutomaApp/automa#1275]
**Describe the bug**
Cant use VPN extension while automa is enabled because automa is blocking access to proxy settings for other extensions
I tired with multiple different vpn extensions and I get the same error with all of them.
Any solution?

**Screenshots**
![vpnerror](https://github.com/AutomaApp/automa/assets/135173038/7559dc41-ce5a-46a1-89f9-72673c03b584)

**Comment by Kholid060** [comment]
There isn't a solution for this besides disabling the Automa extension, or you can try using the Touch VPN extension because it seems like it is working even though Automa is enabled.
