### ISSUE TITLE
Exception handling block Like 'On Error Resume Next'

### ISSUE THREAD

**Issue by playGitboy** [AutomaApp/automa#1278]
Can the Automa plugin support exception handling like 'On Error Resume Next' in VB?

Some exceptions may occur during the process  when using loop data block. How do I ignore these exceptions and go straight to the next loop instead of ending the process with an error?

**Comment by mzaini30** [comment]
https://github.com/AutomaApp/automa/issues/1250#issuecomment-1614575057

**Comment by Kholid060** [comment]
Open the block settings and on the "on error" section select the "execute fallback" option and connect the fallback output to another block or select the "continue flow" option.

https://github.com/AutomaApp/automa/assets/22908993/30aaa66d-c479-48f9-a60b-43aa092d0fb6
