### ISSUE TITLE
Can't connect to Google Sheet

### ISSUE THREAD

**Issue by JosukeTatami** [AutomaApp/automa#1286]
Hello, 

Automa won't connect to Google Sheet. It was working until i uninstall and reinstall the extension.
I also tried to install previous version but the issue is still here.

![image](https://github.com/AutomaApp/automa/assets/137730794/c348dd9d-dbcc-4dc5-81bc-f7621f0cf297)
![image](https://github.com/AutomaApp/automa/assets/137730794/44b61f9e-510d-4bcc-824e-902c16efe0d0)

This drives me so mad and make me loss so much time 😭  please do something

**Comment by denysullivan** [comment]
I keep getting this "[query] "range" is required" as an error too. First time trying to export table to sheets (but I am integrated/connected). I've tried every range type and nothing works
![image](https://github.com/AutomaApp/automa/assets/94069734/0a38a1a9-bf00-4719-9d91-a9f33762c6d4)
