### ISSUE TITLE
[ANNOUNCEMENT TO EVERYONE] Do Not Run Loops within a Single Automa Workflow

### ISSUE THREAD

**Issue by mzaini30** [AutomaApp/automa#1287]
Please refrain from running loops within a single Automa workflow. The longer the process runs, the longer the execution time will become. For example, in a loop from 1 to 10, a JavaScript block takes 0 seconds. However, when it reaches the 500th loop, a single JavaScript block takes 20 seconds.

Solution:

Create Workflow A and Workflow B. Here's the flow:

Main workflow -> at the end of the workflow -> execute Workflow A

Workflow A -> at the end of the workflow -> execute Workflow B

Workflow B -> at the end of the workflow -> stop all workflows (except this workflow) -> execute Main Workflow

By implementing this solution, regardless of how long the looping process runs, the execution time will not increase; it will remain constant.

I hope these tips will be helpful to all of you.

**Comment by SullieLore** [comment]
Thanks for mentioning this. I wonder if Automa could implement a fix/non-loop solution, such as:

Main workflow -> at the end of the workflow -> **break and continue** -> execute Main workflow.

And/or via a hidden duplicated Main workflow version of each singular loop.
