### ISSUE TITLE
cant open dashboard!

### ISSUE THREAD

**Issue by Wentelii** [AutomaApp/automa#1289]
my old version mac, by using chrome, can not open the dashboard, what should i do?
![image](https://github.com/AutomaApp/automa/assets/138673087/28a181a8-4f90-4cc3-ba39-7d1cec9dd513)

**Comment by Wentelii** [comment]
i am in China

**Comment by Kholid060** [comment]
Try updating your Chrome browser to the latest version. And I can't reproduce this issue.
