### ISSUE TITLE
Automatic replacement of browser fingerprint module

### ISSUE THREAD

**Issue by vitaminx** [AutomaApp/automa#1303]
Automatic replacement of browser fingerprint module

I hope to add an automatic update and random browser fingerprint module. It is often not enough to delete the cookie and replace the proxy ip, which will make the execution of automa fail.

Only when fingerprints, cookies and proxy ip are updated at the same time can automation be perfectly realized

**Comment by Kholid060** [comment]
I don't have a plan to add a feature to replace the browser fingerprint. So, I recommended using another extension for that, such as [Fingerprint Spoofing Extension](https://chrome.google.com/webstore/detail/fingerprint-spoofing/ljdekjlhpjggcjblfgpijbkmpihjfkni).
