### ISSUE TITLE
Click event not being dispatched

### ISSUE THREAD

**Issue by nunopoco** [AutomaApp/automa#1304]
**Describe the bug**
The click event is not dispatched on a button when running the worflow without a step-by-step debug.
It works if I set a breakpoint anywhere in the workflow and click "next block", going through it one by one. 
Clicking "resume" after any breakpoint gives the same result as just running it.

**To Reproduce**
[test.automa.zip](https://github.com/AutomaApp/automa/files/12223389/test.automa.zip)
video walkthrough: https://share.clickworks.io/recordings/CspZfXX8AOmLyDU4mQ6V

**Expected behavior**
A click on the specified button.

**Screenshots**
![locationofthebutton](https://github.com/AutomaApp/automa/assets/7423668/1bd32aa5-8df9-4561-85ac-6ab2d9b68a51)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Extension Version: 1.28.1

**Additional context**
When it's running with or without dev protocol, the click is not sent.
Tried sending it with a trigger event of click, double click, hover + click and focus + enter. None worked.
Also tried using js block to use click() and dispatch mouse event, also no result.
It's strange as I can click all other parts of the page.

**Comment by nunopoco** [comment]
Solved: added a "Switch Tab" to switch to the same tab and it worked.
Doesn't seem to make sense but somehow it solved it.

**Comment by kqvanity** [comment]
@nunopoco 
How did you switch to the same tab?
