### ISSUE TITLE
Google Drive block not working

### ISSUE THREAD

**Issue by Vader16039** [AutomaApp/automa#1307]
**Describe the bug**
Google drive block is not working though google account is connected in integration page.

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/136983544/427b9ea9-ca49-4c23-a62f-fea980b721aa)

![image](https://github.com/AutomaApp/automa/assets/136983544/5b77152c-08bb-4931-86b0-c2eacce880ed)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.1

**Comment by Kholid060** [comment]
Fixed in v1.28.2
