### ISSUE TITLE
Host workflow is not working

### ISSUE THREAD

**Issue by CrocodileOP** [AutomaApp/automa#1309]
Hello Kholib060

I have some issue for the Host Workflow.

About Automa 1.21 (using on browser)

I can log in Github account on Automa site, however on Dashboard, it does not link to Github account, it always asked me to sign in again and again.
not only github but also google account does not work as well, so I cannot use the Host Workflow function.

About Automa 1.28 (using on extension pop-up)

Then
 I try to use the new version Automa 1.28, it could log in github account.

However another problem when I activate the Host Workflow.
 At that time it''s working and show the Host code 

But If I close the tab, the Host Workflow isn't active and I have to turn on again, which make the code change.

I need the Host Workflow unchange with the same code. How Can I set it? '....'

**Comment by kiinoo** [comment]
got the same problem still
