### ISSUE TITLE
Could not establish connection to the active tab in Javascript block

### ISSUE THREAD

**Issue by victorgfollow** [AutomaApp/automa#1310]
I'm trying to execute a javascript but i'm getting this error:

"Could not establish connection to the active tab"

This is the Javascript Code:

```
// Função para buscar e clicar no link contendo "https://www.instagram.com"
function buscarECLicarLinkInstagram() {
  const links = document.querySelectorAll('a'); // Seleciona todos os elementos 'a' (links) na página
  
  // Procura por um link que contenha "https://www.instagram.com"
  for (const link of links) {
    if (link.href && link.href.includes('https://www.instagram.com')) {
      // Imprime o link encontrado no console
      console.log("Link encontrado: " + link.href);
      
      // Simula o clique no link
      link.click();
      
      // Termina a busca após encontrar o primeiro link
      break;
    }
  }
}

// Chama a função para buscar e clicar no link
buscarECLicarLinkInstagram();
```

**Screenshots**

![image](https://github.com/AutomaApp/automa/assets/141868560/029d8f6b-f479-4b0e-9d3f-0034f6f68bb0)

![image](https://github.com/AutomaApp/automa/assets/141868560/c8c070ac-b528-4f53-ba74-443d61761b81)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Google Chrome]
 - Extension Version: [1.28.2]

**Comment by code-lixm** [comment]
I had the same problem
