### ISSUE TITLE
Add support for mobile simulation (debugger commands)

### ISSUE THREAD

**Issue by aslafy-z** [AutomaApp/automa#1311]
**Is your feature request related to a problem? Please describe.**
I'd like to simulate a mobile device, like I can do with the Google Chrome debugger.

**Describe the solution you'd like**
Ability to set extra settings on New Tab or Current Tab, or to inject debugger commands in a next block.

**Describe alternatives you've considered**
Keystokes, UA changes, Incognito windows

**Additional context**
I've found it should be doable on Google Chrome with https://stackoverflow.com/a/75681911/4266494.

**Comment by CssEoCAO** [comment]
hi, i also need this feature
