### ISSUE TITLE
Multiple workflow execution

### ISSUE THREAD

**Issue by flingyp** [AutomaApp/automa#1315]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I have a child workflow, and I want to execute the child workflow in the parent workflow loop. But I can manually set the number of cycles. Can Automa do that now? Hoping for advice.

**Describe alternatives you've considered**

**Additional context**

**Comment by Delusionnnn** [comment]
This should be able to be accomplished with a combination of Repeat Task block and Execute Workflow block. A conditions block if it needs to be more complicated.
