### ISSUE TITLE
Dashboard don't open

### ISSUE THREAD

**Issue by nicolasmol** [AutomaApp/automa#1316]
Hi there

Using:
Chrome Version 115.0.5790.170 (Build officiel) (64 bits)
With Automa Version 1.28.2
Under Linux nicolas-hp 5.15.0-78-generic #85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Clicking on this:
![image](https://github.com/AutomaApp/automa/assets/61077647/ea7b67fd-4fd4-4637-a99c-a953df81b8e5)

Don't open the dashboard and console says:
![image](https://github.com/AutomaApp/automa/assets/61077647/b37ff2fd-5785-4166-9e9f-c031de3e5789)

Regards

**Comment by Siykt** [comment]
I tried to reproduce this bug and found that when the default value of  `windowOptions.width`  is much larger than the window width (around twice),  `browser.windows.create`  throws the same error: "Invalid value for bounds. Bounds must be at least 50% within visible screen space."

so, I suggest setting the default value of  `windowOptions`  in such a way that it allows the Dashboard to open correctly.

> src/background/BackgroundUtils.js

```js
const curWin = await browser.windows.getCurrent();
const windowOptions = {
  top: 0,
  left: 0,
  width: Math.min(curWin.width, 715),
  height: Math.min(curWin.height, 715),
  url: tabUrl,
  type: 'popup',
};
```
