### ISSUE TITLE
Appending to Google Sheet selects incorrect column

### ISSUE THREAD

**Issue by SuperTempAccount** [AutomaApp/automa#1320]
**Describe the bug**
When using these settings on a Google Sheets block the data is written to columns A and B.
<img width="301" alt="image" src="https://github.com/AutomaApp/automa/assets/83566267/ef11101d-15fd-4d46-a106-f5f4dda828ba">

**To Reproduce**
1. Add a `Google Sheets` block
2. Select append data
3. Enter a full column as the reference
4. Data is written to column A

**Expected behavior**
Data is written to the columns chosen.

**Screenshots**
This doesn't work
<img width="301" alt="image" src="https://github.com/AutomaApp/automa/assets/83566267/1f53dcb1-ed26-4f8f-b64e-3d7392ad8484">

Giving a direct reference works as expected
<img width="301" alt="image" src="https://github.com/AutomaApp/automa/assets/83566267/998cf821-283a-454b-b16e-24eb1b26b1e0">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox
 - Extension Version: v1.28.4

**Comment by WickedInvi** [comment]
Bump

I've seen this issue before 1.28.4 it's quite limiting. I've been meaning to create a report about this.

**Comment by Kholid060** [comment]
It's not working because that's how the behavior of Google Sheets Append. I don't think I can do something about it

![image](https://github.com/AutomaApp/automa/assets/22908993/973c5784-eb87-415f-a536-b4a6610a56ef)

https://developers.google.com/sheets/api/guides/values#append_values

**Comment by WickedInvi** [comment]
Thank you for responding, if this is a limitation from google, there should be a workaround.

Is it possible to delete the table data thru a JS Block?
To confirm Table is an array of Objects correct?

Do you think the following is possible?


Now I should be able to search for a certain unique variable inside the Object. 

Here is a SS for reference 
![image](https://github.com/AutomaApp/automa/assets/49752323/80e1aa4b-48d6-43f2-bcfd-46f74fee1827)

Get table from the Sheet and add it to the Table.
Assign the currently looping item number to a variable. Before restarting the loop execute a JS Code Block.
Now inside the JS Code Block I am thinking get the Table, create a new Array and push each item from the Table to the Array so I am able to manipulate it.
If I loop thru the Array.itemNumber and check for 123456, if it matches I would add Messaged: "Yes".

Than I want to delete the existing table and add the Array as the new Table.

This way we can simulate "Find and Add value to an Offset cell"

Than we override the whole Table in the Sheet


Hope all this makes some sense.
