### ISSUE TITLE
How automa performs actions during page loads

### ISSUE THREAD

**Issue by chenjore** [AutomaApp/automa#1329]
I found that automa can only execute the following action after the newly opened page is loaded, my requirement is how to start the following action while the page is loading, I am very disturbed, please let me know if you know about it, thanks a lot!

**Comment by Kholid060** [comment]
What actions are you trying to perform while the page is loading?

**Comment by chenjore** [comment]
> 

I want to detect the element directly and execute it as soon as it is detected instead of waiting for all the elements to load.

**Comment by Kholid060** [comment]
Use the Javascript Code block and enable the "Run before page loaded" option

**Comment by chenjore** [comment]
> Use the Javascript Code block and enable the "Run before page loaded" option

After my test, in the js code check Run before page loaded, it is still in front of the page loaded to execute the js code, rather than in the loading of the js code execution
