### ISSUE TITLE
Can I map JSON text ?

### ISSUE THREAD

**Issue by LucianCr** [AutomaApp/automa#133]
I am getting the text from here https://webservicesp.anaf.ro/bilant?an=2018&cui=6859662 and I want to separate the JSON data in columns and then export it, is there currently a way to do this ? Can we have a JSON mapping block ?

**Comment by LucianCr** [comment]
i found this as a workaround https://www.convertcsv.com/json-to-csv.htm but can't figure out if after "get text" block i can copy it in the "enter data" text field then get the text from "result data" text field and then add it to the csv...

![image](https://user-images.githubusercontent.com/53472025/143400602-c3e09da5-d009-401e-9877-30e9a4936b95.png)

the image added is my current workflow which i want to adjust :)

**Comment by LucianCr** [comment]
i created a flow to get the data using the convertcsv website but i get stuck when i want to loop through the data columns 

![image](https://user-images.githubusercontent.com/53472025/143477548-591db052-c616-4fb0-8af3-e4b842ce0bbb.png)

in the form input i get a good result the time and then when it loops i get the plain text variable ( {{ loopData@JevBoC.col1 }} ) aded where the data should be

**Comment by Kholid060** [comment]
That means data with the `JevBoC.col1` path doesn't exist, try to write `{{ loopData@JevBoC }} ` first to see whether it exists or not.

**Comment by LucianCr** [comment]
yep, it does not pull anything after first row but if i try to run only the 4 blocks and export the data is with all the necesary rows... what can i do ? 
![image](https://user-images.githubusercontent.com/53472025/143777674-94277ed6-b541-40da-b1ea-152a0c196e4f.png)

**Comment by LucianCr** [comment]
also, it would be nice to have a JSON transform tool inside Automa

**Comment by LucianCr** [comment]
how can we map JSON text ?
