### ISSUE TITLE
Save assets timeout feature

### ISSUE THREAD

**Issue by NguyenCongVN** [AutomaApp/automa#1332]
**Is your feature request related to a problem? Please describe.**
Sometimes, there's error from the server that make saving assets failed, I need some timeout feature to not wasting time at waiting failed from server.

**Describe the solution you'd like**
A timeout parameter in saving assets block

**Comment by Kholid060** [comment]
You can go to the block settings and input the "Block execution timeout"

![image](https://github.com/AutomaApp/automa/assets/22908993/5f50c515-6de8-47b8-8cfa-58ee0b565bd1)

**Comment by NguyenCongVN** [comment]
@Kholid060 Thank you! I've missed it
