### ISSUE TITLE
BUG - Conditional Block with JS - Cannot use automaSetVariable

### ISSUE THREAD

**Issue by WickedInvi** [AutomaApp/automa#1336]
**Describe the bug**
AutomaSetVariable does not appear in auto complete inside a condition block using JS, and does not work
![image](https://github.com/AutomaApp/automa/assets/49752323/8b3d8380-9e73-49f9-8873-93791b94aea2)

It does show in JS inside normal JS Block
NOTE - Tool tip say automaRefData inside the JS block the rest of it is correct
![image](https://github.com/AutomaApp/automa/assets/49752323/222c7679-e138-4171-8b11-6cc72b6dca7e)
And it works as expected
![image](https://github.com/AutomaApp/automa/assets/49752323/d81026fd-2032-403a-b397-cfb22f3ce813)

**To Reproduce**
Add Condition block with JS
Try to use automaSetVariable

**Expected behavior**
To set variable 

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/49752323/c2c56720-011b-4046-9b69-963574b42fd7)

**Desktop (please complete the following information):**
 - OS: Windows 11  Version	10.0.22621 Build 22621
 - Browser: Chrome Version 116.0.5845.97 (Official Build) (64-bit)
 - Extension Version: 1.28.6

**Comment by Kholid060** [comment]
It's because it only supported the `automaRefData` function.

**Comment by v-smwang** [comment]
> It's because it only supported the `automaRefData` function.
Why is that? Supporting automaSetVariable can bring us more convenience. If not, how do we set the variables？

**Comment by v-smwang** [comment]
> > It's because it only supported the `automaRefData` function.
> > Why is that? Supporting automaSetVariable can bring us more convenience. If not, how do we set the variables？

I was careless. In javascript code, you can use automaSetVariable; Not in the condition, and there's nothing wrong with it from a design point of view
