### ISSUE TITLE
facebook scroll no effect

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#1338]
1 login in facebook account 
2 open target url: https://www.facebook.com/friends/suggestions

![image](https://github.com/AutomaApp/automa/assets/20383505/43ec23ad-7de2-4941-9f37-048e9cc334ca)

I want to ask how to scroll this section use scroll it's difficult for me

**Comment by Kholid060** [comment]
Use `div.xb57i2i` element as the element selector

**Comment by whwh656** [comment]
Thanks

**Comment by whwh656** [comment]
> Use `div.xb57i2i` element as the element selector

**Comment by whwh656** [comment]
[testfbscroll.automa (1).txt](https://github.com/AutomaApp/automa/files/12475640/testfbscroll.automa.1.txt)
I try to use this method ,but i maybe not work
