### ISSUE TITLE
Chrome Tab acting as if CTRL is held down

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1344]
**Describe the bug**
Not sure why but after running some of my workflows (the long ones seem to cause the issue) my space bar will not work in the chrome tab that the workflow has interacted with only sometimes. I have tried to see if there is any rouge scripts running but nothing is showing up and adding the stop workflow command at the end of all my workflows did not solve it. It is acting as if control is held down in the tab which is odd cause control is never used in my workflow. I know its control because spacebar will work if held down for a little bit. My sticky keys are off for reference. No idea what's causing this. 

**To Reproduce**
1. Run Script (super long ones seem to be causing the issue)
2. Go to Chrome Tab that workflow interacted with and don't refresh (refresh solves issue)
3. (This is on company internal sites so I can't share what website it happens on, but I assume it can happen on others but not yet tested)

**Screenshots**
For reference, look at how big my workflow is. It took 6 hours to program.

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 22H2 (Build 19045.3324)
 - Browser: Chrome 116.0.5845.97 (Official Build) (64-bit) (cohort: Stable) 
 - Extension Version: 1.28.6

![image](https://github.com/AutomaApp/automa/assets/141815049/c84f6ce7-44d1-43e4-9e7d-c296dfd5cf00)

**Comment by Kholid060** [comment]
Is there a Trigger Event or Press Key block inside your workflow?

**Comment by Delusionnnn** [comment]
> 

I just have the original trigger which I've tried different keys and also context menu and both have same result. Tried on two different PC's and also another workflow and I am still getting this occasionally despite all these things. I don't have any key presses or trigger event blocks, just a couple clipboard blocks and lots of forms blocks using variables (around 40 global table variables). It's even happening on much smaller workflows too, albeit less.

**Comment by SuperTempAccount** [comment]
I experience this issue periodically. 
The space bar doesn't work until the page is refreshed.
My workflow is much less complicated and doesn't include any `trigger event` or `press key` blocks.
It does include `forms` and `click element` blocks.

My guess is it has something to do with the `forms` block but I will check and post back.

**Comment by Kholid060** [comment]
> I experience this issue periodically. The space bar doesn't work until the page is refreshed. My workflow is much less complicated and doesn't include any `trigger event` or `press key` blocks. It does include `forms` and `click element` blocks.
> 
> My guess is it has something to do with the `forms` block but I will check and post back.

Do you have the workflow file I can use to reproduce this issue? Because I can't reproduce this issue.

**Comment by SuperTempAccount** [comment]
Hi @Kholid060 I found out how to reproduce the issue.

1. Open a website with a textbox/form e.g. https://google.com/
2. Open the Automa extension
3. Open the Element Selector
4. Close the Element Selector
5. The spacebar is disabled

<img width="464" alt="image" src="https://github.com/AutomaApp/automa/assets/83566267/b9c3662b-84ca-4761-94bd-636b4b84170c">


It seems that launching the Element Selector is enough to stop the space bar from working until the page is refreshed.

Let me know if you can't reproduce it

**Comment by Kholid060** [comment]
> Hi @Kholid060 I found out how to reproduce the issue.
> 
> 1. Open a website with a textbox/form e.g. https://google.com/
> 2. Open the Automa extension
> 3. Open the Element Selector
> 4. Close the Element Selector
> 5. The spacebar is disabled
> 
> <img alt="image" width="464" src="https://user-images.githubusercontent.com/83566267/269228457-b9c3662b-84ca-4761-94bd-636b4b84170c.png">
> It seems that launching the Element Selector is enough to stop the space bar from working until the page is refreshed.
> 
> Let me know if you can't reproduce it

Thanks, I can reproduce it now.
