### ISSUE TITLE
New error (t.split is not a function) in Data Block

### ISSUE THREAD

**Issue by systemaddict** [AutomaApp/automa#1347]
**Describe the bug**

After the last update (1.28.7) I have started to see the error:

t.split is not a function

When using the Insert Data block:

![image](https://github.com/AutomaApp/automa/assets/1615733/de3f7099-a342-4755-b89d-7d025994752d)

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktio
 - Browser: Brave
 - Extension Version: 1.28.7

**Comment by ben714** [comment]
I'm having the same issue after the last update.
