### ISSUE TITLE
Can't find active tab

### ISSUE THREAD

**Issue by c3p7f2** [AutomaApp/automa#1350]
**Describe the bug**
When opening the dashboard, the Execute Workflow Block will report an error Can't find active tab

**To Reproduce**
1. open the dashboard
2. execute Workflow
3. the Execute Workflow Block will report an error Can't find active tab

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.7

**Comment by Kholid060** [comment]
Duplicate #1345
