### ISSUE TITLE
Ability to trigger an automated workflow directly from Python code

### ISSUE THREAD

**Issue by menteora** [AutomaApp/automa#1360]
**Is your feature request related to a problem? Please describe.**
I want to be able to initiate an automated workflow from Python code, it's possibile?

**Describe the solution you'd like**
I would like the ability to trigger an automated workflow directly from Python code if it's possible and get results. There is a way to do this?

Thank you

**Comment by Kholid060** [comment]
> I want to be able to initiate an automated workflow from Python code, it's possibile?

No, that's not possible. But if you're running the Automa extension in a headless browser like Selenium, you can inject a javascript code to trigger an event to start workflow execution.

https://docs.automa.site/blocks/trigger.html#trigger-using-js-customevent
