### ISSUE TITLE
Cannot read properties of null (reading 'contentWindow')

### ISSUE THREAD

**Issue by rongtao7** [AutomaApp/automa#1368]
I am in Automa's Conditions and have added the above js, but it is during the process that I have selected the key, and I understand that it is the key that I have selected.
Cannot read properties of null (reading 'contentWindow'), js generation：// Ink-based judgment
var configStr = localStorage.getItem("CRUMB_CONFIG");
var configJson = JSON.parse(configStr);

if (configJson.length == 2) {
   return true;
}

var lastConf = configJson[configJson.length - 1];
return Array.isArray(lastConf.children) && lastConf.children.length > 0;

**Comment by rongtao7** [comment]
Immediately send the message to js. "return true;"

**Comment by rongtao7** [comment]
<img width="779" alt="image" src="https://github.com/AutomaApp/automa/assets/26051975/920a310f-0bab-4262-8750-39f35027c908">

**Comment by rongtao7** [comment]
The cause is the report.

**Comment by Kholid060** [comment]
Can you copy the Conditions block and paste it here? Because I can't reproduce your issue
