### ISSUE TITLE
Can't processed the failure reason in http body, Workflow Events

### ISSUE THREAD

**Issue by zhangtengjin** [AutomaApp/automa#1372]
In Workflow Events, use http request to push workflow failure message. When there are quotation marks in workflow.errorMessage, how to process it? By the way, can I use built-in function expressions in http body?

![image](https://github.com/AutomaApp/automa/assets/33016610/9553e22c-7ed4-49b0-970b-e24f2ed4d70e)

![image](https://github.com/AutomaApp/automa/assets/33016610/973f2c1e-99ac-4e77-b26f-5aba6193a939)

**Comment by zhangtengjin** [comment]
![image](https://github.com/AutomaApp/automa/assets/33016610/8fc064f2-4185-4d3f-a4f5-c34d8cbf047a)
char

Failure reason string parsing will have problems

**Comment by Kholid060** [comment]
> When there are quotation marks in workflow.errorMessage, how to process it?

You need to escape the quotation if you want to use a quotation mark inside a quotation. Use a bracket if you want to access data inside an expression (https://docs.automa.site/workflow/expressions.html#access-another-data-inside-the-expressions). For example,

from
``{ "text": "{{variables.user}} some text {{$replaceAll({{workflow.errorMessage}}, '"', '')}}" }``

to
``{ "text": "{{variables.user}} some text {{$replaceAll([workflow.errorMessage], '\"', '')}}" }``

**Comment by zhangtengjin** [comment]
Thank you very much for your reply！
But there are still problems with parsing~

- This is the failure reason returned by the workflow：` ``Can't find an element with the selector \"span.el-radio__inner"```

- This is the result of parsing using $replaceAll

![image](https://github.com/AutomaApp/automa/assets/33016610/c2182b26-c022-48b0-ae84-2671684579c2)

**Comment by Siykt** [comment]
This is because there is an issue with the regular expression in  `src/workflowEngine/templating/mustacheReplacer.js:20` . It only supports parsing scenarios where  `\"`  does not exist.

**Comment by wushihua** [comment]
Why workflow events do not take effect? After packaging the Chrome plugin, it does not take effect. It is possible to run it directly
