### ISSUE TITLE
Quota exceeded for Google Sheets

### ISSUE THREAD

**Issue by SuperTempAccount** [AutomaApp/automa#1377]
**Describe the bug**
I receive a Quota Exceeded error when using Google Sheets.
Only reading 100 cells of data.
If I make two requests in a minute, it will exceed the quota.
I believe the allowable is 60K requests per minute.

**To Reproduce**
![image](https://github.com/AutomaApp/automa/assets/83566267/8f908fc2-4d00-41e7-92fc-1a4f6048ec14)

**Expected behavior**
More requests are possible per minute.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc/Chrome
 - Extension Version: Chromium Engine Version 116.0.5845.179

**Comment by Kholid060** [comment]
Duplicate #1342
