### ISSUE TITLE
Google Sheet API Read/Write limit reached

### ISSUE THREAD

**Issue by Magicyoyo** [AutomaApp/automa#1381]
**Describe the bug**
When playing a workflow, I get errors from the Google Sheet API, concerning read or write quotas (both).
=> Error message in Automa Logs : "Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:57312334836'"
I'm only updating and reading 17 cells per hour. I think the quota reached concerns the Automa app declared in Google.

**To Reproduce**
1. Create a workflow writing/reading in GG Sheet
2. Share your sheet with 'service@automa2.iam.gserviceaccount.com'
3. Run the workflow
4. Look at logs for errors

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Extension Version: 1.28.9

**Additional context**
Ask for higher limits please. It should be free : https://developers.google.com/sheets/api/limits?hl=en

**Comment by Kholid060** [comment]
> Ask for higher limits please. It should be free.

I'm working on it.

Duplicate #1342
