### ISSUE TITLE
Get response status code in HTTP Request

### ISSUE THREAD

**Issue by ariyan-eghbal** [AutomaApp/automa#1384]
Is it possible to get response status code in HTTP Request Block?

**Comment by SuperTempAccount** [comment]
Hi @ariyan-eghbal, yes it is possible. It is the first field returned.

See https://docs.automa.site/blocks/webhook.html

**Comment by ariyan-eghbal** [comment]
> Hi @ariyan-eghbal, yes it is possible. It is the first field returned.
> 
> See https://docs.automa.site/blocks/webhook.html

I saw that page but it seems `status` is just a part of sample response, it is not part of return structure of HTTP Request Block    
on successful call `{{prevBlockData}}` contains the response body and on failure nothing exists in `{{prevBlockData}}`   
Also if i change the Data path to status the whole replacement fails

**Comment by Kholid060** [comment]
In v1.28.11 you can input `$response.status` as the data path to get the status code.
