### ISSUE TITLE
Expansion Problem

### ISSUE THREAD

**Issue by imperatore-spqr** [AutomaApp/automa#1392]
Hi, when I right-click, the Automa extension does not appear, but the Ad block extension does.

I'm on mac

<img width="326" alt="Schermata 2023-09-20 alle 19 59 54" src="https://github.com/AutomaApp/automa/assets/145378575/ed773fe4-0182-4dac-9db4-4912bd0b65b6">

**Comment by Kholid060** [comment]
It only appears when you have a workflow that has the [`Context Menu` trigger](https://docs.automa.site/blocks/trigger.html#context-menu)

**Comment by imperatore-spqr** [comment]
I have a "Context menu" trigger but it still doesn't appear, can you help me?
<img width="290" alt="Schermata 2023-09-21 alle 11 36 10" src="https://github.com/AutomaApp/automa/assets/145378575/3d8f53c6-6610-4fa6-b37c-be93c78373cc">
<img width="657" alt="Schermata 2023-09-21 alle 11 36 23" src="https://github.com/AutomaApp/automa/assets/145378575/73b12649-235a-4052-875f-6082934c12e9">

**Comment by Kholid060** [comment]
What browser do you use?

**Comment by imperatore-spqr** [comment]
Chrome, I also tested on brave but it doesn't work
