### ISSUE TITLE
condition block does not work anymore

### ISSUE THREAD

**Issue by philobbe** [AutomaApp/automa#1406]
**Describe the bug**
my condition block does not work anymore
it no longer locates element 83. it worked normally before but I don't know since what version change because I haven't used it for some time 

**Desktop :**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.13

![002845](https://github.com/AutomaApp/automa/assets/25483500/3e190764-c4d6-4053-abb7-142f982339d1)
![002846](https://github.com/AutomaApp/automa/assets/25483500/0dd9b8ac-a4ac-4eaf-82c9-af0583ff32d7)

**Comment by yusuferenayas** [comment]
Exactly same problem. Something is wrong on the new version.
