### ISSUE TITLE
Conditions Block not working after update (v1.28.13)

### ISSUE THREAD

**Issue by Vader16039** [AutomaApp/automa#1407]
**Describe the bug**
Getting the error "**e?.toLocaleLowerCase is not a function**" upon executing a workflow with conditions block with "**Equals (case insensitive)**".

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/136983544/53655ee0-d716-4dc6-88af-0733768c2a77)

![image](https://github.com/AutomaApp/automa/assets/136983544/5f965e97-c194-4ea0-8b2a-081ac24a4fe0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: v1.28.13

**Comment by yusuferenayas** [comment]
Exactly same problem. Something is wrong on the new version.

**Comment by Kholid060** [comment]
Duplicate #1406
