### ISSUE TITLE
feature request: default value for `get text` node 

### ISSUE THREAD

**Issue by HaveF** [AutomaApp/automa#1410]
**Is your feature request related to a problem? Please describe.**
We sometimes need to get various pages in the loop, but some pages do not have some specific elements, so in this case, we can only use the 'elements exist' node with the 'get text' node to judge and get elements, if we want to get multiple elements, there will be a lot of 'elements exist' and 'get text' nodes.

**Describe the solution you'd like**
If the 'get text' node can set a default value, such as an empty string, then it is easier to directly represent the default value when the corresponding element is not found on the page, so that the 'elements exist' node is not needed.

Use a 'get text' to be cleaner.

**Comment by Kholid060** [comment]
You can remove the Element Exist block and enable the "On Error" setting of the Get Text block in the Block Settings. In there, enable the "Insert Data" to insert data into a variable or table column in case the element doesn't exist.

![image](https://github.com/AutomaApp/automa/assets/22908993/9a18dd7d-75fd-4e18-b8a4-3146dcb2d701)

**Comment by HaveF** [comment]
@Kholid060 Thanks! Btw, maybe we should put these settings on doc somewhere?
