### ISSUE TITLE
Automa CEB Trigger Parameters

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1412]
Hi,

It concerns the extension version of a workflow, this issue doesn't happen in the workflow itself.

When you use a regular "Parameters" block in the workflow, a popup window is displayed in front of the user, so the user can enter the required informations.

But, if you set parameters in the "Trigger" block, the popup windows opens behind the Chrome window, so the user can't see it.

Thanks!

**Comment by Kholid060** [comment]
Fixed
