### ISSUE TITLE
Embed a workflow execution button on a page.

### ISSUE THREAD

**Issue by macerd** [AutomaApp/automa#1413]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The user creates a workflow in automata with input parameters, after which he clicks on "embed workflow automata", the embedding code is added to the page and it is determined what values will be for each variable.

Adding this option allows the user to make script execution even easier, thus integrating with their platform.

Note that it will be necessary to check if the user has Automa installed and the workflow exists, the button appears on the page.

**Describe alternatives you've considered**
Using the parameter block prompt makes this step easier, but it breaks the flow that the user has to execute workflows that are available, taking more time to configure input values and execution.

**Additional context**

_Example:_
![Screenshot 2023-10-02 at 13 46 20](https://github.com/AutomaApp/automa/assets/16547271/a6ebf2ca-3094-4831-9f6d-58031acc64fe)

**Comment by Kholid060** [comment]
I don't have a plan to add this feature, but you can execute Automa workflow from your website by dispatching JavaScript `CustomEvent`. See https://docs.automa.site/blocks/trigger.html#trigger-using-js-customevent

You have to manually create forms input where the user inputs the workflow variables value.

**Comment by macerd** [comment]
@Kholid060 Thanks for the feedback.
