### ISSUE TITLE
CustomEvent not working & Seeing The JS Code being executed

### ISSUE THREAD

**Issue by Visakh47** [AutomaApp/automa#1416]
Is there anyway I could see the JS code being executed while the workflow runs? Also, i have tried executing this code in the console, trying to trigger a workflow i created, there was no response other than "true" in the console end & no actions in the workflow were performed. 
window.dispatchEvent(new CustomEvent('automa:execute-workflow', {
	detail: { id: 'ib5Df_QZZj7vzlMao9NUT' }
}));

**Comment by Kholid060** [comment]
Try `__automaExecuteWorkflow` as the event name, and if it's still not working, try to re-install Automa. Back up your workflows in the settings before uninstalling Automa.
