### ISSUE TITLE
Forms Block Fails to Write Text But Logs Say Everything's Fine

### ISSUE THREAD

**Issue by Erinesta** [AutomaApp/automa#1417]
Hello all. I am trying to make an Automa script for entering two columns of data from a Google Sheet into a website. It runs greet for the most part and succeeds in entering the data into the first form. However, nothing is entered into the second form field. Incidentally, there is no error in the logs and the workflow succeeds (without entering the data in the second form).

The selector for the second form is shown here

.cke_wysiwyg_frame |> p 

![image](https://github.com/AutomaApp/automa/assets/33264800/30ee96df-7107-479e-a588-c06bebe6b043)

This is my form value {{loopData@emails.Description}}

The workflow runs fine until the second form:

![image](https://github.com/AutomaApp/automa/assets/33264800/73583d78-34a8-484a-9a0f-562ab1b66825)

When the workflow runs, nothing is entered into the second form.

But Automa doesn't throw an error and the logs show that the entire workflow is an unmitigated success!

![image](https://github.com/AutomaApp/automa/assets/33264800/a874bcba-7986-4615-9faa-dd7dc5dbdb7f)

I have tried running the second form in debug mode but it still doesn't help. I have also tried choosing the parent selector of the form, but the results are the same.

 - OS: [ Windows 10.0.19045]
 - Browser: [Google Chrome 117.0.5938.132]
 - Extension Version: [v1.28.14]

I must say that although I have generated a few successful scripts with Automa in the past, I am quite the novice with coding. Any help will be much appreciated.

**Comment by Kholid060** [comment]
You have to enable the "Debug mode" in the Form block settings if you want to input a text into a WYSIWYG editor.
![image](https://github.com/AutomaApp/automa/assets/22908993/56efc81c-940d-4d31-83e9-1ef58d5f1cc8)

**Comment by Erinesta** [comment]
Thanks @Kholid060 for getting back. Even with debug mode enabled on the form block, it still doesn't work. And it still doesn't bring up any error.

I have even tried enabling debug mode for the entire workflow. But when I do, the workflow throws an error on the previous form. This is one is a head-scratcher.

**Comment by Erinesta** [comment]
I have finally succeeded! Through trial and error, I used Firefox and the #Description (text area) selector, and the script was able to enter text into the 2nd form. However, when I try the same selector in Chrome, it still doesn't work whether debug mode is on or off. So, I still don't know what the issue was in the first place.

**Comment by SuperTempAccount** [comment]
@Erinesta hey do you get console logs when running with debug on by any chance?
I don't seem to be able to get any when the context is background.

**Comment by Erinesta** [comment]
As a matter of fact, I am able to get access the logs. 

![image](https://github.com/AutomaApp/automa/assets/33264800/e2e187a0-1892-48e9-b6db-2dee52bfd10e)

I can access them in real-time as the script is running and after @SuperTempAccount .
