### ISSUE TITLE
Popup.html does not close in Automa CEB after workflow is complete

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1418]
Automa CEB has an issue where if you run a workflow the popup.html stays up even after the workflow is complete which is annoying for one but it also messes up if your input parameters are in the trigger block. If in the trigger block, once you complete one workflow and try to run another one that requires parameters the popup will be blank (if you dont close the popup manually each time a workflow is run) This is not an issue if the parameters are gotten from a parameter block prompt. Still doesn't close once complete though either way.

**Describe the solution you'd like**
Just have the popup.html close once the workflow is complete. Also please add in a stop button in the customize section or an ability to right click and stop the running workflow.

**Comment by Kholid060** [comment]
Fixed
