### ISSUE TITLE
Automa CEB Versions Past 9.9.9

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1422]
**Describe the bug**
Automa CEB does not allow versions past 9.9.9 to be published. It "publishes" it but does not appear in the version history to be downloaded.

**Expected behavior**
Allow versions starting with 10.0.0 to be published.

**Additional context**
Tried 11.0.0 and other two digit numbers and it did not work despite the draft version saying the correct version number and able to be downloaded. Just can't publish. Also a feature to remove past versions would be GREAT.

**Comment by Kholid060** [comment]
It should be fixed now
![image](https://github.com/AutomaApp/automa/assets/22908993/5cd861b3-901d-455f-9d1d-6da1ccafb884)
