### ISSUE TITLE
Automa CEB stop button

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1426]
Hi,

When you execute a workflow in an extension, you always have a popup window. When you use parameters, this is logical. But when you don't use them, it should not be mandatory to keep it just to have the ability to stop a workflow.

So, as you have a "Play" button besides each workflow, it could be interesting to have a "Stop" button too, and maybe a "global" Stop button too, to stop all the workflows in the extension at the same time :)

**Comment by Delusionnnn** [comment]
+1 I've been needing this since day 1. Also ability to bind a global stop button (for example to right click dropdown) would be great!

**Comment by Raisrahman37** [comment]
I experienced the same thing. At start tab the workflow is closed. Please Fix itu🙏

**Comment by Kholid060** [comment]
The stop button is now added beside the play button. For the "global" stop button, you can add it manually to your extension by going to the "Interface" section of the extension on the Automa website, adding a button, adding an event handler, and then selecting the "Stop all running workflows" option.

![image](https://github.com/AutomaApp/automa/assets/22908993/ef9e41af-6e82-4fe4-b846-7a61e8ac5f54)

**Comment by sunnmagic** [comment]
Great, thanks!
