### ISSUE TITLE
Bug: Concurrently execute

### ISSUE THREAD

**Issue by Siykt** [AutomaApp/automa#1430]
I encountered some issues while attempting to execute `automa` concurrently:

## handlerForms

Due to the use of `elements.fouce()` + `debugger.Input.dispatchKeyEvent`, the two concurrent `handlerForms` interfere with each other, resulting in incorrect input.

![image](https://github.com/AutomaApp/automa/assets/44022526/804530db-5b92-47b2-8d33-0681e40229f5)

## WorkflowWorker

The setting of `WorkflowWorker.debugAttached` depends on the preceding `active/new/switch Tab` block, which causes the debugger to detach incorrectly.

![image](https://github.com/AutomaApp/automa/assets/44022526/25d3cb42-87d6-4bc6-8b06-80234474ce26)

## To Reproduce
Steps like:

![image](https://github.com/AutomaApp/automa/assets/44022526/75c9f41d-13b4-41e3-a47e-1c0673a6a36e)

**Comment by Delusionnnn** [comment]
+1 

In my experience I’ve never been able to run two workflows that require active tab input to run properly due to this limitation. In automa CEB a worker is generated for each extension and it avoids this partially but that’s the only work around I found.

**Comment by Siykt** [comment]
Bad `breakpoint` state:

![1696948711837](https://github.com/AutomaApp/automa/assets/44022526/f1c337e5-970c-456f-9c92-6e70c0415d3c)
