### ISSUE TITLE
how to add auth proxy?

### ISSUE THREAD

**Issue by CLannadZSY** [AutomaApp/automa#1437]
**Describe the bug**
how to add auth proxy

**To Reproduce**
1. change host: `http://127.0.0.1:7890`
2. this proxy work fine
3. when I use other new proxy, need auth, like this: `http://username:password@host:7890`, it's not work, why?
my username, password, host, port are correct, I can use this auth proxy in python code

**Screenshots**
use `http://127.0.0.1:7890` proxy
![image](https://github.com/AutomaApp/automa/assets/38000492/a88112af-db42-4858-a469-d71b2c1ac624)

use `http://username:password@host:7890` proxy
![image](https://github.com/AutomaApp/automa/assets/38000492/80907705-c887-48db-9fc5-4edeac9ed54b)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Google Chrome
 - Extension Version: v1.28.15

**Comment by Kholid060** [comment]
The Proxy block doesn't support Auth proxy.

**Comment by CLannadZSY** [comment]
> The Proxy block doesn't support Auth proxy.

Are there any plans to support this feature?

**Comment by Kholid060** [comment]
I don't have a plan to support this feature because it will require additional permission, making it longer to review when publishing it into Chrome WebStore.

**Comment by CLannadZSY** [comment]
😔
