### ISSUE TITLE
I've used a form component, but I can't get the selection box to pop up. How do I configure it to make the selection box appear?

### ISSUE THREAD

**Issue by turing1989** [AutomaApp/automa#1440]
**Describe the bug**
![image](https://github.com/AutomaApp/automa/assets/17975927/4eed7018-2b7d-4761-bf0e-da6558c00882)

我使用了form组件，但是无法弹出选择框，需要怎样设置才能弹出选择框？

I've used a form component, but I can't get the selection box to pop up. How do I configure it to make the selection box appear?

**Comment by Kholid060** [comment]
Have you tried using the Click Element block?

**Comment by turing1989** [comment]
https://github.com/AutomaApp/automa/assets/17975927/32f97b96-7201-4703-9ddf-e9e599888e14

i've user a form, input textarea,but do not show selection .

**Comment by ZaneYork** [comment]
试试使用jQuery来的trigger函数，触发目标组件的click或者blur事件
