### ISSUE TITLE
Fill forms from an excel or csv file.

### ISSUE THREAD

**Issue by Leroy-X** [AutomaApp/automa#1446]
**Is your feature request related to a problem? Please describe.**
Hi, I need to fill a form with a certain value from an excel file. And each loop uses different values in the excel file (such as A1, A2, A3, increasing in sequence). When editing the form block, I only see the value option. What should I do? I googled for a long time and couldn't find a way.
Thank you so much!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kholid060** [comment]
You can import your CSV file into your workflow by using the [Insert Data block](https://docs.automa.site/blocks/insert-data.html#import-file) like the below image and from that, use the Loop Data block to loop through the CSV values.

![image](https://github.com/AutomaApp/automa/assets/22908993/4b2d0179-1fb7-4cb9-808b-4db697bb1cbc)

Note: the Insert Data block doesn't support Excel files (xls/xlsx).

**Comment by Leroy-X** [comment]
@Kholid060 Sorry, this is my first time using Automa. Thank you very much for your prompt answer. 

I referred to [this tutorial](https://www.youtube.com/watch?v=Y_bpYKZd_Fw) to learn variables. Everything seems to be going in the right direction.

The second question is, after I imported the data, some characters were not in English and were displayed as garbled characters. How should I solve the problem?

BTW, The .csv file I exported using libreoffice. It seems to be related to text encoding.

**Comment by Kholid060** [comment]
When you preview the data inside the Insert Data block, it should be like this
![image](https://github.com/AutomaApp/automa/assets/22908993/94a6cdb7-650b-4afd-a1ae-5751b1f9bafb)

In the Loop Data block, select the `variable` option and input the variable name the same as the one you input in the Insert data block. In this case `someVariableName` (see previous image).

![image](https://github.com/AutomaApp/automa/assets/22908993/4de8ffd0-6959-4525-b7d7-a4b96cbb4dda)

**Comment by Leroy-X** [comment]
It works now, I prefixed the variable names with $$ before.
Thank you very much for your kind help :D
