### ISSUE TITLE
CSS selector adds a post function, and this post function can be configured for global application

### ISSUE THREAD

**Issue by enjoy-wind** [AutomaApp/automa#1451]
**Is your feature request related to a problem? Please describe.**

When we maintain old projects, the code specifications may not be strict. At this time, the shortest selector can search for multiple nodes, causing the script to fail.

**Describe the solution you'd like**

I want to add a pre-function when running the script. If the selector has multiple nodes, I can write a function to return the required node.

**Describe alternatives you've considered**

For example, this function can be based on whether it and its parent node are displayed as the only condition. Of course, this part is customized according to different projects and can be written by the developer himself.

**Additional context**

**Comment by Kholid060** [comment]
You can use the JS code block for that. In the JS code block, write your logic and mark the element you require by setting an attribute or class to that element. And use that attribute or class you added before as the selector in the next block.
