### ISSUE TITLE
How to trigger blocks using JS CustomEvent

### ISSUE THREAD

**Issue by Vader16039** [AutomaApp/automa#1452]
Is there any way to trigger blocks inside a workflow by using JS CustomEvent?

In the Automa docs there is example how to trigger a workflow using JS CustomEvent. Is there any similar way to trigger a block inside a workflow.

![image](https://github.com/AutomaApp/automa/assets/136983544/f9802715-5a4a-4d07-a0a3-115083f62620)

**Comment by Kholid060** [comment]
Automa doesn't support trigger block using JS custom event.
