### ISSUE TITLE
Button with selector didn't clicked 

### ISSUE THREAD

**Issue by bangnokia** [AutomaApp/automa#1459]
**Describe the bug**
Open the new tab, click the button with the selector `button[id="download-free"]`, The button exists on the screen but it wasn't clicked

**To Reproduce**
I attach the video and the workflow here
[click to element.automa.json](https://github.com/AutomaApp/automa/files/12926374/click.to.element.automa.json)

**Expected behavior**
Button should be clicked

** Video **
https://github.com/AutomaApp/automa/assets/5652494/2b6c70ca-4c18-4e89-97f9-0191e4726fcc

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Extension Version: 1.28.15

**Comment by Siykt** [comment]
the selector find many el:

![image](https://github.com/AutomaApp/automa/assets/44022526/991cf925-229b-433f-87fb-d610bd6410e0)

**Comment by bangnokia** [comment]
@Siykt  thanks, I didn't expect that there are 2 id element in the same page. But then I change to `.content_download > span`, I can see there is only one element
![image](https://github.com/AutomaApp/automa/assets/5652494/7ec8e384-242e-499c-a382-e1ec6091cd6b)

It still didn't click the button

**Comment by Siykt** [comment]
I haven't been able to reproduce your issue. Could you provide the execution logs?

**Comment by bangnokia** [comment]
@Siykt , thanks, that's werid.
This is my latest log and workflow
[click to element.automa(1).json](https://github.com/AutomaApp/automa/files/12928606/click.to.element.automa.1.json)
[[17-10-2023, 19 22 29] click to element - logs.txt](https://github.com/AutomaApp/automa/files/12928626/17-10-2023.19.22.29.click.to.element.-.logs.txt)

<img width="1385" alt="image" src="https://github.com/AutomaApp/automa/assets/5652494/4269a089-bbe4-4c6f-8102-a96b49e73954">


I'll try disable plugins and let you know

**Comment by Kholid060** [comment]
Try to use `#download-free.btn-tablet` as the selector, and the `timeout` error happens when the tab still loading for more than 30 seconds. You can disable the tab loading timeout by going to the settings > Blocks section > Set "Tab load timeout" to 0

![image](https://github.com/AutomaApp/automa/assets/22908993/71674fa1-53be-42eb-b4c4-ed05c5fcd7d7)

**Comment by bangnokia** [comment]
@Kholid060 , thank you. it works now.
Now I understood why 😅. It seems the website is loaded (the button element), but some how it still loading other resources (loading indicator on the favicon slot) such as banners, images, videos,... The extension wait the page finished loading state then it run the block action, that why I got timeout almost times.
