### ISSUE TITLE
QOL see raw JS of each block

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1464]
**Is your feature request related to a problem? 

No problem, just QOL feature**

It would be really convenient to be able to see and edit the raw javascript of each block so we can build our own JS blocks that are built on top of existing code.

**Describe the solution you'd like**
Allow to edit and see the raw JS of each block.

**Comment by Kholid060** [comment]
I don't think I'll add this feature because it'll require a re-work of the workflow engine, and Manifest V3 will make it harder to execute 3rd party code when Automa decides to migrate to that.
