### ISSUE TITLE
Trigger Block "Run on when active tab URL equals value" feature request

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1469]
**Is your feature request related to a problem? Please describe.**
No. My request is for more implementation of the trigger block. There is a way to trigger when "visiting a website" but problem is that there is no way to trigger "when website URL matches XYZ". Lot of forums and such dont technically act like a "load new url" and instead like an "update url" which won't trigger the certain workflow. 

**Describe the solution you'd like**
Add in the ability so that when active tab URL = RegEx or Match URL value then trigger workflow.

**Describe alternatives you've considered**
I can't see how this would be done with java since there needs to be a trigger block with each workflow, right?

**Comment by Siykt** [comment]
@Delusionnnn 
I looked at the source code for the implementation, and it does have detection for updating HistoryState.

Have you tried enabling the "Support SPA website" option in the "when visit a website" trigger?

see #926

**Comment by Kholid060** [comment]
Like @Siykt said, you need to enable the "Support SPA website" option. So Automa will match the tab URL when it's updating.

**Comment by Kholid060** [comment]
If that is the case, maybe you can set up your workflow like the below image and uncheck the "Support SPA website" in the "When visiting a website" trigger. 
![image](https://github.com/AutomaApp/automa/assets/22908993/19a3bf43-548d-46bf-bdab-173b825f3cad)

The Conditions block is for checking if there's a `continue` variable. If `continue` variables exist, it will continue the workflow execution. If not, it will inject the Javascript block.
![image](https://github.com/AutomaApp/automa/assets/22908993/47ec31ee-20e0-4a90-9b2d-bc9d04963c88)

The Javascript Block is for checking if the URL is changing or not. Input it with the below codes. There are some variable values you need to change like `URL_REGEX` and `WORKFLOW_ID` variables.
```js
const URL_REGEX = /[a-z]/; //replace it with your regex here
const WORKFLOW_ID = 'workflow-id'; //replace it with the current workflow id
const ATTR_NAME = 'my-workflow-js';

let workflowRunningURL = null;

function runWorkflow() {
  const isMatchURL = URL_REGEX.test(window.location.href);
  if (
    !isMatchURL ||
    workflowRunningURL === window.location.href
  ) return;

  // assign the current URL so it doesn't run twice at the same URL
  workflowRunningURL = window.location.href;

  const workflowEvent = new CustomEvent('automa:execute-workflow', {
    detail: {
      id: WORKFLOW_ID,
      data: {
        variables: {
          continue: true
        }
      }
    },
  });
  window.dispatchEvent(workflowEvent);
}

(() => {
  const isJSAlreadyInjected = document.body.hasAttribute(ATTR_NAME);
  if (isJSAlreadyInjected) return;

  document.body.setAttribute(ATTR_NAME, 'true');

  // You can use another method here to check if the website URL changing (e.g. MutationObserver)
  setInterval(runWorkflow, 1000);
  automaNextBlock()
})();

```

**Comment by Siykt** [comment]
And set `JavaScript Code Block` setting

<img width="603" alt="image" src="https://github.com/AutomaApp/automa/assets/44022526/6839982d-cb13-4af3-b246-78ff2ddd38a3">

**Comment by Delusionnnn** [comment]
Thanks guys. I tried to get it to work but I don't understand the context of what it doing to be able to replicate it properly. It causes errors that I dont have time to figure out right now. In the future, maybe if trigger by code could be added it would solve these issues. Just a request after all.
