### ISSUE TITLE
Automa CEB: "Link" block bug

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1477]
Hi,

When you run an extension with a "Link" block and the setting "Open in a new tab" active, the current tab is updated too with the same url. It doesn't happen in the "workflow version".

I don't know if it's related to this issue, but I got these error messages in the extension:

![image](https://github.com/AutomaApp/automa/assets/50998197/90dbde88-b153-433c-9480-838610817f6b)

**Comment by Kholid060** [comment]
Fixed
