### ISSUE TITLE
Automa CEB popup.html bug

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1486]
**Describe the bug**
Popup.HTML for the Automa CEB won't close after a workflow that injects an element into a page. 

**To Reproduce**
Right Click > Run Workflow that ends in create element > wait and then the popup.html will stay even though no workflows are running.

**Expected behavior**
Popup.HTML will close upon completion of workflow like it does the others.

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/141815049/36b3557a-8863-424f-ab7a-e398a531803e)

Workflow that causes it: 
![image](https://github.com/AutomaApp/automa/assets/141815049/2a41cd70-b9f0-4298-87f1-722df4077ede)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Extension Version: 1.28.17

**Comment by Kholid060** [comment]
Fixed
