### ISSUE TITLE
Support for Orion browser

### ISSUE THREAD

**Issue by Aboodzwz** [AutomaApp/automa#1494]
Orion is a browser client that can use both Firefox and chrome extensions 

It’s the only browser that has extension’s support on iOS/IpadOS 

automa works on Orion but partially 
The dashboard doesn’t load 

is it possible to fix this or this is orions fault?
Thanks

**Comment by Kholid060** [comment]
> is it possible to fix this or this is orions fault?

I don't think I can fix this, because I don't have an iOS device and I'm not planning to support mobile devices.
