### ISSUE TITLE
Go back button can not show on the browser.

### ISSUE THREAD

**Issue by tuanann123** [AutomaApp/automa#1495]
Go back button can not show on the browser.

Hello.
I can see go back button can not show on the chrome when I run  a script.
And I can see you have not fixed it yet.
Can you tell me more about that?
Thanks.

**Comment by tuanann123** [comment]
I found there are a few places that use your source code and it has a back button.
I wonder if you intentionally hid it?

**Comment by Kholid060** [comment]
Can you explain more about what you mean by the "Go back" button? Or can you take a screenshot of it?
