### ISSUE TITLE
Keyboard Press, Form Fill Cannot Reply Twitter (X) Post - RichText fill failed

### ISSUE THREAD

**Issue by zerominh** [AutomaApp/automa#1508]
**Describe the bug**
Cannot insert text in reply box Twitter (X) using Keyboard Press and also Form Fill

**To Reproduce**
In screen shot for detail

**Expected behavior**

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/30307402/63f4e41d-f888-4201-9e79-8915fcb0973a)
![image](https://github.com/AutomaApp/automa/assets/30307402/ef116dd4-0750-47db-84e5-02e00c958b7f)
![image](https://github.com/AutomaApp/automa/assets/30307402/54bb50d5-df42-463e-ac18-8ab772d08b2e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.19

**Additional context**

**Comment by Kholid060** [comment]
You have to enable the "Debug mode" in the block settings of the Form block
![image](https://github.com/AutomaApp/automa/assets/22908993/44b5bd01-c944-404e-b35a-7ee732306eea)

**Comment by xyunsh** [comment]
> You have to enable the "Debug mode" in the block settings of the Form block ![image](https://user-images.githubusercontent.com/22908993/281622055-44b5bd01-c944-404e-b35a-7ee732306eea.png)

Is there a working example?

**Comment by Kholid060** [comment]
> > You have to enable the "Debug mode" in the block settings of the Form block ![image](https://user-images.githubusercontent.com/22908993/281622055-44b5bd01-c944-404e-b35a-7ee732306eea.png)
> 
> Is there a working example?

You can try this
[X.automa.json](https://github.com/AutomaApp/automa/files/13372159/X.automa.json)

**Comment by xyunsh** [comment]
> > > You have to enable the "Debug mode" in the block settings of the Form block ![image](https://user-images.githubusercontent.com/22908993/281622055-44b5bd01-c944-404e-b35a-7ee732306eea.png)
> > 
> > 
> > Is there a working example?
> 
> You can try this [X.automa.json](https://github.com/AutomaApp/automa/files/13372159/X.automa.json)

Thanks for reply.

But this is not working on Edge with macOS

I found another way that works, use javascript block like this:
```
document.execCommand('insertText', false, 'Hello world');
automaNextBlock()
```

**Comment by xyunsh** [comment]
[https://stackoverflow.com/questions/57879322/how-can-i-enter-data-into-a-custom-handled-input-field/57900849#57900849](https://stackoverflow.com/questions/57879322/how-can-i-enter-data-into-a-custom-handled-input-field/57900849#57900849)
<https://stackoverflow.com/questions/42101134/chrome-extension-for-facebook-clone-automatic-user-is-listening-to/42101620#42101620>
