### ISSUE TITLE
Module Not Found Error in decryptFlow.js

### ISSUE THREAD

**Issue by dgo2dance** [AutomaApp/automa#1512]
Description:
I encountered an error while running the code. The error message states that there is a module not found issue in the decryptFlow.js file. Specifically, it cannot resolve the module getPassKey in the /Users/shuyongduan/Downloads/automa-1.28.18/src/utils directory.

Steps to Reproduce:

Clone or download the automa-main repository from the GitHub page.
Run the code  yarn install            yarn dev
Expected Behavior:
I expected the code to run without any errors and successfully resolve the getPassKey module.

Please let me know if there is any further information or clarification needed to resolve this issue. Thank you for your assistance.

**Comment by Kholid060** [comment]
https://github.com/AutomaApp/automa?tab=readme-ov-file#project-setup
