### ISSUE TITLE
how to debug startWorkflowExec in chrome

### ISSUE THREAD

**Issue by qianzhangdu** [AutomaApp/automa#1513]
I can debug the function startWorkflowExec in  /src/workflowEngine/index.js 
<img width="986" alt="image" src="https://github.com/AutomaApp/automa/assets/20161052/088d0e7a-8479-421b-a43d-19d4bffbd059">

but I can not debug  the function startWorkflowExec
<img width="956" alt="image" src="https://github.com/AutomaApp/automa/assets/20161052/8cd36afd-e4be-4174-beff-b2a7775cadd5">

did i find the wrong execute function  ？

**Comment by small-carbon** [comment]
我执行下图红框里面的流程，调试怎么进不去这个/src/workflowEngine/index.js 中的函数 startWorkflowExec
![image](https://github.com/AutomaApp/automa/assets/887531/85fa321f-902a-4b58-af18-7c1c7e749bea)
