### ISSUE TITLE
Im having the same issue on handle download block as in this discussion

### ISSUE THREAD

**Issue by lkkfarcap** [AutomaApp/automa#1518]
### Discussed in https://github.com/AutomaApp/automa/discussions/1517

<div type='discussions-op-text'>

<sup>Originally posted by **sparkls0** November  8, 2023</sup>
Hey pals, I am really confused about the new system regarding the handle download

The only thing I don't get and I'm not able to do, is retrieve the /file/path inside a variable.

I've followed Automa's docs guidelines

![CleanShot 2023-11-07 at 23 22 57](https://github.com/AutomaApp/automa/assets/48011728/db4fa55b-5e9d-47d6-a053-46205b7579b1)

But wait, what? That's not working, am I missing something? 

So here's what I did, I targeted my picture using an annoying HTML formula (to not rely on dynamical class), put that in selector in the save assets. It contains the src containing the picture url. 

![CleanShot 2023-11-07 at 23 23 59@2x](https://github.com/AutomaApp/automa/assets/48011728/98922862-c656-4dc0-ba3d-f2020c891a50)

Here is it, just for the sake of my example : 

div[role="figure"][aria-label^="Selected: Variation"] > div[tabindex="0"] > span > img

So, I saved items's download IDs, assigned to a variable, gave that variable to the Handle Download's 'File download ID' 

![CleanShot 2023-11-07 at 23 25 03@2x](https://github.com/AutomaApp/automa/assets/48011728/fe8cd825-a944-4fa9-ade0-466bedf4ca9f)

And dang, got the error 'Download id is not a number', right, it's not, it is an array containing number

![CleanShot 2023-11-07 at 23 25 42](https://github.com/AutomaApp/automa/assets/48011728/5910adff-b3c4-4a2d-af5c-517b62dfc455)

So, what am I missing?

</div>

**Comment by GmwEnterprise** [comment]
[](url)
![Snipaste_2023-12-20_17-13-26](https://github.com/AutomaApp/automa/assets/37724595/94639d2d-6e11-44a6-ba2b-ae6070a1c21c)
Version: 1.28.24

I want to obtain the path to download the file, but I cannot obtain it using the "Handle Download Block" component, and the variables are not printed. I am very confused.
![Snipaste_2023-12-20_17-13-57](https://github.com/AutomaApp/automa/assets/37724595/a3908a9c-339a-4112-bb3b-6f37450f7c0e)
![Snipaste_2023-12-20_17-14-10](https://github.com/AutomaApp/automa/assets/37724595/1cedb54d-6473-4792-a477-3868e71e
![Snipaste_2023-12-20_17-15-27](https://github.com/AutomaApp/automa/assets/37724595/b23acbfa-c99a-4565-9328-61a492888976)
![Snipaste_2023-12-20_17-15-34](https://github.com/AutomaApp/automa/assets/37724595/ec8a5e07-5896-4213-8b21-5973e639b5b9)
9439)
