### ISSUE TITLE
Scroll Element Not Working

### ISSUE THREAD

**Issue by zerominh** [AutomaApp/automa#1523]
**Describe the bug**

**To Reproduce**

Go to url of twitter (X) post
Delay 5000
Scroll down
Delay 5000
Expected behavior

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/30307402/81ba66d0-2f30-40e9-987b-bd7be9c935c2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.20 (dev version)

**Additional context**

**Comment by Kholid060** [comment]
It does not work because the tweet is still loading when executing the Scroll Element block. So, use the Element Exists block instead of the Delay block before the Scroll Element block.

[X.automa (1).json](https://github.com/AutomaApp/automa/files/13372883/X.automa.1.json)

**Comment by zerominh** [comment]
It still scroll only 1 time although I repeat 10 times 
![image](https://github.com/AutomaApp/automa/assets/30307402/ca5e0b71-b56e-4170-9cd6-789f5b212395)

https://github.com/AutomaApp/automa/assets/30307402/b2c2b837-a7a4-4668-b790-2d9542105acb

**Comment by Kholid060** [comment]
It's because you do not enable the "Increment vertical scroll" option. When it's not enabled, it only scrolls into the coordinate you specified.
