### ISSUE TITLE
Overflow on the description of the checkbox trigger's parameter

### ISSUE THREAD

**Issue by slavi010** [AutomaApp/automa#1530]
**Describe the bug**
Overflow on the description of the checkbox trigger's parameter.

**To Reproduce**
- Add a checkbock on your Trigger
- Add a long description
- Run the workflow

**Expected behavior**
No overflow.

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/49365528/ae4650c0-9c69-46aa-b037-3efdb0bffc2d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Extension Version: 1.28.21

**Additional context**
Related issue: #1493

**Comment by MarcusXavierr** [comment]
I just removed the `whitespace-pre` class and it solved the problem

![image](https://github.com/AutomaApp/automa/assets/59923581/b6921978-58ba-4e37-894c-045c098fdb5c)
