### ISSUE TITLE
Automa CEB: Unable to add workflows

### ISSUE THREAD

**Issue by Vader16039** [AutomaApp/automa#1534]
Getting error while adding workflows in Automa CEB.

![image](https://github.com/AutomaApp/automa/assets/136983544/5f38ebdb-6afa-4133-b9af-e6c798f6df3e)

![image](https://github.com/AutomaApp/automa/assets/136983544/24ff7045-e627-4d0a-bd38-550cecabcdac)

 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: v1.28.21

**Comment by kolampixel** [comment]
need new update, also happened to me
