### ISSUE TITLE
Keyboard Shortcuts settings not working properly

### ISSUE THREAD

**Issue by BrOrlandi** [AutomaApp/automa#1537]
**Describe the bug**
I have changed my keyboard shortcuts to open Automa Extension on Chrome but the old shortcut still working.
It would be nice to be able to disable all keyboard shortcuts. Because it's conflicting with other shortcuts that I use and as I can't disable them and when I change it, it still works on the old shortcut, the only option I have is to disable the extension when I'm not using it.

**To Reproduce**
1. Go to shortcuts settings
2. Change the "Page > Workflows" shortcut to anything else
3. In any browser tab press Option + 'A'
4. It will open the Automa extension window on Workflows page

**Expected behavior**
It should not open the Automa extension

**Screenshots**
My shortcuts are randomly set so I never press them accidentally.
<img width="1021" alt="image" src="https://github.com/AutomaApp/automa/assets/1594658/608bfd7b-4f7a-4e30-877f-978f933c1b95">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave Browser (Chromium based)
 - Extension Version: 1.28.21

**Comment by Kholid060** [comment]
For that shortcut, you need to change it on the `chrome://extensions/shortcuts` page. On that page, click the pencil icon and leave blank to remove the shortcut.

![image](https://github.com/AutomaApp/automa/assets/22908993/ea29a33f-ecea-4503-b351-386db921bc5b)
