### ISSUE TITLE
Invalid data to loop through

### ISSUE THREAD

**Issue by a24ac1** [AutomaApp/automa#1539]
![image](https://github.com/AutomaApp/automa/assets/146932730/9120d6de-c34a-49c9-92ea-f7aaafdce7b1)
![image](https://github.com/AutomaApp/automa/assets/146932730/fca39e8f-0b5c-4b35-84c1-789e499ff645)
![image](https://github.com/AutomaApp/automa/assets/146932730/42020fb9-614c-4404-9479-af51bf3c22f4)

Http request > Response > Assign to variable ($$jdatas) > Loop through

**Comment by Kholid060** [comment]
In the "Variable name" name of the Loop Data block, you only need to input the name of the variable. For example `$$jdatas`

![image](https://github.com/AutomaApp/automa/assets/22908993/74da3370-63fd-4ca6-bcb4-23420c5d5e02)

**Comment by a24ac1** [comment]
I'm still having problems.

is there a way to loop data, so I want to make truger > http request it will take json array:

[ { "name": "Google 1", "url": "https://google.com" }, { "name": "yahoo 2", "url": "https://yahoo.com" } , { "name": "facebook 2", "url": "https://facebook.com" } ]

then the array is in the data loop
