### ISSUE TITLE
Cannot syn automa with github

### ISSUE THREAD

**Issue by xaoxu2** [AutomaApp/automa#1542]
**Describe the bug**
The automa site is down, cannot connect to github account.

**To Reproduce**
1. Go to '[(https://www.automa.site/auth)'
2. Click on 'Continue to github'

4. See error : This site can’t be reached

**Expected behavior**
Need the site to work then we can log in github account to automa

**Screenshots**

<img width="734" alt="image" src="https://github.com/AutomaApp/automa/assets/142032043/6d8ed70e-d658-43ce-aa14-6b36943281a2">

**Comment by kolampixel** [comment]
Same. today cannot sync with google

![image](https://github.com/AutomaApp/automa/assets/121801559/d4d7357c-5b2a-410b-b762-e0e5ad5e713e)

**Comment by waruingugi** [comment]
Facing the same issue here
