### ISSUE TITLE
Critical problem with keyboard shortcuts

### ISSUE THREAD

**Issue by dziudek** [AutomaApp/automa#1546]
**Describe the bug**
The extension opens dashboard when using "Option + a" shortcut. Unfortunately e.g. in Poland this shortcut is used to write "ą" letter (probably in other languages this problem occurs too). What makes this extension unusable at this moment for many people.

And what is worse - it is impossible to disable this behaviour under shortcuts settins or it is just not working - I have replaced all shortucts, restarted the browser and still problem appears.

**To Reproduce**
1. Use "Option + a" shortcut
2. See extension dashboard opening

**Expected behavior**
Extension should have an option to disable keyboard shortcuts which opens the dashboard - there is no such option

**Desktop (please complete the following information):**
 - OS: mac OS Sonoma
 - Browser: Google Chrome
 - Extension Version: 1.28.21

**Additional context**
It would be great to have an option to disable keyboard shortcuts at all, because in such extension which works in the background the whole time it can lead to unexpected behaviours

**Comment by Kholid060** [comment]
You can follow this to disable the shortcut,

https://github.com/AutomaApp/automa/issues/1537#issuecomment-1813826796
