### ISSUE TITLE
Automa CEB : Impossible to add a Workflow to an extension

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1547]
Hi,

It is impossible to add a Workflow in an extension, it always ends with a "Someting went wrong":

![image](https://github.com/AutomaApp/automa/assets/50998197/8d816175-a1ec-4a82-b07d-41f88cb785b1)

Thanks!

**Comment by Raisrahman37** [comment]
Yes. We Have same

**Comment by sunnmagic** [comment]
If it can help you @Kholid060: 

![image](https://github.com/AutomaApp/automa/assets/50998197/363fa449-8afd-4a09-b863-442d84f04d88)

**Comment by kolampixel** [comment]
Still can't add workflow bro @Kholid060 
![image](https://github.com/AutomaApp/automa/assets/121801559/ba82593a-96cd-43f7-8024-5035362ce162)
