### ISSUE TITLE
Bug in automaNextBlock's nextBlockId?

### ISSUE THREAD

**Issue by Willy-J** [AutomaApp/automa#1551]
**Describe the bug**
When using nextBlockId in js code blocks, it seems to execute the block after the specified block rather than the specified block itself.

**To Reproduce**
I set up 3 js code blocks. Js0 is the executed block, and in js0 I have` automaNextBlock(null, {nextBlockId: 'myv7fq5'})`, where 'myv7fq5' is the id of js1.

**Expected behavior**
 I was expecting js1 to execute, but instead js2 executed. Is this a bug or feature?

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/32266792/81476a5e-036a-4560-a8bb-39a93838c5a4)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [Google Chrome]
 - Extension Version: [v1.28.21]

**Comment by a24ac1** [comment]
same problm
