### ISSUE TITLE
JavaScript Code can cause serious memory issues.

### ISSUE THREAD

**Issue by slavi010** [AutomaApp/automa#1553]
**Describe the bug**
JavaScript Code can cause serious memory issues (with the function automaRefData for example).

Its like the data inside aren't "garbaged" at the end of the JavaScript Code block (they are, at least, at the end of the workflow).

**To Reproduce**
Have at least 2 blocks:
One for inserting some data (tested with a string.length ~= 200 000 caracters) to a variable. Let call it 'test'.
The other one to get the 'test' variable via the function automaRefData.
Loop the JavaScript Code block.

**Expected behavior**
No memory leak.

**Screenshots**
![image](https://github.com/AutomaApp/automa/assets/49365528/94085d6a-006c-40ca-bff5-92e8c4763706)

![image](https://github.com/AutomaApp/automa/assets/49365528/accb0839-286c-4455-b8f0-8b8bdfb2d7d5)

![image](https://github.com/AutomaApp/automa/assets/49365528/ca49b935-0e3b-4788-8bd1-685b940b5721)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: Brave
 - Extension 1.28.21

**Additional context**
Maybe I just doing something wrong somewhere ? ^^'

Btw, thanks a lot for your help :D

**Comment by v-smwang** [comment]
Yes, I also have memory problems here, I did not test it separately, my workflow is more complicated, but I feel that automaRefData and automaSetData have memory problems, and the use of indexedDB also feels that there are memory problems.

**Comment by v-smwang** [comment]
This problem will cause the page to crash if it runs longer

**Comment by slavi010** [comment]
Well, I did a bit of more test and found super really wierd things like this:

![image](https://github.com/AutomaApp/automa/assets/49365528/220f57ec-9f7e-462e-a7ca-5d34ecd324fa)
=> No memory issue

![image](https://github.com/AutomaApp/automa/assets/49365528/f59184bd-2bc0-46cc-8c4d-a1ea7a471268)
=> Memory issue

![image](https://github.com/AutomaApp/automa/assets/49365528/0480e3fc-2501-4998-a289-c1c21412ff9f)
=> No memory issue

**Comment by Siykt** [comment]
The 'state' is storing too many log files.

![image](https://github.com/AutomaApp/automa/assets/44022526/5b267627-fcea-40ac-9cc1-d18ef159ef32)
![image](https://github.com/AutomaApp/automa/assets/44022526/332f884a-82a5-44d9-90c0-b41d5ab5fb6a)

**Comment by v-smwang** [comment]
Turn off the log and run it again. I'm testing it too

**Comment by v-smwang** [comment]
> The 'state' is storing too many logs.
> 
> ![image](https://user-images.githubusercontent.com/44022526/284935144-5b267627-fcea-40ac-9cc1-d18ef159ef32.png) ![image](https://user-images.githubusercontent.com/44022526/284936223-332f884a-82a5-44d9-90c0-b41d5ab5fb6a.png)
> 
> and jsblock not clean:
> 
> ![image](https://user-images.githubusercontent.com/44022526/284939291-8e0e5647-2aed-416b-8bb7-40762fa3e1e5.png)

Do you mean that every time the jsblock variable in the loop is not cleaned up, it keeps accumulating?

**Comment by Siykt** [comment]
yes, see:
![image](https://github.com/AutomaApp/automa/assets/44022526/0bc5632c-2016-40aa-a79a-3e920f20834b)

**Comment by v-smwang** [comment]
Yes, even if logging is turned off, snapshots of variables are still stored. It should be designed to be easy to find problems. It is normal to close the log, but the shutdown should also close the data snapshot, which is not done.

**Comment by v-smwang** [comment]
> Yes, even if logging is turned off, snapshots of variables are still stored. It should be designed to be easy to find problems. It is normal to close the log, but the shutdown should also close the data snapshot, which is not done.

@Siykt Am I right？

**Comment by Siykt** [comment]
this:
> src/workflowEngine/WorkflowEngine.js:309
```js
addRefDataSnapshot(key) {
    this.refDataSnapshotsKeys[key].index += 1;
    this.refDataSnapshotsKeys[
      key
    ].key = `##${key}${this.refDataSnapshotsKeys[key].index}`;

    const keyName = this.refDataSnapshotsKeys[key].key;
    this.refDataSnapshots[keyName] = cloneDeep(this.referenceData[key]);
  }
```

I think this is mainly used for debugging, because the logger actually stores directly into the indexedDB.

![image](https://github.com/AutomaApp/automa/assets/44022526/b14bd0ba-6039-4e10-8eae-d3c2f000b661)

**Comment by v-smwang** [comment]
@Siykt [https://github.com/AutomaApp/automa/issues/1556](url) Have any opinion on this problem？I'd like to discuss it with you

**Comment by Siykt** [comment]
I found that `refDataSnapshots` is completely a bunch of redundant data. And in `debugMode`, it only uses the last `referenceData`.

![image](https://github.com/AutomaApp/automa/assets/44022526/a6b62c38-3fcb-4a8a-beea-f85cdaff171d)

**Comment by Siykt** [comment]
@Kholid060 `jsblock` Execution context is background:

![image](https://github.com/AutomaApp/automa/assets/44022526/8b845bb6-efaf-4974-aa63-b891f6ba72dd)
