### ISSUE TITLE
Cannot read google sheet in AUTOMA CEB. 

### ISSUE THREAD

**Issue by Raisrahman37** [AutomaApp/automa#1558]
Please fix it sir. Cannot read the contents of the goggle sheet. 🙏

**Comment by lionkingc** [comment]
Same here,
Google sheets function didn't work today ,
It works before, I used it to update data to goole spreadsheets

Shared "[service@automa2.iam.gserviceaccount.com](mailto:service@automa2.iam.gserviceaccount.com)"

**Comment by GarryLaly** [comment]
Same here, I think because the server function is down/timeout. We can't access https://www.automa.site/ also
<img width="1121" alt="Screenshot 2023-11-23 at 15 03 19" src="https://github.com/AutomaApp/automa/assets/5617788/b1459e8b-db4e-4160-bae6-15d5d1861a14">

**Comment by REFLEXGAMING007** [comment]
Same here as well
![Screenshot_3583.jpg](https://github.com/AutomaApp/automa/assets/56241882/9f7c6521-c8ca-4a8a-b59f-42ba58d8e4ba)

Please fix it sir!!!
My whole workflow is stopped because of this 😞

**Comment by Kholid060** [comment]
Fixed
