### ISSUE TITLE
Automa site is not working

### ISSUE THREAD

**Issue by xaoxu2** [AutomaApp/automa#1561]
**Describe the bug**

**To Reproduce**
1. Go to '[automasite](https://www.automa.site/auth)'
2. Click on 'Sign in github'
3. See error : This site can’t be reached

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v0.12.0]

**Additional context**

**Comment by Kholid060** [comment]
Fixed
