### ISSUE TITLE
facebook send message form block

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#1566]
<img width="339" alt="image" src="https://github.com/AutomaApp/automa/assets/20383505/53fb1423-56c9-4090-b27f-8463a5420bbb">

form blcok no effect

**Comment by Kholid060** [comment]
Try using the click element block first with `[data-lexical-editor="true"]` as the element selector and then use the javascript code block and input the below code:

```js
document.execCommand('insertText', false, 'YOUR TEXT HERE');
```

Replace `YOUR TEXT HERE` with anything you want.

**Comment by whwh656** [comment]
thanks
