### ISSUE TITLE
Schedule: option to block all other workflow to run if that one workflow start to run

### ISSUE THREAD

**Issue by kocoten1992** [AutomaApp/automa#1575]
**Is your feature request related to a problem? Please describe.**
Hello, does current schedule only allowed one task to run? Is there an option to block other workflow to start when "the chosen" workflow start to run?

**Describe the solution you'd like**
Hi, some workflow need to access to "active tab", if other workflow start to run, I'm afraid it going to mess with "the chosen" workflow?

**Comment by Kholid060** [comment]
You can use the "Workflow State" block after the Trigger block, select the "Stop all workflows" option, and check the "Except for the current workflows" checkbox
![image](https://github.com/AutomaApp/automa/assets/22908993/853dd533-5424-42b5-b9f7-a233fe0d03ac)
