### ISSUE TITLE
Can't move connecting lines

### ISSUE THREAD

**Issue by user72356** [AutomaApp/automa#1585]
The docs shows handles on connecting lines. I can't figure out how to trigger the handles so I can customize the shape of the lines. The doc says to click on the line, I've tried single/double left/right clicks and that didn't work.

**Comment by Kholid060** [comment]
To customize the shape of the lines, you need to click the "block settings" and then click the "Lines" tab.

![image](https://res.cloudinary.com/chat-story/image/upload/v1666162997/automa/block-settings_ppatjo.gif)
