### ISSUE TITLE
[CEB]Can not display the workflow 

### ISSUE THREAD

**Issue by ohzxc** [AutomaApp/automa#1593]
**Describe the bug**
If the computer is on an internal network and cannot display the workflow in the plugin generated by Automa Chrome Extension Builder
 
**Screenshots**
![WeChat_20231216102711](https://github.com/AutomaApp/automa/assets/2950068/9558a456-0ceb-4ae1-888a-0dc0c6992762)

**Comment by Kholid060** [comment]
It only shows a blank page because the Automa CEB needs to fetch the workflows from the Automa Server.

**Comment by ohzxc** [comment]
> It only shows a blank page because the Automa CEB needs to fetch the workflows from the Automa Server.

Thank you for your replay. I hope to add this feature: the ability to build a plugin that can be used offline.
