### ISSUE TITLE
Can automa CEB automatically execute workflow after the browser is started?

### ISSUE THREAD

**Issue by yujun32** [AutomaApp/automa#1610]
My automa CEB browser extension works fine with manual click execution. 
But now I want to fully automate it through selenium.
I'm not very good at browser plug-in development, and the plug-in source code is obfuscated. Could you please give me some improvement ideas or examples?

**Comment by Kholid060** [comment]
If you want to execute a workflow after the browser is started, you can add the "On browser startup" trigger in the trigger block of the workflow. You can also execute a workflow by dispatching the Automa custom event on a website, see https://docs.automa.site/blocks/trigger.html#trigger-using-js-customevent.
