### ISSUE TITLE
Automa Marketplace : Automa's table isn't created when you download a Workflow

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1612]
**Describe the bug**
On the Automa Marketplace, on a workflow, when you click on "Add to extension", everything works fine, the table is created. But, if you choose to download the workflow, then import the json file, the table is not created, so all the blocks related to the table don't work.

**To Reproduce**
Try with any workflow which includes a table, like this one: https://www.automa.site/workflow/08EVrKgi8fpwB6b9ANR5X

Thanks!

**Comment by Kholid060** [comment]
Fixed
