### ISSUE TITLE
how select element inside shadow-DOM ?

### ISSUE THREAD

**Issue by trasferimento** [AutomaApp/automa#1624]
**Describe the bug**
ServiceNow site has deploy a new release ( Vancouver version ) ,  in which they have "moved" all the intersting data's elements inside a shadow-DOM :  using Chrome debugger this section start with 
<component1> 
        #shadow-root(open )
        <component2></component2>...
</component1>

Using the element selector  I can just select the element above/that "load" all the elements that I'm interesting in , for grabbing text.

Is there a special syntax ( CSS combinator ) to reach these elements ?   Like for elements inside iframe , I can use the CCS combinator |>, for instance component1 |> component2    ?

Using a tool similar to Automa App, Browserflow extension, I can reach these elements using  the CSS combinator   >>>  ( not working with Automa )

**Expected behavior**
Using element selector, being able to select elements inside this "shadow DOM"

**Screenshots**
![capture](https://github.com/AutomaApp/automa/assets/31535321/c8e82afe-36c5-4ad3-b8db-4baf292fbb89)

**Desktop (please complete the following information):**
Windows,  
Chrome,  
Automa Version: 1.28.26

**Comment by Kholid060** [comment]
Use `shadow-dom-selector >> element-selector` syntax

![image](https://github.com/AutomaApp/automa/assets/22908993/6441af50-7280-4699-bc52-8fe77b154675)

https://docs.automa.site/workflow/element-selector.html#custom-selector-syntax

**Comment by trasferimento** [comment]
thanks a lot !  It works

**Comment by bryan-zhu-dev** [comment]
> thanks a lot ! It works

Can you provide an example how it works?

**Comment by aliraza948** [comment]
https://books-pwakit.appspot.com/

it's not working for typing in it's search bar for shadow root
![image](https://github.com/user-attachments/assets/19cb9d6f-f836-4484-8a58-3f40f71dd1ce)

**Comment by maisun** [comment]
> thanks a lot ! It works

Hi which browser and OS is it? Would appreciate an example as I can't make it work with either Chrome or Safari on Mac OS
