### ISSUE TITLE
Automa CEB: Unable to add or update variables in custom scripts

### ISSUE THREAD

**Issue by Vader16039** [AutomaApp/automa#1625]
Getting the error "Uncaught (in promise) [object Object]" while adding or updating variables in Automa CEB custom scripts.

1. Go to Customize in the extension page.
2. Select Custom Script in Details tab.
3. Click on open editor and add the below code in the JS editor.
    (async () => {
    await $helper.storage.variables.set({
    country: 'ABC',
    name: 'XYZ',
    email: '123@example.com',
     });
    })();
4. Click on save changes and download the draft of the extension.
5. Add the extension in Chrome.

**Screenshots**

![image](https://github.com/AutomaApp/automa/assets/136983544/b084d3a3-47b2-4bdf-af88-ae30cd326257)

![image](https://github.com/AutomaApp/automa/assets/136983544/e596cd13-db2c-497f-a38b-cbdf28c243f0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: v8.0.0

**Additional context**
Kindly develope the Customize page in the Automa Docs.

**Comment by Kholid060** [comment]
Fixed

**Comment by wumingluren** [comment]
会一直重复添加，并且读取不到通过这种方式添加的存储变量。
