### ISSUE TITLE
 Automate CEB: Toggle text field visibility based on a condition

### ISSUE THREAD

**Issue by Vader16039** [AutomaApp/automa#1628]
I want to toggle the text field visibilty based upon a password input. Can someone kindly help me here.

Before typing the password and clicking unlock.
![image](https://github.com/AutomaApp/automa/assets/136983544/832017e9-7cda-4541-9aa8-44e8e46ce8c9)

After typing the password and clicking unlock.
![image](https://github.com/AutomaApp/automa/assets/136983544/263bba32-015a-4256-9fe6-ac828a6400f6)

 - OS: Windows
 - Browser: Google Chrome

**Comment by Kholid060** [comment]
You can do that like this:

First, set the `hidden` value of all Input components you want to toggle to `true` in the layout section when you edit the component.
![image](https://github.com/AutomaApp/automa/assets/22908993/5e65230e-f4c3-42c0-b7d9-e6b16d346318)

After that, in the "UNLOCK" button. Add the "click" event and paste the below code:

![image](https://github.com/AutomaApp/automa/assets/22908993/d3d98567-be7a-41bc-b829-efa8be1aa21b)

```js
const PASSWORD = 'YOUR_PASSWORD_HERE';

const PASSWORD_INPUT_COMP_ID = 'input6';
const COMP_IDS = ['input3', 'input2', 'input4'];

const inputPass = $vars.comps[PASSWORD_INPUT_COMP_ID].value.trim();

COMP_IDS.forEach((compId) => {
  $helper.setCompData(compId, { hidden: inputPass !== PASSWORD });
})
```

There are several things you need to replace in the above code:
- Replace 'YOUR_PASSWORD_HERE' with the password you want to unlock the hidden inputs
- Replace the value of the `COMP_IDS` variable (`['input3', 'input2', 'input4']`) with the ids of the components that you previously set the `hidden` input to `true`;
- Replace the value of the `PASSWORD_INPUT_COMP_ID` variable (`input6`) with the component ID of the input component for inputting the password.

**Comment by Vader16039** [comment]
Thanks @Kholid060 . This is works.
