### ISSUE TITLE
How to send out email notification of error or complete?

### ISSUE THREAD

**Issue by mxracer388** [AutomaApp/automa#1629]
**Is your feature request related to a problem? Please describe.**
The problem occurs when you need to know if the system has failed, stopped, or completed its tasks. It is not always easy to manually check daily for this.

**Describe the solution you'd like**
Is it possible to have a snippet code that can be added to settings in order to send out an email notification of status, maybe upon an event or even daily?

**Describe alternatives you've considered**
Alternatives are to build this straight into the app as a core function, or add a series of code in the settings tab to act as the function.

**Additional context**
This would enhance the automation process of the app even further, and a nice feature to add to its value.

**Comment by Kholid060** [comment]
Automa has ["Workflow events"](https://docs.automa.site/workflow/settings.html#_4-workflow-events) feature that allows you to do action after the workflow execution finishes with success or failed status. But it doesn't support sending email, so instead, you can use the "HTTP Request" method to send a request to an API that later sends email notifications to your email address.

![image](https://github.com/AutomaApp/automa/assets/22908993/0f7246f2-5484-4ace-89b9-ab7c0827a208)

**Comment by mxracer388** [comment]
Thank you That will work!!!
