### ISSUE TITLE
Failed to record.

### ISSUE THREAD

**Issue by r33452000** [AutomaApp/automa#1701]
**Describe the bug**

**To Reproduce**
1. Go to the web page
2. Click on automa extension button
3. Click record, and show learn more.
![image](https://github.com/AutomaApp/automa/assets/69714117/0e8316e0-8fa1-4a7d-be48-f9522fbf8475)

6. Unable to use the active recording, click the record button will take me to the tutorial page.

**Expected behavior**
Recording the action to workflow.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Extension Version: 1.28.27

**Additional context**

**Comment by r33452000** [comment]
從record workflow那頁跳過去可以直接使用，跳過去後，必需先Scroll 滑鼠，不然會沒有反應，之後就正常了

這個擴充真的非常的棒，解決了困擾以久的麻煩，之前重覆的工作都要另外寫小程式處理，真的省了非常多的時間，感謝開發組!!!

**Comment by GQ-zhang** [comment]
> 從record workflow那頁跳過去可以直接使用，跳過去後，必需先按任何一個連結再跳回來，或是從別的聯結跳過去，不然會沒有反應，之後就正常了
> 
> 這個擴充真的非常的棒，解決了困擾以久的麻煩，之前重覆的工作都要另外寫小程式處理，真的省了非常多的時間，感謝開發組!!!
没听懂你讲了什么，方便重新解释一下吗

**Comment by r33452000** [comment]
就是record workflow過去後，如果不是開新Tab，而是保持在原有Tab操作，就不能繼續操作，一定得頁面刷新才會動

另外編輯到一半，流程圖放大縮小會突然不能用，一定得重開

GUOQING Zhang ***@***.***> 於 2024年7月5日 週五 下午1:52寫道：
