### ISSUE TITLE
Can't Pass CloudFlare's Human Click Test

### ISSUE THREAD

**Issue by xhan** [AutomaApp/automa#1725]
I use "Click Element" to click Cloudflare's Human Click Test.
But after the click operation, it can't pass Cloudflare's detection.

**Comment by aliraza948** [comment]
use click with debug mode it'll work 
![image](https://github.com/AutomaApp/automa/assets/121416988/445fa202-0cd5-4790-9612-5372922c00ba)

**Comment by xhan** [comment]
Thanks, it did work

**Comment by blackawn** [comment]
> use click with debug mode it'll work ![image](https://private-user-images.githubusercontent.com/121416988/339959606-445fa202-0cd5-4790-9612-5372922c00ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzI3MDQsIm5iZiI6MTcyMTY3MjQwNCwicGF0aCI6Ii8xMjE0MTY5ODgvMzM5OTU5NjA2LTQ0NWZhMjAyLTBjZDUtNDc5MC05NjEyLTUzNzI5MjJjMDBiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxODIwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjgxZGM3OGJhNjg5MzFiMWJkMGZlNzMxM2U1MWI3Y2NlNjI1NWMxOGMzODc3Y2I1MWZhY2RlODJhMzkyNjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qwn7u2ADlTVQi5y9gvuQXLbUqYnHrUbQZBQwgatzJyY)

Can you give me a demo? I'm new to this extension.

**Comment by blackawn** [comment]
> Thanks, it did work谢谢，它确实奏效了

Did you succeed? Can you tell me the details of the process?

**Comment by blackawn** [comment]
> Thanks, it did work

Did you succeed? Can you tell me the details of the process?

**Comment by aliraza948** [comment]
there is no need to further detail you can apply click and type text by advance method that's by debug mode ....
if your normal activity doesn't work then you can use debug mode..
✅

**Comment by blackawn** [comment]
> there is no need to further detail you can apply click and type text by advance method that's by debug mode .... if your normal activity doesn't work then you can use debug mode.. ✅

Thank you for your reply. I would like to ask how you got the input checkbox. I didn’t get it in this process.

![image](https://github.com/user-attachments/assets/3dece2a9-b912-4c96-9483-b27b1a6d1b9d)

**Comment by scoful** [comment]
> use click with debug mode it'll work ![image](https://github.com/AutomaApp/automa/assets/121416988/445fa202-0cd5-4790-9612-5372922c00ba)

Hello, could you teach me how to obtain the element or idea of "CloudFlare's Human Click"? Thank you very much.

**Comment by aliraza948** [comment]
> > use click with debug mode it'll work ![image](https://github.com/AutomaApp/automa/assets/121416988/445fa202-0cd5-4790-9612-5372922c00ba)
> 
> Hello, could you teach me how to obtain the element or idea of "CloudFlare's Human Click"? Thank you very much.

Requirment

1. use this selector  for click on captcha               div#cf-turnstile > div >> iframe |> body >> input[type="checkbox"]
2. your browser must be firefox
3. it'll work otherwise try after turn on Debug Mode

**Comment by scoful** [comment]
> > > use click with debug mode it'll work ![image](https://github.com/AutomaApp/automa/assets/121416988/445fa202-0cd5-4790-9612-5372922c00ba)
> > 
> > 
> > Hello, could you teach me how to obtain the element or idea of "CloudFlare's Human Click"? Thank you very much.
> 
> Requirment
> 
> 1. use this selector  for click on captcha               div#cf-turnstile > div >> iframe |> body >> input[type="checkbox"]
> 2. your browser must be firefox
> 3. it'll work otherwise try after turn on Debug Mode

Hello, I tried to follow your steps, and then I noticed something strange.
- 1. I tried to turn on debug mode, and then I noticed a prompt at the workflow level debug settings saying: "Debug mode (This feature is not supported in the Firefox browser)." My Firefox version is 134.0.1
- 2. When I tried to enable debug for "click element" in Firefox, I found that this option was not available.
- 3. May I ask which version of Firefox or which version of Automa you are using?
- 4. When I directly run the code in the browser's console,like this:`document.querySelector('div#cf-turnstile > div > iframe > body input[type="checkbox"]')`, the returned result is null.
- 5. I noticed that Automa has a block called "Switch Frame." Should I use this first to switch to the cf iframe?

**Comment by aliraza948** [comment]
Yeah, you're right there is no debug mode 
But it's working for me without it.

**Comment by aliraza948** [comment]
> > > > use click with debug mode it'll work ![image](https://github.com/AutomaApp/automa/assets/121416988/445fa202-0cd5-4790-9612-5372922c00ba)
> > > 
> > > 
> > > Hello, could you teach me how to obtain the element or idea of "CloudFlare's Human Click"? Thank you very much.
> > 
> > 
> > Requirment
> > 
> > 1. use this selector  for click on captcha               div#cf-turnstile > div >> iframe |> body >> input[type="checkbox"]
> > 2. your browser must be firefox
> > 3. it'll work otherwise try after turn on Debug Mode
> 
> Hello, I tried to follow your steps, and then I noticed something strange.
> 
> * 1. I tried to turn on debug mode, and then I noticed a prompt at the workflow level debug settings saying: "Debug mode (This feature is not supported in the Firefox browser)." My Firefox version is 134.0.1
> * 2. When I tried to enable debug for "click element" in Firefox, I found that this option was not available.
> * 3. May I ask which version of Firefox or which version of Automa you are using?
> * 4. When I directly run the code in the browser's console,like this:`document.querySelector('div#cf-turnstile > div > iframe > body input[type="checkbox"]')`, the returned result is null.
> * 5. I noticed that Automa has a block called "Switch Frame." Should I use this first to switch to the cf iframe?

Yeah, you're right there is no debug mode
But it's working for me without it.

**Comment by scoful** [comment]
> > > > > use click with debug mode it'll work ![image](https://github.com/AutomaApp/automa/assets/121416988/445fa202-0cd5-4790-9612-5372922c00ba)
> > > > 
> > > > 
> > > > Hello, could you teach me how to obtain the element or idea of "CloudFlare's Human Click"? Thank you very much.
> > > 
> > > 
> > > Requirment
> > > 
> > > 1. use this selector  for click on captcha               div#cf-turnstile > div >> iframe |> body >> input[type="checkbox"]
> > > 2. your browser must be firefox
> > > 3. it'll work otherwise try after turn on Debug Mode
> > 
> > 
> > Hello, I tried to follow your steps, and then I noticed something strange.
> > 
> > * 1. I tried to turn on debug mode, and then I noticed a prompt at the workflow level debug settings saying: "Debug mode (This feature is not supported in the Firefox browser)." My Firefox version is 134.0.1
> > * 2. When I tried to enable debug for "click element" in Firefox, I found that this option was not available.
> > * 3. May I ask which version of Firefox or which version of Automa you are using?
> > * 4. When I directly run the code in the browser's console,like this:`document.querySelector('div#cf-turnstile > div > iframe > body input[type="checkbox"]')`, the returned result is null.
> > * 5. I noticed that Automa has a block called "Switch Frame." Should I use this first to switch to the cf iframe?
> 
> Yeah, you're right there is no debug mode But it's working for me without it.
> 
> 5. Browser must be Firefox then you'll able to switch shadowroot and iframe
> 
> Given screenshot was of chrome.
> 
> But chrome is not able switch shadowroot
> 
> In case of cloudflare you'll also need to use shadowroot

Thank you very much, I did it.
- I found that I had to pass the Cloudflare Challenge, not the Cloudflare Turnstile, so I adjusted the css selector and achieved the click, but it could not pass the cf detection. Can you pass the Cloudflare Challenge test?
- Cloudflare Turnstile can definitely pass the detection
