### ISSUE TITLE
[Feature request]Execute specific workflow from url

### ISSUE THREAD

**Issue by coldwinds** [AutomaApp/automa#1749]
**Is your feature request related to a problem? Please describe.**

If we can generate url for specific workflow for execution.
So we can bookmark this url, and execute the workflow from browser's bookmark bar with one click.
Or we can organize workflows into bookmark folders

**Comment by MrAkber** [comment]
Hello Coldwinds,
It already is possible.
Check this out:
https://docs.automa.site/blocks/trigger.html#trigger-through-url

**Comment by coldwinds** [comment]
> Hello Coldwinds, It already is possible. Check this out: https://docs.automa.site/blocks/trigger.html#trigger-through-url

That's great. Thanks for the guide.
