### ISSUE TITLE
What is "Delay" in the Interval Trigger Block?

### ISSUE THREAD

**Issue by amitlevy** [AutomaApp/automa#1768]
When creating a Workflow Trigger, the Interval section has two fields: Interval and Delay. Interval is straightforward, but what is the meaning of Delay in this context?
Could it be that after the interval time passes, it waits for another delay time before triggering? It seems redundant. I'm probably missing something.

-> Has been ignored in discussion for two weeks (asked by someone else), I decided to copy it here because I think this level of opaqueness is on the level of a bug - it seems that simply nobody noes what's the difference between interval and delay.

**Comment by jingbof** [comment]
The `Interval` and `Delay` fields correspond to the properties in the [`alarmInfo`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms/create#alarminfo) object for `alarms.create()`.

`delay` = `delayInMinutes`: This represents the time (in minutes) before the workflow will first fire, starting from the moment the workflow is created, and the `delay` parameter only affects the first time the workflow triggers.

For example, if you create a workflow with an interval of 10 minutes and a delay of 5 minutes, the workflow will first trigger 5 minutes after it's created. After that, it will continue to trigger every 10 minutes.
