### ISSUE TITLE
Automa.site Eror. Cannot open


### ISSUE THREAD

**Issue by Raisrahman37** [AutomaApp/automa#1852]

**Comment by QQOQ** [comment]
use https://automa.wiki

**Comment by Raisrahman37** [comment]
> use https://automa.wiki
So the automa site can no longer be done? Is now the official website wiki automa

**Comment by myesn** [comment]
cannot open https://automa.site/auth for login

**Comment by Raisrahman37** [comment]
> cannot open https://automa.site/auth for login

Yes We Are same

**Comment by myesn** [comment]
They are fixing.

https://discord.com/channels/942211415517835354/942211415962439742/1302823501052510288

![image](https://github.com/user-attachments/assets/928b8293-d07d-4786-a225-5b852fe3b663)

**Comment by bingren-yd** [comment]
https://github.com/AutomaApp/automa/issues/1855#issuecomment-2456998004 @Raisrahman37
