### ISSUE TITLE
Automa Failed to Fetch Google Sheet

### ISSUE THREAD

**Issue by tvmorganas** [AutomaApp/automa#1870]
Google sheets function didn't work tonite ,
It works before, I used it to update data to goole spreadsheets

Already Shared with "[service@automa2.iam.gserviceaccount.com](mailto:service@automa2.iam.gserviceaccount.com)"

Here the log

1. Go to 'trigger.'
2. New tab was open
3. Google sheet " Failed to Fetch"

It works in few hours ago, but suddenly it cant.

<img width="509" alt="image" src="https://github.com/user-attachments/assets/0ada48ec-6ffb-41c0-bc8e-9504b5672155" />

**Comment by mix357** [comment]
Me too.

**Comment by profirst30** [comment]
I have the same problem

**Comment by mix357** [comment]
I have seen that Chrome might not be longer support Automa. Does it relate with this incidence?

**Comment by bingren-yd** [comment]
Google sheets has been restored. It's strange.
