### ISSUE TITLE
"Active tab" not work before using `Javascript Code`

### ISSUE THREAD

**Issue by shaoxyz** [AutomaApp/automa#220]
![image](https://user-images.githubusercontent.com/26154330/147427328-bb16fd46-3466-4c95-a1c4-d6a96112c47a.png)

Can not find the reason~

![image](https://user-images.githubusercontent.com/26154330/147427404-889707ea-0ad5-4578-9562-d4f823d1d314.png)

**Comment by Kholid060** [comment]
When you're using the **Active tab** block, it means that the workflow will be executed on the website that you're currently in like the example below. And you can't directly execute the workflow in the editor.

![Animation](https://user-images.githubusercontent.com/22908993/147450234-fa3b761c-5651-4773-bf62-63ac2db01a61.gif)

**Comment by shaoxyz** [comment]
I see. Thanks!

Here is a personal requirement: watching the flow's running status in the current page.
Is it possible to implement this feature in the future?  

BTW The editor page's UI is very beautiful and comfortable ：）

> When you're using the **Active tab** block, it means that the workflow will be executed on the website that you're currently in like the example below. And you can't directly execute the workflow in the editor.
> 
> ![Animation](https://user-images.githubusercontent.com/22908993/147450234-fa3b761c-5651-4773-bf62-63ac2db01a61.gif)

**Comment by Kholid060** [comment]
> Here is a personal requirement: watching the flow's running status on the current page.
> Is it possible to implement this feature in the future?

It's possible but it'll kinda tricky to implement it. I'll try to add this feature in the future update

**Comment by aswinkumar863** [comment]
@Kholid060 Some of my workflows stopped working in this case. I'm damn sure that it worked fine a few weeks before, while I created it. Probably it's broken in any past update.

**Comment by Kholid060** [comment]
@aswinkumar863 Can you screenshot the logs of your workflows?

**Comment by aswinkumar863** [comment]
**Workflow**

![image](https://user-images.githubusercontent.com/32381261/147527115-2b67fb0f-87fd-4f96-b16b-6a748cb4e082.png)

**Log**

![image](https://user-images.githubusercontent.com/32381261/147526944-b9e2b31c-1b85-42eb-b332-3fe81789746a.png)

**Comment by aswinkumar863** [comment]
@Kholid060 I found this error occurs whenever the workflow fails

![image](https://user-images.githubusercontent.com/32381261/147535617-0456e877-0f48-4313-92be-f075e6bdb6e7.png)

**Comment by Kholid060** [comment]
Are you using the latest version of Automa?

**Comment by aswinkumar863** [comment]
Yes, the latest version. 

But after I reinstalled the extension everything working fine now.
