### ISSUE TITLE
Help with Automa

### ISSUE THREAD

**Issue by br0gio** [AutomaApp/automa#241]
I don't really know how I would do this, so I'm trying to click the button on this webpage https://top.gg/servers/926589348466544680/vote and I've made that work once it votes it sends a webhook message in my discord server I don't know how I would send a different webhook when the button is grayed out. Could anyone help me with this?
![image](https://user-images.githubusercontent.com/93214699/147879746-cbe0b507-3759-4f23-9ca3-72f53445ba66.png)
That is what I have currently but the element exist doesn't work so it will send that it has pressed the button succesfully when it hasn't.
The new tabs at the end are just for different servers that I vote for.

**Comment by whwh656** [comment]
try it add delay

**Comment by br0gio** [comment]
> 

Why would a delay help with anything?
