### ISSUE TITLE
get element （.el-form-item__content > .el-input > .el-input__inner）by Automa，but it cannot work in Forms. Pls help thks..

### ISSUE THREAD

**Issue by Kathrie** [AutomaApp/automa#272]
I get element （.el-form-item__content > .el-input > .el-input__inner）by Automa，but it cannot work in Forms.  
Does Automa not support this type? How could i do next? Thanks
<img width="1037" alt="1" src="https://user-images.githubusercontent.com/98003000/150060161-e05019da-d90f-47d8-b61f-cf0903e6a20b.png">
<img width="1229" alt="2" src="https://user-images.githubusercontent.com/98003000/150060187-50850faa-cfd1-4b7c-b4c4-674158f71303.png">
<img width="1332" alt="3" src="https://user-images.githubusercontent.com/98003000/150060205-1af81bff-0701-4139-91a2-0021e6695989.png">

Looking forward to your reply,thanks.

**Comment by Kholid060** [comment]
> I get element （.el-form-item__content > .el-input > .el-input__inner）by Automa，but it cannot work in Forms.
Does Automa not support this type? How could i do next?

It supports the input element. And try opening the log of the workflow to see if there's an error or not after executing it.

**Comment by Kathrie** [comment]
> the input element. A
There is an error.Can't find an element with ".el-form-item__content > .el-input > .el-input__inner" selector.
But I get element （.el-form-item__content > .el-input > .el-input__inner）by Automa in the following pic.Pls help,thks.

![image](https://user-images.githubusercontent.com/98003000/150487324-77a6e970-0186-4479-aadb-610ab8260529.png)
![image](https://user-images.githubusercontent.com/98003000/150486835-86516b57-3a84-46b6-b489-94c59eaca1b8.png)

**Comment by Kholid060** [comment]
Based on the error, the forms block might get executed when the input element is doesn't exist in the DOM. Try adding the [element exists](https://docs.automa.site/blocks/element-exists.html) before the forms block like the image below.

![image](https://user-images.githubusercontent.com/22908993/150516408-e02f509e-33bc-4f7b-a560-51b8b092a98d.png)
