### ISSUE TITLE
How to upload a column of data obtained by executing a workflow

### ISSUE THREAD

**Issue by pk0933456** [AutomaApp/automa#279]
Thanks for this great Automa
How to upload a column of data obtained by executing a workflow to google sheets
thank
<img width="1049" alt="截圖 2022-01-23 下午11 12 55" src="https://user-images.githubusercontent.com/98203422/150685379-0c9a7cbd-60df-4b80-b96c-9a0b95eeeebc.png">
s

**Comment by Kholid060** [comment]
It's currently not possible to do that. For now, you can add the google sheets block inside the workflow that the Execute Workflow block executes.

**Comment by jddcef** [comment]
Not possible to pass data between workflows?
