### ISSUE TITLE
Reference data loop change

### ISSUE THREAD

**Issue by reysonk** [AutomaApp/automa#291]
Thanks for your work!

I have a low problem and I can't figure out how to do it.
To get the array, I use Google sheets:

```
[
  {
    "msisdn": "123",
    "pass": "123"
  },
  {
    "msisdn": "321",
    "pass": "321"
  }
]
```

In the "forms" block, I call the table value by the Reference key "data", the string "0" and by the array key "msisdn"
  
`  {{ googleSheets@data.0.msisdn }}`
  
Need help how can I loop this call and on every loop and change the line "0" to "X"
  
```
The first cycle is used             	{{ googleSheets@data.0.msisdn }}
The second cycle is used	        {{ googleSheets@data.1.msisdn }}
The third cycle is used	         	{{ googleSheets@data.2.msisdn }}
......etc......
```

**Comment by reysonk** [comment]
Assumed template, described in a global date, but I don’t know how to do it correctly, and how to call a correctly declared global value

very primitive idea looks like this:
```
X = -1

[{ ​"msisdn": "{{ googleSheets@data.X+1.msisdn }}" }]```

**Comment by Kholid060** [comment]
> Thanks for your work!
> 
> I have a low problem and I can't figure out how to do it. To get the array, I use Google sheets:
> 
> ```
> [
>   {
>     "msisdn": "123",
>     "pass": "123"
>   },
>   {
>     "msisdn": "321",
>     "pass": "321"
>   }
> ]
> ```
> 
> In the "forms" block, I call the table value by the Reference key "data", the string "0" and by the array key "msisdn"
> 
> ` {{ googleSheets@data.0.msisdn }}`
> 
> Need help how can I loop this call and on every loop and change the line "0" to "X"
> 
> ```
> The first cycle is used             	{{ googleSheets@data.0.msisdn }}
> The second cycle is used	        {{ googleSheets@data.1.msisdn }}
> The third cycle is used	         	{{ googleSheets@data.2.msisdn }}
> ......etc......
> ```

You can use the [Loop data block](https://docs.automa.site/blocks/loop-data.html) to loop through the google sheets data. For example

![image](https://user-images.githubusercontent.com/22908993/151547529-7fa4e2e6-1aa8-4c6c-bc22-c80159a44234.png)

In the loop data block, input the `Reference key` with the reference key of the google sheets. And in the forms block, you can write `{{ loopData@loopId.msisdn }}`, replace `loopId` with the loop Id of the loop data block `{{ loopData@qUhZTL.msisdn }}`.

**Comment by reysonk** [comment]
Thank you so much!!!! Need its instruction adds to "dosc"
https://docs.automa.site/blocks/loop-data.html#loop-id :)
I can help with translation into Russian :)

I sent you "ko-fi" :)

пт, 28 янв. 2022 г. в 19:39, Ahmad Kholid ***@***.***>:

**Comment by MohamedCartelo** [comment]
Hi, i have a little issue, where i can put the {{ loopData@loopId.msisdn }} in the block form? text field? select? or there is a specific configuration, because i had try all of theme and he paste always {{ loopData@loopId.msisdn }} i use also a google sheet for the data inuput
<img width="1280" alt="Capture d’écran 2022-02-25 à 11 57 31 PM" src="https://user-images.githubusercontent.com/88911091/155814118-c558fa65-3c8d-4529-b8f9-2c4261bcf0a3.png">
:

**Comment by Adrear** [comment]
@Kholid060 What am I doing wrong?

**Flow**
HTTP request -> Loop data -> Condition (check link is exist) -> New tab -> Loop breakpoint

**Loop data**
Loop ID - comment
Loop through - Variable
Variable name - comments

**Logs** 
1. {{ loopData@comment }} - { _id: 0, link: null or correct url }  ✅
2.  {{ loopData@comment.link }} -  {{ loopData@comment.link }} ❌
And then I get error - "{{loopData@comment.link}}" is wrong URL

**Comment by Kholid060** [comment]
> @Kholid060 What am I doing wrong?
> 
> **Flow** HTTP request -> Loop data -> Condition (check link is exist) -> New tab -> Loop breakpoint
> 
> **Loop data** Loop ID - comment Loop through - Variable Variable name - comments
> 
> **Logs**
> 
> 1. {{ loopData@comment }} - { _id: 0, link: null or correct url }  ✅
> 2. {{ [loopData@comment.link](mailto:loopData@comment.link) }} -  {{ [loopData@comment.link](mailto:loopData@comment.link) }} ❌
>    And then I get error - "{{[loopData@comment.link](mailto:loopData@comment.link)}}" is wrong URL

Can you screenshot the log data of the error block in the workflow logs?

**Comment by Adrear** [comment]
> > @Kholid060 What am I doing wrong?
> > **Flow** HTTP request -> Loop data -> Condition (check link is exist) -> New tab -> Loop breakpoint
> > **Loop data** Loop ID - comment Loop through - Variable Variable name - comments
> > **Logs**
> > 
> > 1. {{ loopData@comment }} - { _id: 0, link: null or correct url }  ✅
> > 2. {{ [loopData@comment.link](mailto:loopData@comment.link) }} -  {{ [loopData@comment.link](mailto:loopData@comment.link) }} ❌
> >    And then I get error - "{{[loopData@comment.link](mailto:loopData@comment.link)}}" is wrong URL
> 
> Can you screenshot the log data of the error block in the workflow logs?
<img width="922" alt="Screenshot 2023-09-25 at 09 10 37" src="https://github.com/AutomaApp/automa/assets/22615625/df7bd930-e4b3-4c38-931a-219d64151dce">
<img width="912" alt="Screenshot 2023-09-25 at 09 10 10" src="https://github.com/AutomaApp/automa/assets/22615625/7d21e32f-0083-46ce-ba8a-b56609ed41e5">

**Comment by Kholid060** [comment]
You can use the 'Code' option in the condition block to check if the value is `null`
![image](https://github.com/AutomaApp/automa/assets/22908993/53907b4b-dc06-4163-a161-51a3a1f9aaf2)
