### ISSUE TITLE
When using "webhook", how can I transfer all data of "datacolumns" to "content body"? 

### ISSUE THREAD

**Issue by checkhero** [AutomaApp/automa#320]
Thank you for your work! I have a question about 'webhook'
When using "webhook", how can I transfer all data of "datacolumns" to "content body"? Only the first row of data is transferred by "{{datacolumns}}"

**Comment by checkhero** [comment]
Thank you very much for your answer, but I mean to directly obtain the entire JSON array of datacolumns. The workflow first dynamically crawls the web page data into datacolumns. I don't know how many rows of data there are in datacolumns

**Comment by Kholid060** [comment]
> When using "webhook", how can I transfer all data of "datacolumns" to "content body"?

To transfer all data of the data columns to content body, write `{{ dataColumns }}`
![image](https://user-images.githubusercontent.com/22908993/152879045-128edf72-c8dc-4824-8f3f-22416380e9aa.png)

> Only the first row of data is transferred by "{{datacolumns}}"

Try to check how many rows the data columns have

>  I don't know how many rows of data there are in data columns

You can check how many rows the data columns have by opening the workflow log
![image](https://user-images.githubusercontent.com/22908993/152878691-2c1e1fd2-524b-4a27-97e9-b578d78842c2.png)

**Comment by checkhero** [comment]
When using "webhook", how can I transfer all data of "datacolumns" to "content body"? Only the first row of data is transferred by "{{datacolumns}}"

Thank you very much for your answer. The website data I want to crawl is dynamic and updated all the time, so I made a timing trigger. The trigger dynamically obtains all data through "loop data" and places it in “datacolumns”. Finally, all data of datacolumns is automatically submitted to my server through webhook.

I used {{datacolumns}} in the content body of webhook, But the server only got the first row of data. The workflow log shows that there are multiple rows of data in datacolumns.
![image](https://user-images.githubusercontent.com/99178273/152976915-e7aaf5f3-e980-42b0-9282-e868d54924c6.png)



I copy the data directly from the workflow log to the contentbody, but the server can receive all the data. I don't know what went wrong?
![image](https://user-images.githubusercontent.com/99178273/152973447-bbad7c0f-08c4-48e8-bab0-15f706e03755.png)

my workflow：
![image](https://user-images.githubusercontent.com/99178273/152975561-fad13417-0fc5-4b05-b2bc-81e4225ab915.png)

**Comment by Kholid060** [comment]
> Thank you very much for your answer. The website data I want to crawl is dynamic and updated all the time, so I made a timing trigger. The trigger dynamically obtains all data through "loop data" and places it in “datacolumns”. Finally, all data of datacolumns is automatically submitted to my server through webhook.
> 
> I used {{datacolumns}} in the content body of webhook, But the server only got the first row of data. The workflow log shows that there are multiple rows of data in datacolumns. ![image](https://user-images.githubusercontent.com/99178273/152976915-e7aaf5f3-e980-42b0-9282-e868d54924c6.png)
> 
> I copy the data directly from the workflow log to the contentbody, but the server can receive all the data. I don't know what went wrong? ![image](https://user-images.githubusercontent.com/99178273/152973447-bbad7c0f-08c4-48e8-bab0-15f706e03755.png)
> 
> my workflow： ![image](https://user-images.githubusercontent.com/99178273/152975561-fad13417-0fc5-4b05-b2bc-81e4225ab915.png)

That's kinda weird, I'll look into this if there's a bug in the app
