### ISSUE TITLE
this is not a bug，wang to konw how to scroll element ,thanks 

### ISSUE THREAD

**Issue by techflag** [AutomaApp/automa#328]
this is not a bug，wang to konw how to scroll element ,thanks 

how to scroll the people list，and click it，one by one

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/939362/153623246-d2ac673d-d903-4cb2-930b-8edff0372a33.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v0.17]

**Comment by whwh656** [comment]
v1.12.0
scroll blocks

**Comment by ktmswzw** [comment]
## Bug for Scroll blocks

There is scroll Y to bottom,  then request server for loading more items insert into the list by dynamic.

How setting the script. @whwh656 

thanks.
