### ISSUE TITLE
Automa dont start on exact time

### ISSUE THREAD

**Issue by protocold** [AutomaApp/automa#337]
**Describe the bug**
I have tried to schedule a workflow to start at 8:00am but it only start at like 8:00:33am, it is quite random. 
Is this an expected behavior? is there a way to make it start sharp at the 00 second? 

**To Reproduce**

**Expected behavior**
workflow should start sharp at the time. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 and MacOS 10.15.7
 - Browser: Chrome
 - Extension Version: 0.17.4

**Additional context**

**Comment by Kholid060** [comment]
It follows the time when you click the save button, but I'll fix this on the next update so it starts exactly at the time you inputted.

**Comment by protocold** [comment]
But for some reason on linux it seems to script quite punctually... bug?

**Comment by Kholid060** [comment]
If you're using the `on a specific date` option, I don't think it's a bug because I don't set it to execute at the exact 00 seconds.
https://github.com/Kholid060/automa/blob/697f5d25153884dcb99a9ba780679f301674ac56/src/utils/workflow-trigger.js#L90

**Comment by Kholid060** [comment]
I think it might be a bug if you're using the "on a specific day" option

**Comment by Destroy666x** [comment]
This is still a very serious issue @Kholid060 . I tested and my workflow executed at around 12;00:59 when I expected it at 12:00:00.

Also:
> If you're using the on a specific date option, I don't think it's a bug because I don't set it to execute at the exact 00 seconds.

Why not? I think there should be a seconds field for both in the 1st place, but when it doesn't exist I would always assume it's 0, not a random second.

**Comment by Kholid060** [comment]
> This is still a very serious issue @Kholid060 . I tested and my workflow executed at around 12;00:59 when I expected it at 12:00:00.
> 
> Also:
> 
> > If you're using the on a specific date option, I don't think it's a bug because I don't set it to execute at the exact 00 seconds.
> 
> Why not? I think there should be a seconds field for both in the 1st place, but when it doesn't exist I would always assume it's 0, not a random second. 2x seconds field would be awesome though.

Sure, I'll add seconds input in the next update

**Comment by Destroy666x** [comment]
Thanks!
