### ISSUE TITLE
Having the same element in a same page leads to not write successfully. PLS help,thanks.

### ISSUE THREAD

**Issue by Kathrie** [AutomaApp/automa#340]
**Describe the bug**
Having the same element in a same page leads to not be written successfully. PLS help,thanks.
Step 8 does not take effect.

**Screenshots**
The same element(.is-focus > .el-input__inner) in a same page :
![image](https://user-images.githubusercontent.com/98003000/153810796-f6527c64-eb32-4981-a9fa-54121a806665.png)
![image](https://user-images.githubusercontent.com/98003000/153810795-ed4c8282-8c1b-48a2-b05d-56acd05cd625.png)

Step 8 was not performed，Logs without step 8.
![image](https://user-images.githubusercontent.com/98003000/153810966-d278c2e4-74a1-4fbf-9840-2b5e89131138.png)
![image](https://user-images.githubusercontent.com/98003000/153811067-5ed1258b-dea3-47c4-9e02-989464411849.png)

**Comment by Kholid060** [comment]
Try this https://github.com/Kholid060/automa/issues/341#issuecomment-1038911044

**Comment by Kathrie** [comment]
It doesnot work after i increase the "Try for" and the "Timeout" value.
The same elements(different place) in a same page ,does automa not know which one should be assigned to?
The steps (Forms) doesnot work.
![image](https://user-images.githubusercontent.com/98003000/154004293-051e048d-9d6c-4a3a-ad17-8668993852c0.png)

**Comment by Kholid060** [comment]
Try `.el-input__inner` as the element selector, and if it still doesn't work can you right-click at the input, click the inspect option, take a screenshot and send it here, so I can help you to get the selector of the input.

**Comment by Kathrie** [comment]
Thank you very much for your patience.
I tried .el-input__inner as the element selector, also tried input.el-input__inner as the element selector,but they still don't work.
The screenshot as follows: 
![image](https://user-images.githubusercontent.com/98003000/154218105-32a21831-e521-43bb-b004-fb7cd33dfac3.png)
![image](https://user-images.githubusercontent.com/98003000/154218510-d9376734-9a8b-4504-82c6-e42e15ac6dab.png)

**Comment by Kholid060** [comment]
Try one of these selectors:
- `input[placeholder="textHere"]`
- `label[for="appId"] + .el-form-item__content input.el-input__inner`

Replace the `textHere` with the highlighted text in the image below.

![154218105-32a21831-e521-43bb-b004-fb7cd33dfac3](https://user-images.githubusercontent.com/22908993/154265202-78243046-0953-4e88-a868-cc1055082d72.png)

It is hard to generate a unique selector for the input element because it has a common class name and also doesn't have an id attribute to identify it.

**Comment by Kathrie** [comment]
The input can be realized through the method you provide. Thank you very much.
But other problem has arisen. In fact, after selecting “会员体系系统”, we need to click "Member system system" to bring up the following menu items, the current way does not show the "会员体系系统" dropdown option, so we can not click, we can not select the menu.

I made a video to understand it better.
The effect of need：
https://user-images.githubusercontent.com/98003000/155092448-151727fb-872d-4207-b39f-4d3fc1bcc300.mp4
![image](https://user-images.githubusercontent.com/98003000/155093021-7ba5cb64-5634-41da-8f06-e05a4e9293a4.png)

The actual effect：
https://user-images.githubusercontent.com/98003000/155092406-a99cef43-cb23-4c1f-8a54-44f52d1c99d1.mp4
![image](https://user-images.githubusercontent.com/98003000/155093169-91e85012-ef12-42a4-be93-03d3cb55f9e7.png)

I also use “click”  “会员体系系统”，but it doesn‘t work with no this element.

**Comment by Kholid060** [comment]
First, try using the [record workflow](https://docs.automa.site/guide/creating-workflow.html#recording-a-workflow) feature to get the selector of the element and try to execute the workflow to see whether it's working or not. If it doesn't work, can you send me the screenshot of the dev tools (Right-click the element -> click `Inspect`) of the page, because I can't do anything if I don't know the structure of the page.

**Comment by Kathrie** [comment]
I don't have the record workflow button the screenshot as follows:
![image](https://user-images.githubusercontent.com/98003000/155698993-64a9ca61-8f70-4dd7-84e0-339874486b70.png)

**Comment by Kholid060** [comment]
I guess you haven't updated the extension, are you installing Automa from the [Chrome Web Store](https://chrome.google.com/webstore/detail/automa/infppggnoaenmfagbfknfkancpbljcca)? 

If you're installing Automa from the webstore, you can update the extension by opening `chrome://extensions/` and then click the update button.

**Comment by jddcef** [comment]
Dormant, close?
