### ISSUE TITLE
Is a multithread or multprocess function possible?

### ISSUE THREAD

**Issue by ligeng0197** [AutomaApp/automa#367]
**Is your feature request related to a problem? Please describe.**
Wanna use multithread to speed up snapping up.

**Describe the solution you'd like**
design a block with choices of how many threads we would like to use and a pool max value. I think it should be much like loop block.

**Additional context**
It may be an attractive option for a lot of people with demand of  snapping something up.
Thanks.

**Comment by Kholid060** [comment]
Can you explain what you mean about multithread in this context? Do you mean to set how many threads of the CPU or something else?

**Comment by 1173710214** [comment]
yes, the multi thread of cpu. I am not an expert in js, if its impossible then sorry, but i  would like to assume there is a multi thread option to parallel finish some web js events, like buying several goods at the same page and the same time. The reason why i wanna use multithread is that i think it will send as more as possible the http requests to the server at the same time which improves the possibility of snapping tickets up with other competitors.
Thanks for reply, hope i make myself clear:)

**Comment by Kholid060** [comment]
It's not possible to set how many CPU threads the JS should use. I get what you mean, but I don't think Automa is capable to do that kinda task in the current state.

**Comment by Kholid060** [comment]
> Chrome Extension can be run in services_worker, Maybe this is also a kind of multithread
> 
> https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/

Thanks for the reference, but it will take a long time to migrate the extension from manifest v2 to manifest v3. Because the manifest v3 will be broke some Automa functionality.
