### ISSUE TITLE
Trigger Block ：webhook Trigger

### ISSUE THREAD

**Issue by wisinfun** [AutomaApp/automa#379]
**Describe the solution you'd like**
Add a trigger mode：A public webhook URL can be generated to trigger the workflow when data is received

**Comment by Kholid060** [comment]
I think this feature will require too much work because the extension needs to listen to the server in real time, so it can know when the webhook is sent.

**Comment by keremcankabadayi** [comment]
Thats what im looking for

**Comment by edwyn-amador** [comment]
I need this feature as well
