### ISSUE TITLE
Allow logs to be send to third party provider

### ISSUE THREAD

**Issue by ZlydeTJ** [AutomaApp/automa#403]
**Is your feature request related to a problem? Please describe.**
I would like to send the current log of automa to a third party. We use DataDog as an integration, which allows us easily to send logs from the client to a backend which will collect these logs. 

Additionally we could also send the console.logs from #385 and/or the logging of internal stuff from #347.

**Describe the solution you'd like**
I'm thinking about something simple. Just one JavaScript file we can set per Automa workflow where I can init the logging and expose a log function (with a defined interface). The init gets executed ONCE per new Tab or active Tab. This would be very flexible and allow a wide range of third party plugins.

**Describe alternatives you've considered**
You can also build a full blown integration (this also would be easy), but this would have to be done for every LogProvider there is (and can be a lot of trouble). 

**Additional context**
As an example how this might work, check these [DataDog Docs about Browser Logging](https://docs.datadoghq.com/logs/log_collection/javascript/).

**Comment by Kholid060** [comment]
> I'm thinking about something simple. Just one JavaScript file we can set per Automa workflow where I can init the logging and expose a log function (with a defined interface). The init gets executed ONCE per new Tab or active Tab. This would be very flexible and allow a wide range of third party plugins.

Can you elaborate more about "expose a log function (with a defined interface)"? And because it gets executed once per new tab, I think I will be adding this as an option in the [javascript code block](https://docs.automa.site/blocks/javascript-code.html).

**Comment by ZlydeTJ** [comment]
It would be nice to have a something like this: 

```javascript
let _logger;
(function initLogging() {
  // user inits their logging here
  _logger = new Logger({settings: {key: '<key>'}});
})();

export function automaLog(level, message, ...additionalContext) {
  // user implements their logging logging here
  // but it could look something like this:
  _logger?.log(level, message, additionalContext);
}

```
would be nice to access this via `window.automaLog`. This allows the user to set up their logging once and then expose this function to the document. 

This would work if you automatically "add" the exported `function` to the `window` Object. (This could work with other utilities too).

This would be the "defined interface", between user code and extension code.

Another thing I just ran into is that some sites [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) forbid you from making requests to unknown domains (which is a good security feature!). 

However this hampers the effort to log: It would be nice sending these request via `background.js` of the extension. 

If this is possible it would be nice to execute `automaLog` in this context. E.g. when calling it `window.automaLog("info", "Hello World", {"test": 1})` it would internally call the plugin and the pluging would execute the function call.

I hope this makes sense, however if you wish I can expand on this.
