### ISSUE TITLE
能不能添加Windows系统通知甚至更多展示获取内容的通知方式

### ISSUE THREAD

**Issue by Git0503** [AutomaApp/automa#414]
很多时候并不需要将获取结果导出，而只需要看一眼，如果能在插件或系统通知显示甚至其他更方便的显示方式就足够了

**Comment by Kholid060** [comment]
Sorry if I get it wrong, so you want to display the result using the notification?

**Comment by whwh656** [comment]
webhook就可以啊，用一个钉钉机器人或者企业微信机器人发送通知就行

**Comment by Git0503** [comment]
那能不能调用Windows通知呢（就是下面这种），还有就是现在似乎没有定时触发功能？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kholid060/automa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kholid060/automa] 能不能添加Windows系统通知甚至更多展示获取内容的通知方式 (Issue #414)





 
webhook就可以啊，用一个钉钉机器人或者企业微信机器人发送通知就行

**Comment by whwh656** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/20383505/160280490-c09b8d72-2302-496e-8787-c3e469f1a53f.png">
定时功能说的是这个吗？

**Comment by Git0503** [comment]
是的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kholid060/automa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 晚上8:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kholid060/automa] 能不能添加Windows系统通知甚至更多展示获取内容的通知方式 (Issue #414)





 

 定时功能说的是这个吗？

**Comment by swuecho** [comment]
> 很多时候并不需要将获取结果导出，而只需要看一眼，如果能在插件或系统通知显示甚至其他更方便的显示方式就足够了

可以拿到结果之后，发一个 http request 到通知系统

**Comment by Git0503** [comment]
怎么设置URL和headers可以发到Windows的系统通知里？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kholid060/automa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kholid060/automa] 能不能添加Windows系统通知甚至更多展示获取内容的通知方式 (Issue #414)





  
很多时候并不需要将获取结果导出，而只需要看一眼，如果能在插件或系统通知显示甚至其他更方便的显示方式就足够了
  
可以拿到结果之后，发一个 http request 到通知系统

**Comment by whwh656** [comment]
升级到v1.12.0
然后设置权限就行，可以了就关闭吧
https://github.com/AutomaApp/automa/issues/535
