### ISSUE TITLE
How To Click an unfixed button

### ISSUE THREAD

**Issue by luoyang871111** [AutomaApp/automa#424]
![image](https://user-images.githubusercontent.com/52514896/161185314-4c63f8ad-58c8-49d7-b962-81cd9ce51b69.png)

How to click (Capscreen_Pushmsg单图‘s "运行") after position exchange

**Comment by Kholid060** [comment]
Can you take a screenshot of the dev tools (right-click at the element and click inspect)

**Comment by luoyang871111** [comment]
![image](https://user-images.githubusercontent.com/52514896/161362827-34ab8d91-503a-4040-b261-9132583943a7.png)
https://hamibot.com/dashboard/scripts/console

**Comment by Kholid060** [comment]
Try use this xpath
`.//td[text()="Capscreen_Pushmsg单图"]/following-sibling::td[3]/div/div/*/button`

**Comment by luoyang871111** [comment]
tks

**Comment by luoyang871111** [comment]
> Try use this xpath `.//td[text()="Capscreen_Pushmsg单图"]/following-sibling::td[3]/div/div/*/button
error
