### ISSUE TITLE
一些建议suggestion

### ISSUE THREAD

**Issue by guodaxia9527** [AutomaApp/automa#449]
===automa的修改建议suggestion===
1、新建标签页，允许自定义超时
【A new TAB, allowing custom timeout】
2、允许鼠标框选模块，移动画布改为右键单击空白区域
【Allows the Mouse Box to select  modules and move the canvas change to right-click on a blank area】
3、添加对元素的截图功能，比如只截取一个div标签的图片
【Add a screenshot of web page elements，For example, take a picture of only one div or li Tag】

**Comment by whwh656** [comment]
1 :done
3 :done
