### ISSUE TITLE
unable to activate a html file from offline

### ISSUE THREAD

**Issue by EJNam** [AutomaApp/automa#453]
**Describe the bug**
I saved some html files offline, and I open them in the Edge browser, but I'm unable to activate the tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/36287495/164091008-e1730267-959a-4864-bf03-2c10585383b9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [Version 98.0.1108.55 (Official build) (64-bit)]
 - Extension Version: [ 1.7.2]

**Comment by Kholid060** [comment]
The active tab block only supports a tab where the URL starts with `http://` or `https://`
