### ISSUE TITLE
automa submit react form no effect

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#455]
targeturl:
https://vika.cn/share/shr22BE3dU1vBBQpV0F8p/fomeET14azRfuy4nt8
fill the laber1: text required   label2:number required
result:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/20383505/164254898-19ba21a5-9dbe-436d-a67d-476c3828744f.png">
[form23.txt](https://github.com/Kholid060/automa/files/8522440/form23.txt)

**Comment by whwh656** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/20383505/170382958-0393a1ac-cce2-47c7-8db6-af3fc5147777.png">
automa:v1.11.0
I test it it, it doesn't work

**Comment by whwh656** [comment]
> Can you send the URL where you test it?

https://vika.cn/share/shr22BE3dU1vBBQpV0F8p

**Comment by whwh656** [comment]
have the  bug fixed it?

**Comment by Kholid060** [comment]
Not yet, but I'll be published the fix in the next update

**Comment by whwh656** [comment]
thanks
