### ISSUE TITLE
Can't select the line

### ISSUE THREAD

**Issue by haikbvn** [AutomaApp/automa#456]
**Describe the bug**

Hi,

Thanks for releasing version 1.8.0

I encountered a small error, that was not able to select the line.

**Screenshots**
https://user-images.githubusercontent.com/1848623/164274651-869688f4-458c-4796-bfc9-759214e8f552.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Google Chrome
 - Extension Version: v1.8.0

Thank you!

**Comment by Kholid060** [comment]
Can you take a screenshot of the console tab of the dev tools (`ctrl+shift+i`) to see if there are any errors. 
Because it works fine when I tested it on windows.

**Comment by haikbvn** [comment]
Sorry, I've tried deleting block and re-creating it, but it doesn't have the same problem.

I'll report it here when I encounter this situation.

Thanks!
