### ISSUE TITLE
Can't edit workflows

### ISSUE THREAD

**Issue by csilverman** [AutomaApp/automa#461]
How do I edit existing workflows? There's no clear way to edit a workflow after I've created one; in this case, by recording a series of browser interactions.

**Comment by Kholid060** [comment]
You can edit a workflow by clicking the Automa icon and clicking the workflow that you want to edit

![image](https://user-images.githubusercontent.com/22908993/165241470-f8ca0f6e-63ce-44d4-ab20-7e72fec0b03b.png)

This will open the workflow editor where you can add, delete, or edit the blocks

![image](https://user-images.githubusercontent.com/22908993/165241701-d43dff17-30aa-4bae-914c-5a89e491800d.png)

**Comment by csilverman** [comment]
That's what I was doing, but it's not working. I tried Automa in an incognito window, just to see if some other plugin was interfering with it, but I got the same result.

**Comment by csilverman** [comment]
Here's what I'm seeing—not sure how helpful it is. (I checked the console just in case there were errors, and I didn't see anything.)

Very much appreciate how responsive you are, by the way. This is an amazing tool, so I'd love to be able to use it—just a little difficult when I can't edit the workflows.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/5296044/166119396-3202604a-94c8-4f8e-91ee-40244344f2d6.png">

**Comment by mig8447** [comment]
This happened to me today and it turned out that the workflow doesn't open when the Automa Button is hidden in the Extensions menu

**Comment by happyTonakai** [comment]
> This happened to me today and it turned out that the workflow doesn't open when the Automa Button is hidden in the Extensions menu, once I pinned the extension it worked

Also happened to me. Thank you for the solution but it is so strange...
