### ISSUE TITLE
Cannot find element in iframe

### ISSUE THREAD

**Issue by EQleechng** [AutomaApp/automa#463]
How to locate the elements in iframe in automa and select the copy selector method? An error will be displayed in the log and the elements cannot be obtained. How can I solve it?

In addition, the delay and the judgment of the existence of the element have been added, but the required element cannot be obtained.

**Comment by Kholid060** [comment]
If the element is inside an iframe element, you need to switch the frame into the iframe element using the [switch frame block](https://docs.automa.site/blocks/switch-to.html#switch-frame-block).

See https://automa.site/workflow/43KwyiOH4OaIpRFJ8A3AH for an example
