### ISSUE TITLE
How to delete all rows in the Table?

### ISSUE THREAD

**Issue by WangJincheng888** [AutomaApp/automa#476]
The "Delete Data Block"  only supports deleting column, but I want to delete all rows except the headers. I don't know how to do it. Thanks.

**Comment by Kholid060** [comment]
If you select the `[all columns]`, it will automatically delete all the rows of the table

![image](https://user-images.githubusercontent.com/22908993/166615028-11a0aedc-8342-4d7c-80d2-5f3cfea7ef45.png)

**Comment by WangJincheng888** [comment]
Thanks for applying
But I don't want to delete the table headers. I just want to delete the value of each row.

**Comment by WangJincheng888** [comment]
> Thanks for applying But I don't want to delete the table headers. I just want to delete the value of each row.

For example, I created a table like this ,
![image](https://user-images.githubusercontent.com/41196830/166699929-b93c5cab-f65e-4db1-9e5f-47b47c083a82.png)
Then in a "Loop Data Block", I insert data into the tabel in **the first loop**.
![image](https://user-images.githubusercontent.com/41196830/166699173-7ae760cd-671c-41d0-b387-ca586d56e6a9.png)
And in **the second loop**, I wanted to update the table values. So I tried "Delete Data Block", but it deleted my all headers and turned them into "coloums" .
![image](https://user-images.githubusercontent.com/41196830/166700906-196cbcd1-ae71-4396-8f3b-145e76a2f331.png)
My headers (`car`, `price`, `url`) were deleted as well!
