### ISSUE TITLE
About Nested Loop

### ISSUE THREAD

**Issue by Miruuacle** [AutomaApp/automa#484]
Hi, I meet a problem about Nested Loop,  I want Automa to generate 9 links, for example, I have 3 keywords and want to search them on certain website, then for each keywords, I want to browse 3 pages results, so I mean, its total 9 links, if we use click element to turn pages, its ok, but I want Automa to generate these links by loopData block, I have tried some combination of modules, it doesnt work and just generate 3 links. Could you optimize this function or tell me how to use Automa to achieve nested loop?

**Comment by Kholid060** [comment]
After looping the keywords, you can loop through the elements first to get the link and insert it into the table. After that, you can loop the table to get the link. 

You can import the workflow below as the demo, but you need to change the extension from `txt` to `json` first.

[Loop Behance.txt](https://github.com/Kholid060/automa/files/8658808/Loop.Behance.txt)

**Comment by Miruuacle** [comment]
Thank you, I have read your workflow, you got 3 image link for each keyword, in fact, I want to get 3 pages, for example:
https://www.alibaba.com/trade/search?IndexArea=product_en&SearchText=power_bank&page=1
https://www.alibaba.com/trade/search?IndexArea=product_en&SearchText=power_bank&page=2
https://www.alibaba.com/trade/search?IndexArea=product_en&SearchText=power_bank&page=3

Total 3 keywords, so its 9 links

**Comment by Adongggg** [comment]
Is there a bug in saving asset blocks?

**Comment by Kholid060** [comment]
> No, just want to achieve Nested Loop, 2 variable (keyword and page number ), for example, generate: https://xxx.com?SearchText=power_bank&page=1 https://xxx.com?SearchText=power_bank&page=2 https://xxx.com?SearchText=power_bank&page=3 https://xxx.com?SearchText=table_fan&page=1 https://xxx.com?SearchText=table_fan&page=2 https://xxx.com?SearchText=table_fan&page=3 https://xxx.com?SearchText=car_radio&page=1 https://xxx.com?SearchText=car_radio&page=2 https://xxx.com?SearchText=car_radio&page=3
> 
> now I don't know how to use this blocks to generate these 9 links directly.

You can loop the keyword first, and inside the keyword loop, you can loop by number to generate the page number. And to insert the URL to the table, use the `Insert data` block and input `https://xxx.com?SearchText={{loopData@keyword}}&page={{loopData@page}}` in the `value` field.

![image](https://user-images.githubusercontent.com/22908993/167737782-b931d62b-eb7a-4ebe-9a20-196702e675b2.png)

Or you can import the below workflow.

[Generate links.txt](https://github.com/Kholid060/automa/files/8665426/Generate.links.txt)

**Comment by Miruuacle** [comment]
> 

Thank you very much, your workflow is great, you helped me solve this problem, thank you again.

And, @Kholid060, I found when I copy a block, then I want to cancel the connection between two blocks, it always display "paste" when right click and Blocking the "X", I can't click "X".

**Comment by Kholid060** [comment]
> And, @Kholid060, I found when I copy a block, then I want to cancel the connection between two blocks, it always display "paste" when right click and Blocking the "X", I can't click "X".

I'll fix it, but you also can delete the connection by clicking the connection and pressing the "Delete" button

**Comment by Miruuacle** [comment]
> > And, @Kholid060, I found when I copy a block, then I want to cancel the connection between two blocks, it always display "paste" when right click and Blocking the "X", I can't click "X".
> 
> I'll fix it, but you also can delete the connection by clicking the connection and pressing the "Delete" button

OK, Thank you.
