### ISSUE TITLE
Is there a bug in saving asset blocks?

### ISSUE THREAD

**Issue by Adongggg** [AutomaApp/automa#489]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v0.12.0]

**Additional context**

**Comment by Kholid060** [comment]
Is there's something that not working or an error when using the save assets block?

**Comment by Adongggg** [comment]
Using show n.map is not a function error

**Comment by whwh656** [comment]
> Using show n.map is not a function error

#481

**Comment by Adongggg** [comment]
What is the reason for the saved asset block not being available?

**Comment by Adongggg** [comment]
> 使用保存资产块时是否有什么不工作或错误？

Prompt n.map error when using
