### ISSUE TITLE
Infinite process gets slower and crash over the time

### ISSUE THREAD

**Issue by juansabaye** [AutomaApp/automa#492]
**Describe the bug**
Infinite process gets slower and crash over the time

**To Reproduce**
1. Create an infinite 5 minute loop that open a new tab, sign in some where, check if some text exist, signout, close tab, repeat
2. Let it run a night
3. Wait to see it get slower
4. Wait for it to crash or stop

**Expected behavior**
Over the time it become slower 

**Screenshot**
![image](https://user-images.githubusercontent.com/39252070/168448135-53ec87d8-9609-490a-b36e-95a88e2d98b5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser: [Google Chrome]
 - Extension Version: [Versión 101.0.4951.67 (Build oficial) (64 bits)]

**Additional context**

**Comment by Kholid060** [comment]
Thanks for the report, it crashed because it hasn't optimized to handle an infinite process. I'll try to fix this in the future.

**Comment by juansabaye** [comment]
Oh, got it. What about not saving logs? Like setting an option for not saving logs

**Comment by Kholid060** [comment]
You can try that, and maybe that cause it gets slower because the log of the workflow saved into memory
