### ISSUE TITLE
The paste operation performed with the trigger event is invalid

### ISSUE THREAD

**Issue by F12EN** [AutomaApp/automa#495]
**Describe the bug**
Hi, I want to use the “trigger event”-“keyup” to trigger COMMAND +V to implement paste, but it doesn't work. Am I using it incorrectly or is there some other reason? Looking forward to your reply, thank you!

**Expected behavior**
 trigger COMMAND +V to implement paste.

**Screenshots**
![image](https://user-images.githubusercontent.com/25075086/168858192-e1a75b80-d5dd-4a33-aa86-82779b3d0a1e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Google Chrome
 - Extension Version: v101.0.4951.64

**Comment by Kholid060** [comment]
Automa or any chrome extension can't perform OS-level keyboard shortcuts like `Ctrl+V` or `Command+V` on Mac. Because these keys "presses" are simulated at the browser level, not on the OS level.

**Comment by F12EN** [comment]
@Kholid060 OK, Thank you!

**Comment by moonpie94** [comment]
@F12EN   hi   can I ask how you solved the pasting problem?
