### ISSUE TITLE
Add option to pin 1 workflow in toolbar

### ISSUE THREAD

**Issue by shahnawaz323** [AutomaApp/automa#497]
I was wondering how can we pin 1 workflow or a number of workflows separately on the bookmarks bar of a browser. I can't find the option anywhere right now.

For example I want to pin the workflow named "Skip Youtube ads" on my bookmarks bar in chrome.

So that I don't have to click 2 times to run a workflow

Please add this feature.

**Comment by Kholid060** [comment]
I don't think I'll add this feature because it'll require additional permission to make it work. If you want quick access to run the workflow, you can set the trigger of the workflow to `keyboard shortcut`, so you only need to press the shortcut whenever you want to run the workflow.

**Comment by shahnawaz323** [comment]
How can add keyboard shortcut? Sorry I new to this and I can't figure out till now even after trying. A video tutorial will be helpful

**Comment by Kholid060** [comment]
Open the workflow first, click the edit button in the [trigger ](https://docs.automa.site/blocks/trigger.html#trigger-block) block, and select the keyboard shortcut option.

![image](https://user-images.githubusercontent.com/22908993/169414777-4d5d1973-aba8-46bc-bd90-b8c4e2fd4f2c.png)
