### ISSUE TITLE
[firefox]Settings cannot save

### ISSUE THREAD

**Issue by spbdev** [AutomaApp/automa#502]
**Describe the bug**
In firefox, select "Chinese" at Automa - Settings - Language, but cannot apply, and lost the settings when reload/refresh page.

**To Reproduce**
1. Go to Settings
2. Select chinese at Language.
3. Reload page

**Comment by wordpure** [comment]
@Kholid060 

This bug still exists in Automa 1.16.5.

In Firefox 104, when the language is switched to Chinese, the console reports an error. After refreshing the page, the interface language does not change.

![图片](https://user-images.githubusercontent.com/68013962/185610508-7a03d1c4-d431-46c7-be2e-f617beb6d221.png)

**Comment by Kholid060** [comment]
I'll fix it

**Comment by wordpure** [comment]
> I'll fix it

Firefox extension can save settings after updating to 1.16.6, thanks for the fix.
