### ISSUE TITLE
Unable to Open New Tab with blank URL

### ISSUE THREAD

**Issue by amansinna** [AutomaApp/automa#503]
I tried to automate a process which require to perform action on welcome screen which we get when we click + sign to open new tab with no url. 

What I tried:
1. "New Tab" method - It didn't worked. It require a valid URL.
2. "Javascript Code" method - It also didn't worked. "window.open('chrome://newtab');"

Can anyone please help me to accomplish this task? Seems the provided method didn't worked.

**Comment by Kholid060** [comment]
I don't think you can accomplish that task because even though you're able to open a new tab with no URL, the chrome extension only can have access to the tab where the URL starts with `http` or `https`
