### ISSUE TITLE
selector copy no effect 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#504]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/20383505/169683049-c7c7459f-68fb-49ad-b172-ee9706ad0a5e.png">

automa:1.10.1 
os:macos
open selector list 
I click the copy button, i find no effect ,clipboard is null

**Comment by whwh656** [comment]
v1.11.2  it doesn't work

**Comment by whwh656** [comment]
v1.12.0
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/20383505/172267248-d4b322d6-288b-4c35-b9a7-64a46eb4461a.png">

**Comment by Kholid060** [comment]
For now, you can press the `ctrl+c` keys until it fixed
