### ISSUE TITLE
support compare diff  two takescreenshot

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#506]

**Comment by Kholid060** [comment]
Can you describe more about this feature? Like how it works, what you want to happen, etc.

**Comment by whwh656** [comment]
> Can you describe more about this feature? Like how it works, what you want to happen, etc.
The conditions block only compare by value or element ,but  i want to compare picture.
---------------------
example:
I want  to  upload  one screenshot of element A in my compute or network and compare  screenshot of  A with the screenshot of element B 

if they are the same  i think is pass else not pass
