### ISSUE TITLE
v1.11.0  {{activeTabUrl}} 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#510]
automa:v1.11.0
_**first question :**_
<img width="940" alt="image" src="https://user-images.githubusercontent.com/20383505/170502248-29bfd27f-5983-4fd6-92f1-40f55dd704e2.png">

**_second question:_**
 javascirpt block 
 const a = {{activeTabUrl}} ; 
 this is forbidden i couldn't get value of a

**Comment by Kholid060** [comment]
1. You can't use URL as the file name.
2. You can't use mustache tag (`{{}}`) inside the javascript code, use the [`automaRefData`](https://docs.automa.site/blocks/javascript-code.html#automarefdata-keyword-path) instead. For example,
```js
const url = automaRefData('activeTabUrl');

// Or if you want to get the current tab url
const url = window.location.href;
```

**Comment by whwh656** [comment]
> ```js
> const url = automaRefData('activeTabUrl');
> ```

thanks
