### ISSUE TITLE
auto waiting

### ISSUE THREAD

**Issue by chenshuichao** [AutomaApp/automa#512]
The network is variant，so "auto waiting" is cool!
playwright can be referred .

**Comment by mzaini30** [comment]
Can you explain?

**Comment by chenshuichao** [comment]
https://playwright.dev/docs/actionability

**Comment by chenshuichao** [comment]
@mzaini30

**Comment by jddcef** [comment]
Yes I'm sure any library can be included. Check the Javascript block, and the preload things in there
