### ISSUE TITLE
HTTP request how to  set variables in headers

### ISSUE THREAD

**Issue by foreverxhj** [AutomaApp/automa#518]
![image](https://user-images.githubusercontent.com/12062849/171317553-5a2083d4-1695-4798-a45f-7f99e0b2d20a.png)
I would like to know how to set variables in this place.

**Comment by Kholid060** [comment]
It's currently not possible to do that, I'll fix it in the next update

**Comment by foreverxhj** [comment]
![image](https://user-images.githubusercontent.com/12062849/171337027-62d1639a-7b6e-47be-b457-d8febef6bd72.png)
This how to set variables in payload

**Comment by Kholid060** [comment]
By using the mustache tag like 
```json
{
  "value": {{variables@variableName}}
}
```

If the variable value is a string, place the mustache tag inside a quote like `"{{variables@variableName}}"`

**Comment by mzaini30** [comment]
It seems this issue was solved
