### ISSUE TITLE
support variables in these blocks

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#523]
1 
for example: I may upload many files at one time  I want to a variable to write 
<img width="853" alt="image" src="https://user-images.githubusercontent.com/20383505/171991922-40413cc6-23bf-4270-822b-344c6314758b.png">

2
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/20383505/171991962-6e0da89f-151a-4422-9d00-64c9c3395f88.png">

**Comment by Kholid060** [comment]
1. You can already do that
2. I'll support it in the next update

**Comment by whwh656** [comment]
thanks
