### ISSUE TITLE
no log display

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#529]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/20383505/172038698-882c4e98-87e6-4bdc-bd1f-a8ec6664958f.png">
automa:v1.11.3
no log disply after workflow finished.

**Comment by Kholid060** [comment]
Try to reload the tab

**Comment by whwh656** [comment]
> Try to reload the tab
<img width="805" alt="image" src="https://user-images.githubusercontent.com/20383505/172039073-95881c92-f9f6-48e7-8221-f473f9504c3a.png">

thanks
