### ISSUE TITLE
how to handle the dialog popup on page load?

### ISSUE THREAD

**Issue by xjfnet** [AutomaApp/automa#532]
the page popup a dialog on onload, how to handle the dialog?

```html
<html>
<body>
<script>
alert('error');
</script>
</body>
</html>
```

**Comment by Kholid060** [comment]
Add the Handle dialog block before the dialog occurs
![image](https://user-images.githubusercontent.com/22908993/172088499-8438ae61-f35b-4e3d-b953-1555a40f6314.png)

**Comment by xjfnet** [comment]
no effect

**Comment by xjfnet** [comment]
there is a Login button on the page, click the Login button, the form post to the page itself, and then popup up a alert dialog to show error message

**Comment by Kholid060** [comment]
And try to enable the `Debug mode` in the workflow settings
![image](https://user-images.githubusercontent.com/22908993/172090549-3cdaafd1-1910-4c8a-adcc-54e48e713572.png)

**Comment by xjfnet** [comment]
no effect, even enable "Debug mode", and add "Handle Dialog" before "New Tab" and "Click Element"

**Comment by xjfnet** [comment]
can we inject script and replace alert at dom loaded?

**Comment by Kholid060** [comment]
> no effect, even enable "Debug mode", and add "Handle Dialog" before "New Tab" and "Click Element"

This might be a bug, I'll look into it


> can we inject script and replace alert at dom loaded?

Yes, by using the javascript code block
```js
const alertWindow = window.alert;
window.alert = () => {
  window.alert = alertWindow;
}

automaNextBlock();
```

**Comment by xjfnet** [comment]
but your code above seems run just once, it need to auto run when page reload after click element

**Comment by Kholid060** [comment]
Try this code
```js
window.alert = () => {
  window.alert = true;
}
```
And in the javascript code block, enable the `Execute every new tab`
![image](https://user-images.githubusercontent.com/22908993/172098802-72189e23-36f5-4f9e-9f73-85975a9e599f.png)

**Comment by xjfnet** [comment]
no effect, it seems that the `alert()` run before the code above

and i found these of `Chrome DevTools Protocol`, 
[Page.javascriptDialogClosed](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-javascriptDialogClosed)
[Page.javascriptDialogOpening](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-javascriptDialogOpening)
[Page.handleJavaScriptDialog](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-handleJavaScriptDialog)

**Comment by Kholid060** [comment]
> no effect, it seems that the `alert()` run before the code above
> 
> and i found these of `Chrome DevTools Protocol`, [Page.javascriptDialogClosed](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-javascriptDialogClosed) [Page.javascriptDialogOpening](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-javascriptDialogOpening) [Page.handleJavaScriptDialog](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-handleJavaScriptDialog)

Automa is actually using that when the `Debug mode` is enabled,
https://github.com/AutomaApp/automa/blob/340b66baac2fe6bc151286acaacaca2438c94325/src/background/workflowEngine/blocksHandler/handlerHandleDialog.js#L46-L56

**Comment by vleskiv** [comment]
@Kholid060 I have the same issue, the "Handle dialog" doesn't work as expected with the next workflow:
![image](https://user-images.githubusercontent.com/37241643/185765775-e73a0665-43f0-4149-9d53-943a4585bb1d.png)

it is easy to reproduce here:
https://the-internet.herokuapp.com/javascript_alerts
