### ISSUE TITLE
take-screenshot range of a single element does not match

### ISSUE THREAD

**Issue by zhfeng1** [AutomaApp/automa#534]
**Describe the bug**
take-screenshot range of a single element does not match

**To Reproduce**
Any page can be reproduced, such as https://docs.automa.site/ , selector: .theme-default-content

**Expected behavior**
Correct range

**Screenshots**
<img width="921" alt="image" src="https://user-images.githubusercontent.com/46773648/172100049-89983f95-dc99-422c-8881-3d4acd1db36d.png">
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/46773648/172100096-d3cb2b0f-2f2c-45e4-8dec-770ad6a504de.png">

**Desktop (please complete the following information):**
 - OS: MacOS Apple silicon
 - Browser: Google Chrome
 - Extension Version: 1.11.4

**Additional context**
None

**Comment by whwh656** [comment]
https://github.com/AutomaApp/automa/issues/475

I test it zoom in or  zoom out of chrome which can effect screenshot

**Comment by zhfeng1** [comment]
hello
But I don't use zoom in. It's currently 100%，
<img width="372" alt="image" src="https://user-images.githubusercontent.com/46773648/172279085-35ef4623-5fac-434c-a723-d7227e23e58a.png">

**Comment by whwh656** [comment]
you set zoom in ==60%

**Comment by zhfeng1** [comment]
Only 50% and 67% options，like this？It's too small.
But it does work，thanks.
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/46773648/172287190-b1dab5fe-f52d-4056-bd5c-d4096d5a757b.png">
