### ISSUE TITLE
add voice tips

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#535]
play a failed voice  when script run failed
play a successful voice  when script finshed

**Comment by Kholid060** [comment]
I don't think I'm gonna add voice audio when the workflow is finished executing.
But in the next update, there will be a notification whether the workflows run successfully or not

![Animation](https://user-images.githubusercontent.com/22908993/172123026-c25f176d-078f-43b7-ba71-9a9e26fe829c.gif)

**Comment by whwh656** [comment]
mac don't support  browser notifications alert

**Comment by Kholid060** [comment]
I didn't know that, maybe you can try Automa v1.12.0 first, and if the notification doesn't work you can comment here and I'll consider adding it into Automa.

**Comment by whwh656** [comment]
> I didn't know that, maybe you can try Automa v1.12.0 first, and if the notification doesn't work you can comment here and I'll consider adding it into Automa.
macos i try it,  no  notifications
<img width="902" alt="image" src="https://user-images.githubusercontent.com/20383505/172264903-4230037d-1fcb-44e2-9b57-ca4ebeab1513.png">

**Comment by Kholid060** [comment]
You need to grant the notification permission to Automa, to do it open the workflow settings
![NVIDIA_Share_YEga26N0BA](https://user-images.githubusercontent.com/22908993/172269712-cdc5de11-6f93-4ce7-93fa-0f83a40c0237.png)

**Comment by whwh656** [comment]
> You need to grant the notification permission to Automa, to do it open the workflow settings ![NVIDIA_Share_YEga26N0BA](https://user-images.githubusercontent.com/22908993/172269712-cdc5de11-6f93-4ce7-93fa-0f83a40c0237.png)

I'm sorry to tell you that  no effect on macos
<img width="741" alt="image" src="https://user-images.githubusercontent.com/20383505/172499797-7bdc1473-f743-42a0-8060-c925587f8981.png">
