### ISSUE TITLE
Is it possible to set the basis for css to find elements during automatic recording?

### ISSUE THREAD

**Issue by shaobeichen** [AutomaApp/automa#542]
**Is your feature request related to a problem? Please describe.**
Is it possible to set the basis for css to find elements during automatic recording? Because if it is based on css selectors, sometimes it will be based on id, but id is sometimes dynamic, so the script often fails, but full xpath is possible, so can you set the search element basis before recording?

**Describe the solution you'd like**
Set Find Element By Before Recording

**Comment by Kholid060** [comment]
It's not possible, you have to change it manually after you stop recording
