### ISSUE TITLE
backup failed

### ISSUE THREAD

**Issue by shaobeichen** [AutomaApp/automa#544]
**Describe the bug**
backup 
```json
{
  error: "Internal Server Error"
  message: "null value in column \"__id\" of relation \"workflows2\" violates not-null constraint"
  statusCode: 500
}
```
request params
```json
{
    "globalData": "[{ \"key\": \"value\" }]",
    "description": "",
    "dataColumns": [],
    "id": "CGSJTrR3xzvp2g3igITI9",
    "__id": null
}
```

**Comment by Kholid060** [comment]
Fixed

**Comment by Shu-Ji** [comment]
I have the same issue when backup:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/1127594/191398944-413f323f-24d8-418e-8ce6-6d4d847818d6.png">

Automa
Version: 1.20.0

**Comment by Kholid060** [comment]
> @Kholid060 I have the same issue when backup with the latest Automa version 1.20.0:
> 
> <img alt="image" width="1424" src="https://user-images.githubusercontent.com/1127594/191398944-413f323f-24d8-418e-8ce6-6d4d847818d6.png">
> 
> Automa Version: 1.20.0

This should be working now

**Comment by Shu-Ji** [comment]
> 

Yes, it works now. Thanks.
