### ISSUE TITLE
support call  Chrome devtools Recorder?

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#558]
if can Support is cool

![image](https://user-images.githubusercontent.com/20383505/172798301-78773a47-784f-45dd-a4fa-2b44ada3e15d.png)

Recorder can record many  complex canvas event which can reduce many javascript code simulation

**Comment by Kholid060** [comment]
Sorry, I don't think that's possible. Because of Automa and Chrome dev tools Recorder is a different app
