### ISSUE TITLE
it's not safe for me 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#562]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/20383505/173228641-86897283-6989-4713-af95-57e2244059b3.png">

I don't know why automa change my computer's proxy ip
The ip is in other place which affected my network speed and when i stop the chrome's proxy, automa will not work

**Comment by Kholid060** [comment]
Have you used the proxy block in Automa? If yes, that's might be the cause

**Comment by whwh656** [comment]
> Have you used the proxy block in Automa? If yes, that's maybe the cause why your proxy setting changed

I have delete workflow which include proxy block,but it no effect

**Comment by Kholid060** [comment]
You can disable Automa and then enable it. Or in the Automa dashboard, open the devtools (`ctrl+shift+i`) and then paste this code in the `console` tab 
```js
chrome.proxy.settings.clear({ scope: 'regular' })
```

**Comment by whwh656** [comment]
thank you, it work well

**Comment by whwh656** [comment]
> ```js
> chrome.proxy.settings.clear({ scope: 'regular' })
> ```

chrome.proxy.settings.clear({ scope: 'regular' }) only this way to solve this problem is  work
