### ISSUE TITLE
{{looData@loopid.data}} is unvalid 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#564]
v1.12.2
<img width="908" alt="image" src="https://user-images.githubusercontent.com/20383505/173238353-6f7c4e7c-3f45-4a69-afe3-3c43dd172859.png">

{{looData@loopid.data}} is unvalid
we must use {{prevBlockData@data}} is useful, I'm confused

**Comment by Kholid060** [comment]
You don't need to add `.data` at the end of it if you use `loopId`, you only need to do `loopData@loopId`.

**Comment by whwh656** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/20383505/173258673-d169c3d9-ba7e-4675-a97f-ebcf859055aa.png">
Can I understand the relationship between the three in this way
{{looData@loopId.$index}} =={{looData@loopId}}   ?
{{prevBlockData@data}}     == {{looData@loopId}} +1 ?
