### ISSUE TITLE
Copy and paste in different workflows

### ISSUE THREAD

**Issue by Axlabo** [AutomaApp/automa#566]
Is there any way to copy blocks from a workflow and paste to another ?

**Comment by whwh656** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/20383505/173374817-a714e969-7a8b-49ea-9c88-2cfdb4ba8893.png">
Press Ctrl and the left mouse button to select


press  ctrlkey and left click mouse at the same time to select block which you want  and click copy button then goto another workflow and paste them

**Comment by mzaini30** [comment]
lgtm

**Comment by mzaini30** [comment]
@Kholid060 solved
