### ISSUE TITLE
Javascript run automaSetVariable is invalid

### ISSUE THREAD

**Issue by wangshaojie1995** [AutomaApp/automa#567]
prev JavaScript block run automaSetVariable('test', [1,2,3]) 
but next  JavaScript block run automaRefData('variables', 'test') is undefined

**Comment by Kholid060** [comment]
Have you called the `automaNextBlock` function at the previous javascript block?

**Comment by wangshaojie1995** [comment]
Yes, I did

**Comment by wangshaojie1995** [comment]
Yes, I did

my code：
try { const length = document.getElementsByTagName('iframe').length + 1 automaSetVariable('iframeLength', [...new Array(length).keys()]) console.log(automaRefData('variables', 'iframeLength')) // result: [1,2,3] } catch(e) { console.error(e) automaSetVariable('iframeLength', []) }) automaNextBlock([...new Array(length).keys()].map(item => ({iframe:item})))

> Have you called the `automaNextBlock` function at the previous javascript block?

**Comment by Kholid060** [comment]
Can you open the workflow log to see whether the `iframeLength` variable is registered or not
![image](https://user-images.githubusercontent.com/22908993/173549793-4b2a21f5-d1e4-41d9-bc98-1e62987d8463.png)

**Comment by wangshaojie1995** [comment]
> 根据 javascript 代码块的执行时间，您的 JS 代码可能有问题。尝试检查正在执行 JS 代码的开发工具的控制台选项卡，或者您可以尝试此代码。
> 
> ```js
> try { 
>   const length = document.getElementsByTagName('iframe').length + 1
>   automaSetVariable('iframeLength', [...new Array(length).keys()]) 
>   console.log(automaRefData('variables', 'iframeLength')) // result: [1,2,3] 
> } catch(e) {
>   console.error(e)
>   automaSetVariable('iframeLength', [])
> }
> 
> automaNextBlock([...new Array(length).keys()].map(item => ({ iframe: item })))
> ```

I found the problem 
my workflow：switch Frame(iframe) -> javascript code(automaSetVariable) -> switch Frame(main) -> javascript code (automaRefData, result is undefined )
switch Frame Will it affect variables？

**Comment by Kholid060** [comment]
It is not supposed to affect it. I've tried it, and I think this is a bug because the variable is not registered. I'll fix it

**Comment by wangshaojie1995** [comment]
> It is not supposed to affect it. I've tried it, and I think this is a bug because the variable is not registered. I'll fix it

Thanks for your help
