### ISSUE TITLE
Source code BUG

### ISSUE THREAD

**Issue by wangshaojie1995** [AutomaApp/automa#574]
file: /src/utils/helper.js
line: 107  function parseJSON

BUG: JSON.parse(data); 
When data is [0], the result is 0
which will cause
/src/background/workflowEngine/blocksHandler/handlerLoopData.js 
if (!Array.isArray(currLoopData)) {
  throw new Error('invalid-loop-data');
}

**Comment by Kholid060** [comment]
Thanks, I'll fix it
