### ISSUE TITLE
http request block json response data path Can't get data

### ISSUE THREAD

**Issue by 847689421** [AutomaApp/automa#576]
json response screenshot below，I can't get json data using `data.children[0].children[1].alias`，can you help me？
request url is `https://help.aliyun.com/help/json/menupath.json?nodeId=214259&website=cn&language=zh`
![image](https://user-images.githubusercontent.com/20372242/173710811-218bbe44-9ae4-473f-86f9-f8aab5f25ddd.png)

**Comment by Kholid060** [comment]
Try `data.children.0.children.1.alias`

**Comment by 847689421** [comment]
ok,thanks
