### ISSUE TITLE
How to interactively preset some variables before the workflow starts

### ISSUE THREAD

**Issue by cs118651** [AutomaApp/automa#583]
Is there a feature that allows the user to customize some variables through an interactive dialog before the workflow starts？

**Comment by cs118651** [comment]
For example, I am now designing a workflow whose function is to automatically change a certain setting item for a gitlab project. I hope my users can interactively enter their own gitlab project name through a dialog box, instead of To edit the workflow, to change the global variables in it

**Comment by Kholid060** [comment]
> I hope my users can interactively enter their own GitLab project name through a dialog box, instead of To edit the workflow, to change the global variables in it

I think you can use the javascript block to show a dialog, for example
```js
const projectName = window.prompt('Enter project name')
automaSetVariable('projectName', projectName);
automaNextBlock();
```
The above code will show a dialog to the user and then save its value into the `projectName` variable.

**Comment by cs118651** [comment]
This solved my problem, thanks a lot！
