### ISSUE TITLE
ask for help,javaScript code block console.log Can't print log

### ISSUE THREAD

**Issue by 847689421** [AutomaApp/automa#585]
I wrote the print code in the javaScript code block，but I can't see the log printed by console in devtools。Is there something wrong with my usage?
![image](https://user-images.githubusercontent.com/20372242/173969635-57ca2a80-182c-4c89-8a35-e309e6233245.png)
![image](https://user-images.githubusercontent.com/20372242/173969452-7db95e87-553f-4e93-85ca-ced896ab396f.png)

**Comment by Kholid060** [comment]
Can you show the logs of the workflow?

**Comment by mzaini30** [comment]
Looking at logs tab. Maybe, you can see error like this:

![image](https://user-images.githubusercontent.com/7939342/173973481-e80149d1-ae2c-4e4b-9f5f-b6865830ab7b.png)

**Comment by 847689421** [comment]
![image](https://user-images.githubusercontent.com/20372242/173991636-9bb0a4b9-9f53-47e2-a2de-9305c83314e4.png)

**Comment by Kholid060** [comment]
You need to use the new tab block before using the javascript block

**Comment by 847689421** [comment]
my problem, i get it，thanks
