### ISSUE TITLE
google sheets block [GET spreadsheet range] preview data 404 error code

### ISSUE THREAD

**Issue by 847689421** [AutomaApp/automa#600]
I use google sheets to get table data error，Screenshot below。
![image](https://user-images.githubusercontent.com/20372242/174509888-4e6a8aa1-22f5-4c6b-b88b-c938682a352e.png)
![image](https://user-images.githubusercontent.com/20372242/174509889-8b269af4-bc96-439a-8725-28615c7de9dd.png)
![image](https://user-images.githubusercontent.com/20372242/174509901-27aed9b7-7eff-4081-891a-017c94c63dc3.png)

**Comment by Kholid060** [comment]
Make sure the spreadsheet id is correct and give Automa service account access permission to the spreadsheet https://docs.automa.site/blocks/google-sheets.html#access-to-spreadsheet
