### ISSUE TITLE
Can the value input of insert data block use variables?

### ISSUE THREAD

**Issue by 847689421** [AutomaApp/automa#607]
I use {{ variables@codeupUpdateLogObj }} or {{ googleSheets@results.0.oldCodeupUpdateLogObj }} in the value input box, it is not converted into a value, but directly stored as a string。
![image](https://user-images.githubusercontent.com/20372242/174693885-cfacaf6f-6eaf-440a-8735-a3ce5a673a7c.png)
![image](https://user-images.githubusercontent.com/20372242/174693862-5f9d27c5-1362-4c4e-88f9-cad5d49f2e38.png)

**Comment by Kholid060** [comment]
Check if `variables@codeupUpdateLogOb` exists in the workflow log because if it doesn't exist, Automa will not convert it into a value.

**Comment by 847689421** [comment]
ok,thanks
