### ISSUE TITLE
black Theme

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#612]
![image](https://user-images.githubusercontent.com/20383505/174731801-7948dbd2-cbc5-46c0-a4e6-6a3686bb7485.png)
page num is whtie

**Comment by mzaini30** [comment]
Solved in next version. I use Firefox

![IMG_20220624_145126](https://user-images.githubusercontent.com/7939342/175479838-5bfdefec-da57-4070-86d4-4fdb39ac4abc.jpg)

**Comment by mzaini30** [comment]
Wait. I'll try it on Chrome

**Comment by mzaini30** [comment]
I think we can't do it in Chrome because the background color for `<select>` can't be changed.
