### ISSUE TITLE
[Firefox]New tab block with option Wait till tab loaded error when url was redirected

### ISSUE THREAD

**Issue by spbdev** [AutomaApp/automa#615]
**Describe the bug**
New tab block with option "Wait till tab loaded" error when url was redirected

**To Reproduce**
1. Check "Wait till tab loaded" on New tab block
2. Run the workflow
3. New tab block error when url was redirected to login
4. The error is "Error code 2152398850"

**Screenshots**
![1](https://user-images.githubusercontent.com/5189960/174931505-c4076abc-650f-4838-a7ff-5cfcf25ba6fa.png)

**Comment by mzaini30** [comment]
Can you show me the workflow you created? Because I created a similar workflow, but it worked.

This is the workflow I created:
[ke bapas.json.txt](https://github.com/AutomaApp/automa/files/8973788/ke.bapas.json.txt)

**Comment by spbdev** [comment]
> Look at the gif，when delete thursday，but deleted friday and thusday still there.
![1](https://user-images.githubusercontent.com/5189960/175490051-08593981-3341-4e8e-b568-a720c5911f56.gif)
