### ISSUE TITLE
add change variable block

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#619]
if one workflow set global variable,eg : {["a":1]} initial
whether add one block change variable {["a":2]} when the workflow run successfully
when i run the workflow next time global variable is  {["a":2]} rather than  {["a":1]} ,  avoid I get data and store variable in database and get it  from backend api?

**Comment by whwh656** [comment]
PLS

**Comment by Kholid060** [comment]
I'm working on it, but you can actually tell Automa to save the variables by enabling the "Reuse last state" option

![qOyFm71Y5Q](https://user-images.githubusercontent.com/22908993/175471526-c90636bf-314e-4ed0-8ab6-59034f375ae9.png)

**Comment by whwh656** [comment]
thanks
