### ISSUE TITLE
css selector can't get title

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#624]
automa:1.13.2
<img width="987" alt="image" src="https://user-images.githubusercontent.com/20383505/175754564-1fe08ff0-4571-4840-8c98-5a47138f1fb2.png">

<img width="949" alt="image" src="https://user-images.githubusercontent.com/20383505/175754418-c17e1037-625b-424a-a780-3b04873edebe.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/20383505/175754456-689b23bc-a910-499c-88cb-fb0741c0f3f3.png">

[title.json.txt](https://github.com/AutomaApp/automa/files/8983715/title.json.txt)

**Comment by Kholid060** [comment]
It's working when I tested it,
![image](https://user-images.githubusercontent.com/22908993/175754898-af4fa009-900f-49e8-92a4-88d6fff96fe7.png)
[title (1).txt](https://github.com/AutomaApp/automa/files/8983735/title.1.txt)

**Comment by whwh656** [comment]
thanks
