### ISSUE TITLE
Context menu: variable `ctxTextSelection` is null in Zendesk

### ISSUE THREAD

**Issue by jin-ds** [AutomaApp/automa#633]
**Describe the bug**
Not sure if this is a bug or a Zendesk restriction somehow, but I'm successfully able to select text in other websites and use it as a variable (`$ctxTextSelection`), but when I try the same on https://domain.zendesk.com, the text is not grabbed. I don't get an error in the logs, there is just a null value

**To Reproduce**
See description

**Expected behavior**
Able to add selected text to variable `$ctxTextSelection`

**Screenshots**

Not working:

![](https://cdn.zappy.app/c869e58148af864aa611d6934f7e48bc.png)

Working:

![](https://cdn.zappy.app/da84756ad0ccbf3311400087f268e82e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Google Chrome
 - Extension Version: `
1.14.0`

**Additional context**
n/a

**Comment by mzaini30** [comment]
You can try with `window.getSelection()`

**Comment by jin-ds** [comment]
> You can try with `window.getSelection()`

Hi @mzaini30 —thanks for the suggestion!

I wish I understood how to implement that though :(

I'm a super-noob. The goal is to capture that text, and send it via an HTTP request. Would you be able to provide some screenshots of where/how I would add that function? Currently, I have it set up like this:

![](https://cdn.zappy.app/5a44049fa5a2edd59d2d983767e6917c.png)

Do I need a different trigger for and/or add additional steps?

Thanks so much!

**Comment by mzaini30** [comment]
- trigger context menu
- active tab
- JavaScript block: 

```javascript
let selection = window.getSelection().toString()
automaSetVariable("selection", selection) // CMIIW
automaNextBlock()
```

Now, get selection variabel with `{{variables@selection}}`

**Comment by jin-ds** [comment]
Oh thank you so much @mzaini30 !!! This is doing the trick as well! Much much much appreciated!!!!
