### ISSUE TITLE
v1.14.0 delete log is no effect

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#635]
logs can't be deleted 
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/20383505/177021853-87600eb4-cc78-4c10-b3c7-cdb76bf5ab17.png">

**Comment by Kholid060** [comment]
I'll fix it, in the meantime, you can delete the log from the logs page 
![image](https://user-images.githubusercontent.com/22908993/177022174-c8f09ca3-8c84-44a2-8859-4b80d9934675.png)

**Comment by whwh656** [comment]
thanks
