### ISSUE TITLE
block line lable function

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#640]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/20383505/177224946-419d1073-0225-45b6-953b-29560a4c97a6.png">
I don't understand this function how it works

**Comment by Kholid060** [comment]
It's for labeling the line
![image](https://user-images.githubusercontent.com/22908993/177225085-132bdeff-2388-4986-84e0-857b31266f00.png)
![image](https://user-images.githubusercontent.com/22908993/177225098-90e67142-d409-498e-8239-ac379d84ddb5.png)

**Comment by whwh656** [comment]
why give the line label name?

**Comment by Kholid060** [comment]
Maybe for making the workflow more readable. It's optional though, you don't have to add a label to the line.

**Comment by whwh656** [comment]
thanks
