### ISSUE TITLE
what is the difference between reload tab  and  force refresh?

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#647]
what is the difference between reload tab block  and  force refresh: ctrl + shirt +r  ?

**Comment by Kholid060** [comment]
The difference is the browser will keep the website cache when you reload and clear the website cache when you force refresh.

**Comment by whwh656** [comment]
> The difference is the browser will keep the website cache when you reload and clear the website cache when you force refresh.

thanks , because go back blcok  is not work so i ask this question

**Comment by Kholid060** [comment]
Is there an error in the workflow log? If the error says "Cannot find a next page in history." it means that the tab doesn't have a history, you can check whether the tab has a history by looking at the left and right arrow on the top left.
![image](https://user-images.githubusercontent.com/22908993/177700544-caa7de8d-5899-44ad-824e-f8bca8fd94e1.png)

**Comment by whwh656** [comment]
> Is there an error in the workflow log? If the error says "Cannot find a next page in history." it means that the tab doesn't have a history, you can check whether the tab has a history by looking at the left and right arrow on the top left. ![image](https://user-images.githubusercontent.com/22908993/177700544-caa7de8d-5899-44ad-824e-f8bca8fd94e1.png)

os:macos
version:1.15.1
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/20383505/178129189-e1610451-5658-4353-b85d-d23c072661a0.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/20383505/178129213-a16dbc17-a7e2-44cf-a16a-9229922ef96f.png">
