### ISSUE TITLE
duplicate block can't move 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#653]
automa 1.15.0
![image](https://user-images.githubusercontent.com/20383505/177965335-b55ce751-a2d9-40c9-ae62-c1e14c44b26b.png)

I duplicate click block but i can't move the copied block

**Comment by Kholid060** [comment]
Do something like this 

![duplicate](https://user-images.githubusercontent.com/22908993/177966166-7950352d-c665-428e-a05a-b73b7eebdf25.gif)

Both of them are moved because they're selected.

**Comment by whwh656** [comment]
> automa 1.15.0 ![image](https://user-images.githubusercontent.com/20383505/177965335-b55ce751-a2d9-40c9-ae62-c1e14c44b26b.png)
> 
> I duplicate click block but i can't move the copied block
![企业微信截图_16572741586575](https://user-images.githubusercontent.com/20383505/177967546-970df408-ed0a-4810-9947-c22f70a1403f.png)

![image](https://user-images.githubusercontent.com/20383505/177967506-1e96d2f3-2914-47ac-94ef-1106edcb97df.png)

**Comment by Kholid060** [comment]
Can you maybe provide a screen recording so I can more understand what's going on? Because I have tried following the image that you provided, but can't reproduce the issue that you were facing
