### ISSUE TITLE
what does it  means?

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#658]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/20383505/178128481-d9de84a0-8856-4db2-bbcb-a2244cd562ba.png">

**Comment by Kholid060** [comment]
Snap to the grid disabled
![without-snap-grid](https://user-images.githubusercontent.com/22908993/178129487-9742dfc0-65d6-440f-be83-01745ed32fa8.gif)

Snap to the grid enabled
![with-snap-grid](https://user-images.githubusercontent.com/22908993/178129484-3ffe39c7-db32-4d31-ad91-2584aa5c27fa.gif)

**Comment by whwh656** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/20383505/178131266-6ba2efc9-dbdd-4b5b-94af-4396a15dbeb6.png">

<img width="409" alt="image" src="https://user-images.githubusercontent.com/20383505/178131108-c3932d41-8d3a-41c6-a8a6-a78f7099de89.png">
 every black dot space is one pixel ?

**Comment by Kholid060** [comment]
It might be
