### ISSUE TITLE
tables & variables export/import feature

### ISSUE THREAD

**Issue by mylovelycodes** [AutomaApp/automa#659]
**Is your feature request related to a problem? Please describe.**
Hi,

i think that,  tables & variables export/import feature may useful for peoples who have two environments (dev & prod), 
and they useualy write workflow in dev pc and run in prod pc.  

in 1.15.0, the local backup in settings basically works now, 
but some workflows with operations on storage/tables & variables will cause exceptions.

**Describe the solution you'd like**

the local backup in settings may support  storage tables & variables.

If you can go a step further, support the entire automa configuration (including workflow, storage, settings) synchronized across devices using google drive, that would be even better.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kholid060** [comment]
> the local backup in settings may support storage tables & variables.
> 
> If you can go a step further, support the entire automa configuration (including workflow, storage, settings) synchronized across devices using google drive, that would be even better.

That's actually a good idea, I'll try to implement this in the future
