### ISSUE TITLE
Custom User-Agent in New Tab block not support  mustache tag

### ISSUE THREAD

**Issue by mylovelycodes** [AutomaApp/automa#663]
**Is your feature request related to a problem? Please describe.**

In New tab block ,  User-Agent do not support  mustache tag. hope can fix it.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/22500/178393953-21fcae28-65d9-4102-8a28-877b43b55742.png">

**Describe the solution you'd like**

1. add  mustache tag support in  User-Agent.
2. Automa could consider a plugin to obfuscate features to avoid being identified as a robot and thus better automate operations.

https://github.com/UltrafunkAmsterdam/undetected-chromedriver
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth#readme

**Describe alternatives you've considered**

by the way, i don't think use  chrome.debugger.sendCommand to add extra headers is a good idea. it need to detach a debugger and user can see "Automa is debugged this browser ..." tips at the browser .  maybe you can try declarativeNetRequest, it's more powerfull and automa can proiver a Header Block for users.

https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-ModifyHeaderInfo

**Additional context**
:)

**Comment by Kholid060** [comment]
> In New tab block , User-Agent do not support mustache tag. hope can fix it.

I'll fix it

> by the way, i don't think use chrome.debugger.sendCommand to add extra headers is a good idea. it need to detach a debugger and user can see "Automa is debugged this browser ..." tips at the browser . maybe you can try declarativeNetRequest, it's more powerfull and automa can proiver a Header Block for users.
> 
> https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-ModifyHeaderInfo
> 

I agree with this, I'm using the debugger because Automa already has the `debugger` permission which if I'm using the `declarativeNetRequest` API will require additional permission.
Hopefully, I can change this in the future.
