### ISSUE TITLE
collect block

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#664]
for example :

I usually only  use five block ,if Automa display  too many block it is not convenient 
i have a idea about :every block  should have a collect  icon 
and i want to fill default value in block and  then  i  click the collect icon  then this block and default value is saved  and   put in my collection box 
it ‘s  convenient for me to use next time and search block

**Comment by mzaini30** [comment]
I think it's like "most used" blocks

**Comment by whwh656** [comment]
> I think it's like "most used" blocks

good
