### ISSUE TITLE
Firefox sync support

### ISSUE THREAD

**Issue by flossgeek** [AutomaApp/automa#666]
Having an option to sync the workflows with Firefox sync would be very convenient.

**Comment by Kholid060** [comment]
I don't think that would be possible because as far as I know, Firefox doesn't have the API to do that.

**Comment by flossgeek** [comment]
They do have an API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by flossgeek** [comment]
I think that the size of the json file wouldn't be too big for Firefox Sync (except when someone would sync too large an amount of workflows of course). A backup from a freshly installed extension (with the two example workflows) is 20.4 KB for me, while the maximum size an extension may sync is 102.4 KB.

Great to have such a responsive maintainer on such a promising project.
