### ISSUE TITLE
Auto-test potential

### ISSUE THREAD

**Issue by edisonX-sudo** [AutomaApp/automa#67]
I see a great potential of auto-test in this project.
will that be possible 2 achieve some features like assertion or something 2 expose the execution status?
thanks.

**Comment by Kholid060** [comment]
> will that be possible 2 achieve some features like assertion or something 2 expose the execution status

Do you mean to expose the execution status of the workflow or the blocks of the workflow?

**Comment by xushunke** [comment]
it is like，mm... in the view of testing， the tester will make some assertion to verify if the program works fine， and if all assertion pass the result will show the green light ， the idea is some kind of like what i say above

**Comment by xushunke** [comment]
anyway as a tool 4 automation， this is quite impressing 4 me， and i believe it will be perfect if it can have the potential of testing， which gonna release the burden of the web developers truly

**Comment by Kholid060** [comment]
Got it, is it the extension already has this feature, I mean it already exposes the execution status and error in the log. And for the assertion feature, I think it's kinda tricky to implement but I will try my best.

**Comment by xushunke** [comment]
Thanks a lot 4 ur contribution, people like u make the community a better place.

**Comment by xushunke** [comment]
https://github.com/cypress-io/cypress
