### ISSUE TITLE
Hope that the new tab can use the variable

### ISSUE THREAD

**Issue by liuweiyibai** [AutomaApp/automa#677]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/179435311-042f3ca5-f356-4b76-93ac-8bd6a09bd124.png)
![image](https://user-images.githubusercontent.com/20383505/179435326-aa77722a-625a-47a7-afcf-49e56b38c4cf.png)
