### ISSUE TITLE
元素选择器

### ISSUE THREAD

**Issue by WDTLCC** [AutomaApp/automa#682]
在百度搜索页面元素选择器变型严重  无法使用
<img width="834" alt="企业微信截图_16583931154970" src="https://user-images.githubusercontent.com/33241387/180171764-2444bfa3-cf5a-4f2e-b543-3afd1a389c14.png">

**Comment by Kholid060** [comment]
Which version are you using?

**Comment by WDTLCC** [comment]
Hello, I used version 1.3.1 for secondary development

**Comment by Kholid060** [comment]
Try use the newer version, because the fixed is in there.

**Comment by WDTLCC** [comment]
![1658720516649](https://user-images.githubusercontent.com/33241387/180694710-8c4180a5-9022-4b9b-907c-3e2da686b1c5.jpg)
我尝试使用automa最新版本

**Comment by Kholid060** [comment]
> ![1658720516649](https://user-images.githubusercontent.com/33241387/180694710-8c4180a5-9022-4b9b-907c-3e2da686b1c5.jpg) 我尝试使用automa最新版本

It's version v1.15.3?
![image](https://user-images.githubusercontent.com/22908993/180694989-bae8ff4e-7de9-4909-b4fb-b92157d9b61e.png)

**Comment by WDTLCC** [comment]
您可以尝试点击关闭按钮   在打开元素选择器

![1658720941083](https://user-images.githubusercontent.com/33241387/180695371-4e1b751c-d739-4bda-8c81-d918e9590473.jpg)
![1658721028995](https://user-images.githubusercontent.com/33241387/180695434-28974ebb-7638-437b-9c56-09d0a419d5cf.jpg)

**Comment by Kholid060** [comment]
I'll fix it
