### ISSUE TITLE
how can i keep  the format '\n' in httprequest block

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#684]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/20383505/180393825-8e332ecb-8d66-4d5f-a531-7af6ffcaec43.png">

<img width="861" alt="image" src="https://user-images.githubusercontent.com/20383505/180389890-0fc93cba-712e-4fdf-ab80-5c6bd824a712.png">

**Comment by Kholid060** [comment]
The `\n` will be automatically converted into a new line

**Comment by whwh656** [comment]
> The `\n` will be automatically converted into a new line
log is error
<img width="629" alt="image" src="https://user-images.githubusercontent.com/20383505/180456113-738f4348-79fb-4d2b-be01-4095158459e5.png">
![Uploading image.png…]()

**Comment by whwh656** [comment]
need help

**Comment by Kholid060** [comment]
I think it's because of the new line that caused the error. For now, try to remove the new line when sending an HTTP request. To remove the new line use the javascript block and copy the below code

```js
const variable = automaRefData('variables', 'key1')
automaSetVariable('key1', variable.replace(/(?:\r\n|\r|\n)/g, ' '))
```

**Comment by whwh656** [comment]
thanks ,
if i want to export or send http  keep the format '\n' ,maybe is it impossible?

**Comment by Kholid060** [comment]
I actually haven't tested it
