### ISSUE TITLE
Is there an API for import workflow ? 

### ISSUE THREAD

**Issue by Yvees** [AutomaApp/automa#686]
**Is your feature request related to a problem? Please describe.**
I am trying to import workflow file by JS. 

**Describe the solution you'd like**
So is there an API for import workflow ? 

**Describe alternatives you've considered**
Or an entry for writing db ? or any other ways to import a workflow file by code.

**Comment by Kholid060** [comment]
There's no API to import a workflow. If you want to import a workflow by code you can modify the source code, for example

```js
import { useWorkflowStore } from '@/stores/workflow';

const workflowStore = useWorkflowStore();
workflowStore.insert(workflowObj);
```

**Comment by Yvees** [comment]
Hi, @Kholid060  thank you for reply. Actually what I mean is how to import a workflow outside the extension by the json file. I have a html page, and one button in the page. When I click the button, then insert a workflow to the automa. 
So is there a way to implement this by code.

**Comment by Kholid060** [comment]
Automa doesn't have an API for doing that
