### ISSUE TITLE
data block 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#687]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/20383505/182008007-113ddf91-875b-4bd2-a9b4-43457a94f98d.png">

[aaa.automa.txt](https://github.com/AutomaApp/automa/files/9227980/aaa.automa.txt)

**Comment by Kholid060** [comment]
As you can see here, the value of the `cx` variable is an array. Therefore, if you want to reference the value of the `cx` variable, try `{{variables@cx.0}}`

![chrome_MhkpviCKBJ](https://user-images.githubusercontent.com/22908993/182008670-012be4e2-97d3-4023-aa57-c6d3f43d54c0.png)

**Comment by whwh656** [comment]
thanks

**Comment by whwh656** [comment]
> As you can see here, the value of the `cx` variable is an array. Therefore, if you want to reference the value of the `cx` variable, try `{{variables@cx.0}}`
> 
> ![chrome_MhkpviCKBJ](https://user-images.githubusercontent.com/22908993/182008670-012be4e2-97d3-4023-aa57-c6d3f43d54c0.png)

<img width="876" alt="image" src="https://user-images.githubusercontent.com/20383505/182016823-f3f23f61-811b-4d55-b5a9-271fe1822274.png">
no effect

**Comment by Kholid060** [comment]
I forgot that you can't use the mustache tag in the RegEx block, so you need to use the insert data block before the RegEx block like in the image
![image](https://user-images.githubusercontent.com/22908993/182017087-b123d16a-c4f3-4224-849a-b3ce6a02fab1.png)

**Comment by whwh656** [comment]
thanks
