### ISSUE TITLE
Another questions: remove html scroll event

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#693]
remove html event scroll by chrome devtools eventlistener
![image](https://user-images.githubusercontent.com/20383505/182504571-adf8e613-cc96-47f0-9bf8-2df0865192fe.png)

![image](https://user-images.githubusercontent.com/20383505/182504622-eb4c4751-5635-436f-8bde-4df1f27536f9.png)

afert removed : The scrollbar can still  be  scrolled 
![image](https://user-images.githubusercontent.com/20383505/182504735-48c9d975-f442-4e97-9545-31f1a3be392a.png)

I want to know why can be scrolled after remove scroll event

**Comment by Kholid060** [comment]
> I want to know why can be scrolled after remove scroll event

Because the `scroll` event doesn't have anything to do with the scrollbar, the `scroll` event is used to listen to the element when it's been scrolled. If you only want the page is not scrollable, you can just use CSS. For example,
```css
html {
  overflow: hidden;
} 
```
