### ISSUE TITLE
Can't use variables in HTTP request block settings in `dev` branch

### ISSUE THREAD

**Issue by nicolas-t** [AutomaApp/automa#695]
Hello Ahmad, 

I've been testing the latest features that are going to get released from the `dev` branch, especially the support for HTML in the HTTP Request block: https://github.com/AutomaApp/automa/commit/5ecb52609e36b422365138ee72a7b8bbbd552abc

It's working great for the content in the body, but I found that it broke the use of mustache variables in the API URL as well as the Header values, thus breaking the flows where I used variables to dynamically define the API endpoint. 

I think it's regression since it is working fine on `main`.

Thanks in advance for your help, 

Nicolas

**To Reproduce**
1. Create an HTTP request block
2. Use variables in requested URL 

**Expected behavior**
On the current version (1.15.2) we can use mustaches to construct the requested URL

**Screenshots**
![image](https://user-images.githubusercontent.com/1765930/182890727-a61b8b3f-e4f4-4755-98d6-5d625ecca8a5.png)
![image](https://user-images.githubusercontent.com/1765930/182891322-50e31a51-72ae-4371-8afa-d8ad3afa0f4e.png)
Above we can see what looks like unnecessary quotes around the `replacedValues` strings.

**Desktop (please complete the following information):**
 - Extension Version: dev

**Comment by Kholid060** [comment]
Fixed
