### ISSUE TITLE
download video m3u8

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#699]
targeturl:https://mp.weixin.qq.com/s?__biz=Mzg3ODUyMzQ1MQ==&mid=2247486745&idx=2&sn=d57bc27aaae785f3e296c13f78e1aefd&chksm=cf13284df864a15b5c6a6737f55e2d8a53907dd1bf84fc105510dc1350952282b3317cb9fd24&scene=21#wechat_redirect

2 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/20383505/183272337-ac72d2f9-9607-4642-af18-596b7281ad5a.png">

3 can help me download this video in this page , i can't find this videourl

**Comment by Kholid060** [comment]
I don't think this would be possible using Automa because to be able to download files like a video or an image, it needs the full URL of those files.
