### ISSUE TITLE
storage variablies no effect

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#705]
![image](https://user-images.githubusercontent.com/20383505/183578525-6bc59e1a-3278-4c35-abd2-1e1d4e2b6f12.png)

automa:1.16.2

![image](https://user-images.githubusercontent.com/20383505/183578642-aacab6a3-19e9-48ef-8989-2e09ef39b276.png)

**Comment by Kholid060** [comment]
Try add `$$` before the variable name, for example `{{variables@$$inputnews}}`. If it doesn't work, try re-add the variable.

**Comment by whwh656** [comment]
> {{variables@$$inputnews}}

[ctest.automa.txt](https://github.com/AutomaApp/automa/files/9288436/ctest.automa.txt)
no effect

**Comment by Kholid060** [comment]
Have you tried to remove and add the variable?

**Comment by whwh656** [comment]
> Have you tried to remove and add the variable?

i tried, no effect
