### ISSUE TITLE
I have some problems :)

### ISSUE THREAD

**Issue by Spark831** [AutomaApp/automa#718]
HI!
I'd like to fill data from google sheet.
![image](https://user-images.githubusercontent.com/111445068/185173837-59d49b3c-bb94-4d8c-895e-166279090a29.png)
![image](https://user-images.githubusercontent.com/111445068/185174024-7fe3b77b-c47c-4c8e-bb47-6651b9dd8134.png)
![image](https://user-images.githubusercontent.com/111445068/185174106-0337d5d5-2a24-433c-855e-001ba814b3da.png)
![image](https://user-images.githubusercontent.com/111445068/185174280-3727a61e-e6df-4148-aa89-f74e57e45c8d.png)
but, when I output... 
![image](https://user-images.githubusercontent.com/111445068/185174579-f44c9f55-f51d-4602-8028-d532ca767949.png)
there are square brackets and Quotation marks at the forward and backward.
how to adjust the program so that the forward and backward don't include square brackets and Quotation marks?
and how to repeat the program so that the next data can be filled ?
(sorry there are lots of problems) 
thanks!

**Comment by oddtoddd** [comment]
hey @Spark831 
im having the same problem and just wondering how or if you fixed it
thanks

**Comment by oddtoddd** [comment]
I ended up adding it twice to get rid of both brackets but it works now, thank you so much
