### ISSUE TITLE
How do I insert multiple cols at once in insert data to table?

### ISSUE THREAD

**Issue by wuwenrufeng** [AutomaApp/automa#734]
insert data is:
![insert data block](https://user-images.githubusercontent.com/45844514/186343466-90ca3de2-d84a-42b6-82b0-d8d60e7888b3.png)

table is:
![articles](https://user-images.githubusercontent.com/45844514/186343487-4fecde48-4d01-4f9c-8dd3-29d218d8f4cf.png)

result:
![result](https://user-images.githubusercontent.com/45844514/186343517-dc9612f6-6dc4-4ad9-b586-0334f83ee564.png)

**Comment by wuwenrufeng** [comment]
The test found that referencing the variable triggered the bug

**Comment by Kholid060** [comment]
Thanks for the report, I'll fix it
