### ISSUE TITLE
1.16.4 After a table is added, an Error occurs when a user clicks the table

### ISSUE THREAD

**Issue by carls96** [AutomaApp/automa#738]
![1](https://user-images.githubusercontent.com/59246551/186622715-fc0015bd-671a-499a-90ea-b85ce45997c3.png)
![2](https://user-images.githubusercontent.com/59246551/186622720-43da42cd-2e0a-4295-91e5-36c7809a060f.png)
![3](https://user-images.githubusercontent.com/59246551/186622725-d7932262-b6d4-43cf-b07f-405510cf4ee0.png)

**Comment by Kholid060** [comment]
Update the extension to 1.16.7
