### ISSUE TITLE
Allow removing shortcuts

### ISSUE THREAD

**Issue by m0nhawk** [AutomaApp/automa#739]
**Is your feature request related to a problem? Please describe.**
Default shortcut is conflicting with Chrome's Cmd + Shift + A for "Search Tabs", and I'm unable to find shortcut that is available.

**Describe the solution you'd like**
In addition to "Record shortcut", there is also a "Delete shortcut" button.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

---

Something like this:
<img width="873" alt="issue" src="https://user-images.githubusercontent.com/8220926/186791071-83ed8da5-e5fa-4fde-8ea9-3035e3dd9bab.png">

**Comment by Kholid060** [comment]
To change the keys, go to settings > shortcuts > Automa shortcut. And to prevent conflict, you can change the shortcut into ctrl+alt/option+a
![image](https://user-images.githubusercontent.com/22908993/186790908-410d6712-d4ed-4f52-b5f7-8b9e4255a77f.png)

**Comment by george-martinec** [comment]
Please allow removing shortcut it's annoying
