### ISSUE TITLE
Proposal: Reusable Package

### ISSUE THREAD

**Issue by mgilangjanuar** [AutomaApp/automa#756]
**Is your feature request related to a problem? Please describe.**
Sometimes we build a workflow from multiple reusable blocks, eg. `send to gmail when...`, `add an event to gcal if...`, etc

**Describe the solution you'd like**
Create an Automa Package Manager for people to publish their reusable packages which can be installed like in Automa Marketplace.

**Describe alternatives you've considered**
Make a block folder (in existing feature v1.17.0) shareable to others.

**Additional context**
Here's an example of using a reusable package in a workflow:

![image](https://user-images.githubusercontent.com/3146378/187573933-84fa20c2-f00f-494f-b855-a07fc51b9d92.png)

**Comment by mzaini30** [comment]
Can I ungroup Reusable Package?
