### ISSUE TITLE
[bug] memory leaks issue when run workflows repeatly

### ISSUE THREAD

**Issue by fzn0x** [AutomaApp/automa#759]
**Is your feature request related to a problem? Please describe.**
Running workflows repeatly with Infinite loop will cause memory leaks, it's probably caused by large arrays, I believe this is the root cause https://github.com/AutomaApp/automa/blob/849201fa15fecd38605453b39990497d7374d576/src/background/index.js#L294

**Describe the solution you'd like**
Clear the arrays on repeat block if possible.

**Describe alternatives you've considered**
-

**Additional context**
Relate to #492

**Comment by mzaini30** [comment]
Thanks for your suggestion

**Comment by Kholid060** [comment]
> **Is your feature request related to a problem? Please describe.** Running workflows repeatly with Infinite loop will cause memory leaks, it's probably caused by large arrays, I believe this is the root cause
> 
> https://github.com/AutomaApp/automa/blob/849201fa15fecd38605453b39990497d7374d576/src/background/index.js#L294
> 
> **Describe the solution you'd like** Clear the arrays on repeat block if possible.
> 
> ## **Describe alternatives you've considered**
> **Additional context** Relate to #492

I don't think this line of code is the root cause
https://github.com/AutomaApp/automa/blob/849201fa15fecd38605453b39990497d7374d576/src/background/index.js#L294

because it's only pushing the item into the array when the user is using the [record workflow](https://docs.automa.site/guide/creating-workflow.html#recording-a-workflow) feature.

Or do you have the workflow to reproduce this bug?

**Comment by fzn0x** [comment]
> > **Is your feature request related to a problem? Please describe.** Running workflows repeatly with Infinite loop will cause memory leaks, it's probably caused by large arrays, I believe this is the root cause
> > https://github.com/AutomaApp/automa/blob/849201fa15fecd38605453b39990497d7374d576/src/background/index.js#L294
> > 
> > **Describe the solution you'd like** Clear the arrays on repeat block if possible.
> > ## **Describe alternatives you've considered**
> > **Additional context** Relate to #492
> 
> I don't think this line of code is the root cause
> 
> https://github.com/AutomaApp/automa/blob/849201fa15fecd38605453b39990497d7374d576/src/background/index.js#L294
> 
> because it's only pushing the item into the array when the user is using the [record workflow](https://docs.automa.site/guide/creating-workflow.html#recording-a-workflow) feature.
> 
> Or do you have the workflow to reproduce this bug?

The workflow is the same as related issue.
another 
If it's not the root cause, maybe it is another arrays operation that causing the issue https://github.com/AutomaApp/automa/blob/849201fa15fecd38605453b39990497d7374d576/src/background/index.js#L499 or logs

I think no operation causing the memory leaks outside the arrays operation.

**Comment by fzn0x** [comment]
Do you think you already clear every arrays whenever it is on repeat? If not, I think you need to clear it or simplifying it that it is the same workflow but repeated without pushing the same workflow again

**Comment by fzn0x** [comment]
clear means you need to reset it to NULL state again.

**Comment by mzaini30** [comment]
Can you give us the workflow that happen this error?
