### ISSUE TITLE
Trigger Inputs

### ISSUE THREAD

**Issue by zawadzkip** [AutomaApp/automa#76]
**Is your feature request related to a problem? Please describe.**
I have certain workflows that can vary based on a single input that I would like to select on trigger time. 

**Describe the solution you'd like**
With the trigger option, it would be nice to be able to select from a pre-determined list of inputs that I can trigger a workflow with.

**Describe alternatives you've considered**
:) 

**Additional context**
I use this tool to automate the login flow for an app I work on. We have multiple test users that we use, and it would be great to be able to select the test user directly from the trigger time, instead of making a new workflow for each test user, with the same underlying flow.

**Comment by Kholid060** [comment]
I will try to add this feature in the next update

**Comment by jddcef** [comment]
I think this can be closed
