### ISSUE TITLE
Loop data: how to loop arrays in GlobalData

### ISSUE THREAD

**Issue by 13771412500** [AutomaApp/automa#760]
I want to use the variable function of loop data to loop the array in GlobalData, but an error is reported

![image](https://user-images.githubusercontent.com/39471894/188267680-dadb04af-165e-4db1-9adf-36c65f05a984.png)
![image](https://user-images.githubusercontent.com/39471894/188267692-d737cb50-11cb-4f58-ba54-96f193906ed3.png)
![image](https://user-images.githubusercontent.com/39471894/188267717-c1e2743b-382c-401c-930c-ca24966ddcbf.png)

**Comment by Kholid060** [comment]
Select the "Custom data" option in the loop data block and insert the data like `{{globalData@hobbies}}`
![image](https://user-images.githubusercontent.com/22908993/188267824-6c236f65-c402-4a8a-aa7b-7540a4ecf481.png)

**Comment by 13771412500** [comment]
> 在循环数据块中选择“自定义数据”选项并插入数据，如`{{globalData@hobbies}}` ![图片](https://user-images.githubusercontent.com/22908993/188267824-6c236f65-c402-4a8a-aa7b-7540a4ecf481.png)

Thank you. I see what you mean. How is variable used?
![image](https://user-images.githubusercontent.com/39471894/188267947-7476205e-628e-4c03-b3f0-eac1366e61a9.png)

**Comment by Kholid060** [comment]
It's used when you want to loop data from a [variable](https://docs.automa.site/api-reference/variables.html#variables), and you only need to input the variable name there.

**Comment by 13771412500** [comment]
> It's used when you want to loop data from a [variable](https://docs.automa.site/api-reference/variables.html#variables), and you only need to input the variable name there.

Thank you. I tried, but I still seem to report an error, as shown below:

![image](https://user-images.githubusercontent.com/39471894/188268261-a6479674-bbfd-4418-8453-2324c9886f67.png)
![image](https://user-images.githubusercontent.com/39471894/188268280-74c496ab-d207-45ea-be60-d837a743bf49.png)
![image](https://user-images.githubusercontent.com/39471894/188268292-ee55de47-0371-4a85-9f30-351238a89d42.png)

**Comment by 13771412500** [comment]
> It's used when you want to loop data from a [variable](https://docs.automa.site/api-reference/variables.html#variables), and you only need to input the variable name there.

I understand. It's not an expression, so you can't use a dot. Thank you

**Comment by Kholid060** [comment]
> > It's used when you want to loop data from a [variable](https://docs.automa.site/api-reference/variables.html#variables), and you only need to input the variable name there.
> 
> I understand. It's not an expression, so you can't use a dot. Thank you

Yes, currently it's not possible to use dot when you want to loop variable in the loop data block
