### ISSUE TITLE
Wait connection fails: this.engine.waitConnections[t][n.id] is undefined

### ISSUE THREAD

**Issue by Joachricar** [AutomaApp/automa#763]
After upgrading to v1.18.1 the wait connection element fails:

`this.engine.waitConnections[t][n.id] is undefined`

This was not an issue on friday, before the upgraqde.

**Comment by Kholid060** [comment]
If you're using Chrome, the fix is on its way

**Comment by Joachricar** [comment]
Ahh, sorry forgot to add that I'm using firefox :)

**Comment by Kholid060** [comment]
It's working when I tested it, maybe try to restart your browser. If it is still not working, try to remove and add the wait connections block

![image](https://user-images.githubusercontent.com/22908993/188382318-7599a1e8-50ad-4873-908e-6edd9b61db74.png)

**Comment by Joachricar** [comment]
I tried upgrading firefox, re-add the wait connections block, but I'm still seeing the issue:
![image](https://user-images.githubusercontent.com/1376026/188383076-30f88b01-25ac-42e2-80a9-53847c28b2b5.png)

This error prompted me to update my script, and I found that I don't really need that block.
