### ISSUE TITLE
[Feature request] Topping Workflow

### ISSUE THREAD

**Issue by evolution-ant** [AutomaApp/automa#771]
It is difficult to manage a large number of workflows.
Maybe it can be displayed in this position.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/24502661/189268551-0bd8ab1a-95b8-40b6-9ffd-1cc06f52d104.png">

**Comment by Kholid060** [comment]
> It is difficult to manage a large number of workflows.
> Maybe it can be displayed in this position.

Do you mean difficult to manage the workflows in the Automa dashboard?
![image](https://user-images.githubusercontent.com/22908993/189269118-275eead6-5abf-4539-a9eb-15a51714823a.png)

**Comment by evolution-ant** [comment]
Workflow sequencing , top commonly used workflows , so i can find them quickly.

**Comment by Kholid060** [comment]
> Workflow sequencing , top commonly used workflows , so i can find them quickly.

Got it
