### ISSUE TITLE
[Feature request] input data to the workflow

### ISSUE THREAD

**Issue by evolution-ant** [AutomaApp/automa#773]
**Is your feature request related to a problem? Please describe.**
I want to input data to the workflow

**Describe the solution you'd like**
search for input data
<img width="364" alt="image" src="https://user-images.githubusercontent.com/24502661/189313318-68510f13-494f-400b-8866-eb1a3cfb51fa.png">

**Comment by Kholid060** [comment]
You can add a [parameter](https://docs.automa.site/blocks/trigger.html#parameters) to the workflow

**Comment by evolution-ant** [comment]
> 

I want to change parameters frequently, that way is tedious. For example, I have to translate words frequently

**Comment by evolution-ant** [comment]
> You can add a [parameter](https://docs.automa.site/blocks/trigger.html#parameters) to the workflow
I can't know this data in advance

**Comment by Kholid060** [comment]
> I want to change parameters frequently, that way is tedious. For example, I have to translate words frequently

Can you explain more about this? Because I can't grasp what are you trying to do.

**Comment by evolution-ant** [comment]
> > I want to change parameters frequently, that way is tedious. For example, I have to translate words frequently
> 
> Can you explain more about this? Because I can't grasp what are you trying to do.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/24502661/189316455-9820a59b-7dc8-4bae-8586-2c8e1f634fc5.png">
Like alfred ,enter the content and pass it into the workflow

**Comment by evolution-ant** [comment]
> > I want to change parameters frequently, that way is tedious. For example, I have to translate words frequently
> 
> Can you explain more about this? Because I can't grasp what are you trying to do.

Want to enter data temporarily instead of setting it up in advance

**Comment by Kholid060** [comment]
You can do that using the workflow parameters

https://user-images.githubusercontent.com/22908993/189326246-b6f1ca95-aadd-4c29-a369-4e8074b5e308.mp4

**Comment by evolution-ant** [comment]
> You can do that using the workflow parameters
> 
>  parame.mp4
Thanks, you're right, I didn't really use this feature before
