### ISSUE TITLE
Logging no longer works in Firefox

### ISSUE THREAD

**Issue by okaune** [AutomaApp/automa#774]
**Describe the bug**
After updating to the latest version (1.18.1), logs seems to be broken in Firefox. Also testet that the same automations have logs as expected in Chrome.

**To Reproduce**
1. Run any automa workflow that normally should have logging in Firefox.
2. Check log tab, no logs to be found.

**Expected behavior**
Expect to have logs in the same way as in previous versions of the extention and as it currently works in Chrome.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Firefox 103.0.2
 - Extension Version: v1.18.1

**Comment by Kholid060** [comment]
I can't reproduce this issue, have you tried to clear the workflow logs?

**Comment by okaune** [comment]
Strange. We were two users in different locations that experienced this issue on Firefox on Friday. When testing now, however, it seems to work as expected again. The workflow logs were completely empty even though the workflow had been run multiple times in the past (and also had log entries in the past). Now all log entries for the workflows seems to be back again. Not sure what could cause this, but it is all working again now at least.
