### ISSUE TITLE
[Feature request] Tabs API

### ISSUE THREAD

**Issue by standingflower0607** [AutomaApp/automa#784]
I want get the numbers of tabs that are opend and index of tabs. 
Can I get that information in Javascript Code Brock? If so, could you tell how to do it?

**Comment by Kholid060** [comment]
You can use the get tab URL first like below
![image](https://user-images.githubusercontent.com/22908993/189556053-6d4a9119-670b-4af1-8f26-c63f1e2fa746.png)

And then using the [`$getLength`](https://docs.automa.site/api-reference/reference-data.html#getlength-str) function to count how many tabs are open in the window `{{$getLength([variables@tabs])}}`

![image](https://user-images.githubusercontent.com/22908993/189556107-ee63e4fc-0c26-4666-b196-28f5b4bf3504.png)

**Comment by standingflower0607** [comment]
Thank you !
