### ISSUE TITLE
interval doesn't work on firefox

### ISSUE THREAD

**Issue by q629988171** [AutomaApp/automa#788]
**Describe the bug**
interval doesn't work for firefox

**To Reproduce**
1. Trigger->Interval->1 minutes->Fixed delay
2. Active tab
3. reload tab

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 版本 10.0.18362.356
 - Browser: Firefox 104.0.2 (64 位)
 - Extension Version: automa-1.19.0.xpi

**Additional context**
`{
	"extVersion": "1.19.0",
	"name": "test",
	"icon": "riGlobalLine",
	"table": [],
	"version": "1.19.0",
	"drawflow": "{\"drawflow\":{\"Home\":{\"data\":{\"d7077850-67de-47e3-a9f0-dad65d98f425\":{\"id\":\"d7077850-67de-47e3-a9f0-dad65d98f425\",\"name\":\"trigger\",\"data\":{\"disableBlock\":false,\"description\":\"\",\"type\":\"interval\",\"interval\":1,\"delay\":5,\"date\":\"\",\"time\":\"00:00\",\"url\":\"\",\"shortcut\":\"\",\"activeInInput\":false,\"isUrlRegex\":false,\"days\":[],\"fixedDelay\":true},\"class\":\"trigger\",\"html\":\"BlockBasic\",\"typenode\":\"vue\",\"inputs\":{},\"outputs\":{\"output_1\":{\"connections\":[{\"node\":\"6f93bcf6-cb76-4609-8828-1af3262779bb\",\"output\":\"input_1\"}]}},\"pos_x\":50,\"pos_y\":300},\"6f93bcf6-cb76-4609-8828-1af3262779bb\":{\"id\":\"6f93bcf6-cb76-4609-8828-1af3262779bb\",\"name\":\"active-tab\",\"data\":{\"disableBlock\":false},\"class\":\"active-tab\",\"html\":\"BlockBasic\",\"typenode\":\"vue\",\"inputs\":{\"input_1\":{\"connections\":[{\"node\":\"d7077850-67de-47e3-a9f0-dad65d98f425\",\"input\":\"output_1\"}]}},\"outputs\":{\"output_1\":{\"connections\":[{\"node\":\"dbffcfb5-9d66-49fa-8a20-d697b8cf63d9\",\"output\":\"input_1\"}]}},\"pos_x\":471,\"pos_y\":329},\"dbffcfb5-9d66-49fa-8a20-d697b8cf63d9\":{\"id\":\"dbffcfb5-9d66-49fa-8a20-d697b8cf63d9\",\"name\":\"reload-tab\",\"data\":{\"disableBlock\":false},\"class\":\"reload-tab\",\"html\":\"BlockBasic\",\"typenode\":\"vue\",\"inputs\":{\"input_1\":{\"connections\":[{\"node\":\"6f93bcf6-cb76-4609-8828-1af3262779bb\",\"input\":\"output_1\"}]}},\"outputs\":{\"output_1\":{\"connections\":[]}},\"pos_x\":862,\"pos_y\":279}}}}}",
	"settings": {
		"blockDelay": 0,
		"debugMode": false,
		"defaultColumnName": "column",
		"executedBlockOnWeb": false,
		"inputAutocomplete": true,
		"insertDefaultColumn": true,
		"onError": "stop-workflow",
		"restartTimes": 3,
		"reuseLastState": false,
		"saveLog": true
	},
	"globalData": "[{ \"key\": \"value\" }]",
	"description": "",
	"includedWorkflows": {}
}`

**Comment by Kholid060** [comment]
Try to click the save button when editing the workflow 
![firefox_1OlWycwaU0](https://user-images.githubusercontent.com/22908993/189834567-3d2d37e2-22fa-460e-8f84-fbe342fd170f.png)

**Comment by q629988171** [comment]
> Try to click the save button when editing the workflow ![firefox_1OlWycwaU0](https://user-images.githubusercontent.com/22908993/189834567-3d2d37e2-22fa-460e-8f84-fbe342fd170f.png)

It doesn't work for me means.

**Comment by Kholid060** [comment]
Can you show the log of the workflow? Because it's working when I test it
![image](https://user-images.githubusercontent.com/22908993/189835901-ba4d9e2a-f6fd-4610-bd79-2466440e87b6.png)

**Comment by q629988171** [comment]
> Can you show the log of the workflow? Because it's working when I test it ![image](https://user-images.githubusercontent.com/22908993/189835901-ba4d9e2a-f6fd-4610-bd79-2466440e87b6.png)

it's work. The first time, you need to manually click the refresh button when you restart computer or reinstall Firefox.
![firefox 触发刷新](https://user-images.githubusercontent.com/2260447/189841584-464332aa-1f5a-4bc7-9631-5460287eee5e.png)
