### ISSUE TITLE
Workflow include packages not working from second loop

### ISSUE THREAD

**Issue by haikbvn** [AutomaApp/automa#791]
**Describe the bug**
Workflow include packages not working from second loop.

Everything goes perfectly in the first loop, but from the second loop only first package work, the output is on the last package, then the loop continues on the part where there is no package.

Sorry, my english is not good :(

**Screenshots**
https://vimeo.com/749660933

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows 11]
 - Browser: [e.g. Google Chrome]
 - Extension Version: [e.g. v1.19.0]

**Comment by Kholid060** [comment]
Have you tried to reconnect the block, and check the input and output of the package.

**Comment by haikbvn** [comment]
> Have you tried to reconnect the block, and check the input and output of the package.

I tried to do that. If not Set package as block, all loop will work.

Here is my workflow code.
https://automa.site/workflow/eYQWaMjVbMLJ8O-L6145D

**Comment by Kholid060** [comment]
> > Have you tried to reconnect the block, and check the input and output of the package.
> 
> I tried to do that. If not Set package as block, all loop will work.
> 
> **Here is my workflow code:** https://automa.site/workflow/eYQWaMjVbMLJ8O-L6145D
> 
> **Package use in workflow:** ![2022-09-15](https://user-images.githubusercontent.com/1848623/190347125-3b8655c4-4a16-4162-804c-0595a4aa2beb.png) ![2022-09-15 (1)](https://user-images.githubusercontent.com/1848623/190347144-fba843f3-0763-452e-9d23-758e2aadeeca.png)

I'll check it
