### ISSUE TITLE
How to use the checkbox in the form?

### ISSUE THREAD

**Issue by chenyunc123** [AutomaApp/automa#793]
How to use the checkbox in the form?

**Comment by Kholid060** [comment]
You only need to input the selector of the checkbox, you can set whether the checkbox is checked or not in the "Selected" option.

![chrome_fZ13SYyBwp](https://user-images.githubusercontent.com/22908993/190626208-6cc1605c-b8db-4124-89ac-0ae6bb6c4945.png)
