### ISSUE TITLE
webhook host const 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#794]
![image](https://user-images.githubusercontent.com/20383505/190634005-435c4d56-ec08-422d-8c6f-a82d39fd4859.png)
http webhook block;
target : I want to set hostserver  as const variable 
how to modify soure code Automa 
I try 
![image](https://user-images.githubusercontent.com/20383505/190634277-fa33d4a6-c259-4b52-8295-c57dcbc79c6b.png)
![image](https://user-images.githubusercontent.com/20383505/190634365-9dda0e17-cf26-4dab-b0ee-75c0516f43a4.png)
but no effect

**Comment by Kholid060** [comment]
Open the `src/utils/shared.js` file, and find the `webhook` property in the `tasks` variable. Input the HTTP request URL in the `url` property, see the below image.
![sublime_text_uv9aYdK6x4](https://user-images.githubusercontent.com/22908993/190634829-eefb631f-0826-49ed-bf01-2c822f76e4d4.png)

And in the `EditWebhook.vue` file, add a `readonly` attribute.
![image](https://user-images.githubusercontent.com/22908993/190635348-e81411b8-95ed-4a38-8acc-b50b4aa4df24.png)

**Comment by whwh656** [comment]
thanks
