### ISSUE TITLE
debug source code 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#796]
Now i modifysource code and i want to know if it can works,  but I don't know how to debug source code
now i  am usually save source code    and then yarn build and yarn build:zip and install the zip package to chrome 
Is it possible not to install zip in chrome , i can debug in vscode

**Comment by Kholid060** [comment]
You can run the `yarn dev` script and then drag and drop the `build` folder into the `chrome://extension` page.

**Comment by whwh656** [comment]
thanks
