### ISSUE TITLE
source code 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#797]
source code : in src 
1 what is the relationship the file of  workers.js and engine.js  
2 I want to know how one  workflow is  work,  What important files  in source code  I need to focus on ？

**Comment by Kholid060** [comment]
The engine is used to manage the state and data of the workflow that is currently running. And the worker is for executing the blocks inside the workflow. When the workflow starts running, the engine creates a worker to execute a block from the trigger block

https://github.com/AutomaApp/automa/blob/82a14512edff2a2e3111f22ead670b189f4432da/src/background/workflowEngine/engine.js#L239

And if the workflow branches like shown in the image below, the engine will create a new worker to execute blocks from that branch.
![chrome_OAE7rXtAdv](https://user-images.githubusercontent.com/22908993/191146437-4763f5e0-b319-41cf-b672-aef9257fc2a5.png)

**Comment by whwh656** [comment]
THANKS
