### ISSUE TITLE
can't not click element in iframe

### ISSUE THREAD

**Issue by xjfnet** [AutomaApp/automa#812]
![image](https://user-images.githubusercontent.com/4667005/193172595-64458f10-0746-4f1b-9f0f-f63a2b5d0c95.png)

![image](https://user-images.githubusercontent.com/4667005/193172650-692e8ef6-4241-41b4-876d-528f5e288bf1.png)

i want to click a `div` in the iframe, not `an Iframe element`

**Comment by xjfnet** [comment]
yes, have a look at the screenshot above.

**Comment by Kholid060** [comment]
Try to change the element selector to this format `iframe-selector |> div-selector`

**Comment by xjfnet** [comment]
Can't find an Iframe element with "iframe#MainFrame iframe#slt_HomePage_1_CC div#gvPeace_cell0_38_btnPublish_0_CD" selector.

**Comment by xjfnet** [comment]
i have change the element selector to "iframe#MainFrame |> iframe#slt_HomePage_1_CC |> div#gvPeace_cell0_38_btnPublish_0_CD" and change "Click Element" to "GetText", but workflow keep running will not finish.

![image](https://user-images.githubusercontent.com/4667005/193175630-10eb90b7-5429-43f0-a657-eb80cef6c10e.png)

**Comment by Kholid060** [comment]
Seem like you have a nested iframe, Automa currently doesn't support nested iframe

**Comment by marcelocecin** [comment]
hello, does it work with [frameset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frameset)?

**Comment by gaozjha** [comment]
> Seem like you have a nested iframe, Automa currently doesn't support nested iframe

when will you support

**Comment by gaozjha** [comment]
> i have change the element selector to "iframe#MainFrame |> iframe#slt_HomePage_1_CC |> div#gvPeace_cell0_38_btnPublish_0_CD" and change "Click Element" to "GetText", but workflow keep running will not finish.
> 
> ![image](https://user-images.githubusercontent.com/4667005/193175630-10eb90b7-5429-43f0-a657-eb80cef6c10e.png)
you can use javascript block  now ,
document.getElementById('MainFrame ').contentWindow.document.getElementById('MainFrame ').contentWindow.document.getElementById('gvPeace_cell0_38_btnPublish_0_CD').click()
