### ISSUE TITLE
The default CTRL+SHIFT+A shortcut interferes with Chrome Tab Search

### ISSUE THREAD

**Issue by joosniz** [AutomaApp/automa#816]
**Describe the bug**
The default CTRL + SHIFT + A shortcut overrides the Chrome Tab Search. As it's possible to change the Automa shortcut the issue isn't as critical, however, it seems that the Automa shortcut can get reset to default at seemingly random times.

**To Reproduce**
1. (Using a fresh install of Automa) Go to any non-browser page
2. Press 'Ctrl + Shift + A'
3. The Automa search window shows up instead of the Tab Search
4. Go to shortcut settings in Automa
5. Press the trash can to remove the shortcut
6. Go to a non-browser page and hit the same shortcut without reloading the page
7. Go to another page and hit the same shortcut. Tab Search should activate.

**Expected behavior**
The shortcut should open the Tab Search that is native to Chrome. The user should not have to remove it from the extension settings. Removing the shortcut should not require the user to reload all tabs to restore browser functionality, and the extension should never reset the shortcut so that the user must change/remove it again.

**Screenshots**
![Automa search box](https://user-images.githubusercontent.com/11315995/193933799-5201a175-61b0-4eeb-80dd-531f529783e0.png)
![Automa Chrome Tab Search](https://user-images.githubusercontent.com/11315995/193933796-384b5071-a1aa-42cc-945d-0d01d1c99556.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Google Chrome]
 - Extension Version: [1.21.1]

**Additional context**

**Comment by Kholid060** [comment]
You can change or remove the shortcut by going to settings > shortcuts > Automa shortcuts
![image](https://user-images.githubusercontent.com/22908993/193939935-c142e51e-15a1-4c3f-8e83-102af31d3234.png)

**Comment by mzaini30** [comment]
I think it better if change to Ctrl Shift e
