### ISSUE TITLE
workflow data structure explain

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#817]
questions1 
 I want to konw how  to define the data structure of workflow in source code ? I am confused

question 
2 when I import workflow How to parse the json file?

**Comment by whwh656** [comment]
> edges: [],

![image](https://user-images.githubusercontent.com/20383505/194685379-194120f7-159a-4551-bdeb-0b08a2792034.png)
what is nodes ,the properties of node， i am confused

**Comment by Kholid060** [comment]
> > edges: [],
> 
> ![image](https://user-images.githubusercontent.com/20383505/194685379-194120f7-159a-4551-bdeb-0b08a2792034.png) what is nodes ,the properties of node， i am confused

Nodes are the block you're seeing in the editor, and edges are what connects nodes to a map.
![chrome_3FERHVi2c1](https://user-images.githubusercontent.com/22908993/194755316-f2a94a01-5f5b-4be4-80bd-539248bcf436.png)

For that section, the data is coming from the flow library that Automa uses. The library is called [`vue-flow`](https://github.com/vue-flow), and you can learn more about it by opening its [documentation](https://vueflow.dev/guide/).

**Comment by whwh656** [comment]
greate ,thanks
