### ISSUE TITLE
Console of the background page shows 403 error

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#828]
Go to `edge://extensions/?id=infppggnoaenmfagbfknfkancpbljcca`
Click Inspect views: Background page.  /newtab.html

There are some errors in the console

e.g. 

```
api.automa.site/v1/me/check:1 
       Failed to load resource: the server responded with a status of 403 ()
```
﻿

**Comment by Kholid060** [comment]
You can ignore that error
