### ISSUE TITLE
Repeat Task - infinite loop

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#829]
**Describe the bug**
I have a loop that I set to 10 times, but it runs repeatedly, with the same step being run a few times in a row before moving on....

**To Reproduce**
Set a variable before the loop, e.g. myCount  set to 1
increment it by 1 in the loop.
Try to loop it 10 times.
See this flow:
![image](https://user-images.githubusercontent.com/608676/194711607-c5d3b858-c7d5-4e4e-9407-ca6ad5fb63f9.png)

**Expected behavior**
It should run ten times, once on each increment and not many times on each increment for more than 10 times.

**Screenshots**
Console log shows:

> .... CUT OUT ....
> heerrrre 16
> ​ heerrrre 16
> ​ heerrrre 16
> ​ heerrrre 16
> ​ heerrrre 16
> ​ heerrrre 16
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ​ heerrrre 25
> ,,,, ,,,,

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge 106.0.1370.37 (Official build) (64-bit) 
 - Extension Version: 1.21.1

Even if I simplify it, and just have an empty loop with a condition and an  increment, it runs to 17 times.
And if I simplify further to just this flow in the picture that follows, then it only runs the repeat task 1 time: 
![image](https://user-images.githubusercontent.com/608676/194711935-51a6b377-d45b-4834-a4ef-85f5eb373432.png)

**Comment by Kholid060** [comment]
While I trying to fix this bug, you can use the loop data block like the below image.
![image](https://user-images.githubusercontent.com/22908993/194808013-61c1ba28-aeca-47e7-a833-3a30a3f749a4.png)

**Comment by jddcef** [comment]
> And do you have parallel blocks inside the workflow?
No, just single outs for everything....
Here's the gist to make your testing easier https://gist.github.com/jddcef/ef063b2f7d541fb51c28b87ba898ec77

**Comment by jddcef** [comment]
Can't do a simple loop

> While I am trying to fix this bug, you can use the loop data block and select the "numbers" option. ![image](https://user-images.githubusercontent.com/22908993/194808013-61c1ba28-aeca-47e7-a833-3a30a3f749a4.png)

Can't do a simple loop either :( here's the flow: https://gist.github.com/jddcef/d37681b4ec1bf7a8c88d8ec932cd9563

**Comment by jddcef** [comment]
If I use a loop, and there is a split path in the loop, it repeats way too many times...
Known bug?

**Comment by Kholid060** [comment]
It's expected to prevent it, use the Wait connections block and enable the "Only continue specific flow" option.
![image](https://user-images.githubusercontent.com/22908993/197143648-65b35f1d-d35b-47e4-8178-2c9c1137f153.png)
