### ISSUE TITLE
Javascript block not being executed...

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#845]
This simple flow https://gist.github.com/jddcef/8dae5a88dc0e974793358474a4e0610e

does not execute the Javascript block, but it does the notification fine. and they are siblings.

**Comment by Kholid060** [comment]
Use the new tab block or active block before using the javascript block.

**Comment by jddcef** [comment]
I see, so could the javascript block's not show like a red outline or warning or icon on it to say "this won't be executed without an active tab preceding it"? So that users don't get suprised?

Could you not add an option to the switch tab block that says, "prefer to use the current tab", because it switches to another tab if I have duplicate tabs that match the url open...

**Comment by Kholid060** [comment]
> I see, so could the javascript block's not show like a red outline or warning or icon on it to say "this won't be executed without an active tab preceding it"? So that users don't get suprised?

Sure, I'll add it in the next update.

> Could you not add an option to the switch tab block that says, "prefer to use the current tab", because it switches to another tab if I have duplicate tabs that match the url open...

If you create a new tab using the new tab block, you can add a [query string](https://en.wikipedia.org/wiki/Query_string) in the URL to differentiate the browser tabs. For example, instead of writing `https://google.com` as the URL of the new tab block, you can write it like `https://google.com?useThisTab=true`. And in the switch tab block, write the match pattern with the query string `https://google.com/*?useThisTab=true`

**Comment by jddcef** [comment]
THanks.

So, why can't there be an option to say, if there are multiple matches of tabs, and the current tab is also a match just like the others, then use the current tab as one of the "random choices"?

**Comment by jddcef** [comment]
fixed, new version will give an error, great.

> So, why can't there be an option to say, if there are multiple matches of tabs, and the current tab is also a match just like the others, then use the current tab as one of the "random choices"?

I still think this is how it should work, current tab as priority over other random tabs.

**Comment by Kholid060** [comment]
I'll consider adding it

**Comment by jddcef** [comment]
Also, could Active Tab block also have a block settings? So that on error, I can switch to another tab perhaps?

**Comment by jddcef** [comment]
Also, could Active Tab block also have a block settings? So that on error, I can switch to another tab perhaps?

**Comment by jddcef** [comment]
my workaround is this:  a switch tab which falls back to an active tab on failure.

![image](https://user-images.githubusercontent.com/608676/197489519-e4b74e8e-5f6d-41ff-a27b-8a48a5d095b5.png)
