### ISSUE TITLE
 Sub workflow block errors : Can't find an element with "" selector.

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#848]
If I run a workflow block, it will say : 
`Can't find an element with "" selector.` on that block.
But the actual message I think is it can't find a certain selector in the workflow flow itself, but the message seems to get lost on its way up

**Comment by Kholid060** [comment]
On which block that error happened?

**Comment by jddcef** [comment]
> On which block that error happened?

On the workflow block

**Comment by Kholid060** [comment]
If you're using the execute workflow block you can click this button to see where the error is
![chrome_RnifKHxK40](https://user-images.githubusercontent.com/22908993/195807593-e2bd397b-5f7c-4dbe-8321-d2b74b909df2.png)
![image](https://user-images.githubusercontent.com/22908993/195807633-78a4c558-4e7e-4620-8769-fe0dc6691543.png)

**Comment by jddcef** [comment]
Will close until I get energy for it again
