### ISSUE TITLE
When import whole backup, some flows have no name or don't ever get imported 

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#849]
Importing individual workflows seems to work better than the bulk backup import. 

![Screenshot_20221014-103204367](https://user-images.githubusercontent.com/608676/195801796-fc9a6a47-ac4f-4e37-bb58-e16e91877425.jpg)

Ok, I am using Kiwi Browser on Android, which can run the automa extension quite well. So I know it won't be completely compatible for some cases, but so far so good.

**Comment by Kholid060** [comment]
Are you using the local backup or the cloud?

**Comment by jddcef** [comment]
Local

**Comment by marcelocecin** [comment]
what device configuration can you run on android?
