### ISSUE TITLE
http request blcok 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#850]
automa:1.21.3
url : https://v0.yiketianqi.com/api?unescape=1&version=v91&appid=43656176&appsecret=I42og6Lm&ext=&cityid=101020100
method :GET 
Response :json
![image](https://user-images.githubusercontent.com/20383505/195841078-29cde72d-eb21-46da-b074-7f3489113543.png)

![image](https://user-images.githubusercontent.com/20383505/195840864-eba3f38d-5ef0-411a-8524-ab80a0ca668e.png)

![image](https://user-images.githubusercontent.com/20383505/195840983-59cbbb1f-b010-4f8f-851a-714dbcc061a1.png)

how get tge value key:wea ?
I try 
data[0].wea
data[0].to.wea

**Comment by Kholid060** [comment]
Use the dot notation data.0.wea
