### ISSUE TITLE
I would like to enter empty string into cell in Sheets

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#859]
If I try insert something like 
`[["Code", "ParentCode","SrcUrl"],  ["{{ variables@codeIn}}", "", "{{ variables@urlIn}}"]]` it fails with:

> [body] "values[1][1]" does not match any of the allowed types

but if put an empty space, then it works 
`[["Code", "ParentCode","SrcUrl"],  ["{{ variables@codeIn}}", " ", "{{ variables@urlIn}}"]]`

Strange that can't enter an empty cell, or just not write anything

**Comment by Kholid060** [comment]
It's because I don't think inputting an empty string is allowed.

**Comment by jddcef** [comment]
> It's because I don't think inputting an empty string is allowed.

That would be weird to have to force spaces...

**Comment by jddcef** [comment]
It is allowed: 

> When updating, values with no data are skipped. To clear data, use an empty string ("").
from https://developers.google.com/sheets/api/guides/values
