### ISSUE TITLE
insert data add file type of xlsx

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#860]
![image](https://user-images.githubusercontent.com/20383505/196123127-973f762e-658e-4885-9dc5-1f91d6f339f3.png)

![image](https://user-images.githubusercontent.com/20383505/196123067-0cbc0335-49da-4da0-aac7-de42eb246f78.png)

**Comment by Kholid060** [comment]
Automa doesn't support importing an xlsx type file. You can convert it into CSV first before importing it into Automa.

**Comment by whwh656** [comment]
thanks
