### ISSUE TITLE
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#861]
Updated to 12.1.4 and some workflows aren't working. 

It's a workflow that works as  control panel (button overlays over a webpage)
It accesses current url and creates elements.

contains something like:
`
{"name":"automa-blocks","data":{"nodes":[{"computedPosition":{"x":-256.3076923076924,"y":19.84615384615382,"z":1000},"data":{"activeInInput":false,"contextMenuName":"","contextTypes":[],"date":"","days":[],"delay":5,"description":"","disableBlock":false,"interval":60,"isUrlRegex":false,"observeElement":{"baseElOptions":{"attributeFilter":[],"attributes":false,"characterData":false,"childList":true,"subtree":false},"baseSelector":"","matchPattern":"","selector":"","targetOptions":{"attributeFilter":[],"attributes":false,"characterData":false,"childList":true,"subtree":false}},"parameters":[],"shortcut":"","time":"00:00","triggers":[{"data":{"activeInInput":false,"contextMenuName":"","contextTypes":[],"date":"","days":[],"delay":5,"description":"","disableBlock":false,"interval":60,"isUrlRegex":false,"observeElement":{"baseElOptions":{"attributeFilter":[],"attributes":false,"characterData":false,"childList":true,"subtree":false},"baseSelector":"","matchPattern":"","selector":"","targetOptions":{"attributeFilter":[],"attributes":false,"characterData":false,"childList":true,"subtree":false}},"parameters":[],"shortcut":"","time":"00:00","type":"manual","url":""},"id":"cphx_","type":"manual"},{"data":{"isUrlRegex":false,"url":"https://www.google.co.za/"},"id":"9tTGA","type":"visit-web"},{"data":{"isUrlRegex":false,"url":"https://twitter.com/"},"id":"_WeGa","type":"visit-web"}],"type":"manual","url":""},"dimensions":{"width":192,"height":72},"handleBounds":{"source":[{"id":"O_35SaStMu3BdI_xXqyoC-output-1","position":"right","x":195.97666422526044,"y":27.978515625,"width":16,"height":16}]},"id":"O_35SaStMu3BdI_xXqyoC","label":"trigger","position":{"x":-256.3076923076924,"y":19.84615384615382},"selected":true,"type":"BlockBasic"},{"computedPosition":{"x":399.23076923076917,"y":-6.15384615384616,"z":1000},"data":{"conditions":[{"conditions":[{"conditions":[{"id":"dmcjCHxiEls6TNKPEHK8B","items":[{"category":"value","data":{"value":"{{variables@getTabUrl}}"},"id":"4vIlZMrnI36YVABaeannF","type":"value"},{"category":"compare","id":"rkOwaez5mf1LJXNs1tbw4","type":"cnt"},{"category":"value","data":{"value":"twitter.com/"},"id":"J7vQdRfg0rWY8WSMI_EGq","type":"value"}]}],"id":"AB3_RYpRS0TAtjmFDJnF-"}],"id":"MZARku9kLPYdAu49A1Kri","name":"twitter.com"}],"description":"","disableBlock":false,"retryConditions":false,"retryCount":10,"retryTimeout":1000},"dimensions":{"width":256,"height":157},"handleBounds":{"source":[{"id":"g0a2deh-output-MZARku9kLPYdAu49A1Kri","position":"right","x":260.9765625,"y":81.142578125,"width":16,"height":16},{"id":"g0a2deh-output-fallback","position":"right","x":259.9802652994792,"y":123.09572855631511,"width":16,"height":16}],"target":[{"id":"g0a2deh-input-1","position":"left","x":-19.980672200520836,"y":70.537109375,"width":16,"height":16}]},"id":"g0a2deh","label":"conditions","position":{"x":399.23076923076917,"y":-6.15384615384616},"selected":true,"type":"BlockConditions"},{"computedPosition":{"x":75.38461538461536,"y":0.7692307692307665,"z":1000},"data":{"assignVariable":true,"dataColumn":"","description":"","disableBlock":false,"saveData":false,"type":"active-tab","variableName":"getTabUrl"},"dimensions":{"width":192,"height":72},"handleBounds":{"source":[{"id":"lj9ty1q-output-1","position":"right","x":195.9765625,"y":27.978515625,"width":16,"height":16}],"target":[{"id":"lj9ty1q-input-1","position":"left","x":-19.98046875,"y":27.978515625,"width":16,"height":16}]},"id":"lj9ty1q","label":"tab-url","position":{"x":75.38461538461536,"y":0.7692307692307665},"selected":true,"type":"BlockBasic"},{"computedPosition":{"x":862.6153846153851,"y":-66.30769230769232,"z":1000},"data":{"css":"#el-automa-container {\n  position: fixed;\n  right: 20px;\n  bottom: 10px;\n  display: flex;\n  align-items: center;\n  padding: 10px 13px;\n  z-index: 9999999999;\n           \n  background-color: white;\n  color: black !important;\n}\n\n#el-automa-container button {\n  padding: 1px 4px;\n  cursor: pointer;\nwhite-space: normal;\n      max-width: 200px;\n }\n\n","description":"","disableBlock":false,"findBy":"cssSelector","html":"<div id=\"el-automa-container\">\n  \n</div>","insertAt":"after","javascript":"const buttons = [\n\n\n{ name: \"T.copyCode&Url,G.newRowSheet\", workflowId: \"eObCutobUPddmw5UKaSkI\" },\n{ name: \"Tw.code&id2clip=successfulBetConfirmDIalogue\", workflowId: \"qTkL0CIYdeAeJWyu20A75\" },\n//{ name: \"\", workflowId: \"\" },\n  \n // { name: 'Workflow 1', workflowId: '07sXp1axY5mU5PPRdOJtf' },\n // { name: 'Workflow 2', workflowId: '' },\n];\n\nconst container = document.querySelector('#el-automa-container');\n\nbuttons.forEach((button) => {\n  const buttonEl = document.createElement('button');\n  buttonEl.textContent = button.name;\n  \n  buttonEl.addEventListener('click', () => {\n    automaExecWorkflow({ id: button.workflowId });\n  });\n\n  container.appendChild(buttonEl);\n});\n","preloadScripts":[],"runBeforeLoad":false,"selector":"body","waitForSelector":false,"waitSelectorTimeout":5000},"dimensions":{"width":192,"height":72},"handleBounds":{"source":[{"id":"ebki1xl-output-1","position":"right","x":195.97635904947919,"y":27.978528340657554,"width":16,"height":16}],"target":[{"id":"ebki1xl-input-1","position":"left","x":-19.98046875,"y":27.978528340657554,"width":16,"height":16}]},"id":"ebki1xl","label":"create-element","position":{"x":862.6153846153851,"y":-66.30769230769232},"selected":true,"type":"BlockBasic"}],"edges":[]}}`

**Comment by Kholid060** [comment]
What browser are you using?

**Comment by jddcef** [comment]
Edge

**Comment by Kholid060** [comment]
Seems like this error occurs when you select "Strict" in the tracking prevention setting.

![image](https://user-images.githubusercontent.com/22908993/196575771-02e6d7fb-cb42-405a-a227-4d6274b64051.png)

**Comment by jddcef** [comment]
It started working again after update today to version  1.21.5
(do you have to use 3 sections in the version number? it makes it hard to remember the version, 2 would be enough I'm sure, like 1.22, 1.23, 1.24 etc.. won't really reach the end of that)

**Comment by Kholid060** [comment]
> (do you have to use 3 sections in the version number? it makes it hard to remember the version, 2 would be enough I'm sure, like 1.22, 1.23, 1.24 etc.. won't really reach the end of that)

I'm not using 2-number in the version because I'm following [Semantic Versioning](https://semver.org/).
