### ISSUE TITLE
Wait for Page Load

### ISSUE THREAD

**Issue by Naatan** [AutomaApp/automa#865]
**Is your feature request related to a problem? Please describe.**

I'm trying to write an automation that includes clicking links and navigating to other pages, and I cannot find a way to wait for the next page to load before looking for the next link to click.

**Describe the solution you'd like**

Some way of delaying the next action until the current tab has finished loading.

**Describe alternatives you've considered**

I've tried utilizing the while loop to wait for an element to be available, but the subsequent click action on the very same selector would fail saying it could not find it.

**Additional context**

**Comment by Naatan** [comment]
No, same tab.

**Comment by jddcef** [comment]
There is a Wait block for hardcoded time delays.

You have to figure out how the page flags that the page is done loading. Some use an overlay or something that pops up while they fetch the next page. You can look for that as a wait selector for example.

**Comment by Naatan** [comment]
That seems overkill for something that should be fairly simple. I understand some websites use single page apps so it's not that simple, but a page load itself sounds to me like a very common use case.

Effectively I'm asking for `window.onload`.

**Comment by Kholid060** [comment]
If you expect the page to reload after an action like clicking a link, try adding a delay block for 1-2 seconds before continuing to the next block. Automa will automatically wait for the page to fully load before executing the blocks.
Or you can use the browser event block
![image](https://user-images.githubusercontent.com/22908993/197067324-0c1a68a2-d7d5-4f78-8860-90cab0fdeebc.png)

**Comment by Naatan** [comment]
@Kholid060 Thank you, that looks like it addresses my use-case!
