### ISSUE TITLE
http request block

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#869]
1 different target url A and b
2 same request body 
3 can compare the difference  http request A: json response A   with request B  json response

**Comment by Kholid060** [comment]
I guess you can do it like this
1. Use the insert data block to insert data for the body into a variable 
![image](https://user-images.githubusercontent.com/22908993/196883845-330391a8-136b-494a-9284-6c081e56522b.png)
2.  Inside the body on each of the HTTP Request blocks, write `{{ variables@body }}`; And assign the response to a variable.
3.  To compare the response if it's the same, use the conditions block.
![image](https://user-images.githubusercontent.com/22908993/196884674-6adbf7c6-ed37-428e-a466-49c62466bfef.png)

![image](https://user-images.githubusercontent.com/22908993/196884747-1000be1f-ec59-4de5-ae52-36fd53be50cb.png)

**Comment by whwh656** [comment]
greate! thanks
