### ISSUE TITLE
Most parameter types are missing after upgrading from Automa v1.21.5 to v1.21.6

### ISSUE THREAD

**Issue by whalehub** [AutomaApp/automa#878]
### Describe the bug
After Chrome automatically updated Automa from v1.21.5 to v1.21.6, the parameter prompt block is missing almost all of the types which it had in the previous version.

### To Reproduce
1. Download and install [Automa v1.21.5](https://github.com/AutomaApp/automa/files/9841903/Automa.v1.21.5.crx.zip).
2. Create a new workflow.
3. Create a new parameter prompt block.
4. Note the number of available parameter types.
5. Download and install [Automa v1.21.6](https://github.com/AutomaApp/automa/files/9841901/Automa.v1.21.6.crx.zip).
6. Create a new workflow.
7. Create a new parameter prompt block.
8. Note that almost all of the parameter types from v1.21.5 are missing

### Expected behavior
None of the commits between these two versions mention this change, so it seems like the missing parameter types are the result of a bug rather than a deliberate decision to remove them.

### Screenshots
**Automa v1.21.5**

![screenshot](https://user-images.githubusercontent.com/44198148/197274219-11f80dd2-1756-4a5e-a46b-7ef82760f9c8.png)

**Automa v1.21.6**

![screenshot](https://user-images.githubusercontent.com/44198148/197274250-26467b05-ba16-4e98-a4d7-f276641d3517.png)

### Desktop
 - **OS:** Windows 10 21H2
 - **Browser:** Google Chrome v106
 - **Extension Version:** v1.21.5 and v1.21.6

### Additional context
N/A

**Comment by Kholid060** [comment]
It's expected, in version 1.21.5 I accidentally published the internal version of Automa.
