### ISSUE TITLE
Double execution of a single path

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#880]
This flow runs twice...

![image](https://user-images.githubusercontent.com/608676/197338284-487f9031-a554-4f61-8f9f-da2a14fe983d.png)

Logs show repetition:
![image](https://user-images.githubusercontent.com/608676/197338192-a8d502e9-86eb-498c-8ea6-c23441da26eb.png)

it definitely should not..

**Comment by Kholid060** [comment]
Try to remove the connection between the while loop block and the delay block.
![chrome_Wm4J3UJAK3](https://user-images.githubusercontent.com/22908993/197338397-caedea8e-cf4e-4f26-834d-e44d2e34c0f6.png)

**Comment by jddcef** [comment]
This also caused an issue I think: a double path with a disabled block, but I think it's the while loop, if the while loop gets executed 2 or 3 times, then the whole chain down the line will run 2 or 3 times....
Which is not how I understand the flow, which is not how a while loop should execute, because it has one output it should escape it once and not multiple times...
![image](https://user-images.githubusercontent.com/608676/197339327-19e6f711-3f85-4909-a1ec-3a403cad35d6.png)

**Comment by jddcef** [comment]
> Try to remove the connection between the while loop block and the delay block, and then connect them.

Do you mean I must do it once off just to fix the flow? There's no way to rearrange the two blocks order of input and output other than the way they are though?

Anyway, I'm trying to wait until a modal overlay loading div disappears to indicate the page is finish, so I put a while loop and a delay...
Is there any other block that doesn't have this bug of repeating the flow for each loop iteration?

**Comment by jddcef** [comment]
I found something that works: 
![image](https://user-images.githubusercontent.com/608676/197340146-75ff57e5-ee59-40d4-8176-6013a042027b.png)

A loop data, going from 1 to 100 or whatever is a lot, and then repeat it. The loop data block doesn't escape more than once which is good. 
But the bug still remains with the while loop.

**Comment by Kholid060** [comment]
> This also caused an issue I think: a double path with a disabled block, but I think it's the while loop, if the while loop gets executed 2 or 3 times, then the whole chain down the line will run 2 or 3 times... Which is not how I understand the flow, which is not how a while loop should execute, because it has one output it should escape it once and not multiple times...
> 
> ![image](https://user-images.githubusercontent.com/608676/197339399-d2624207-6222-4468-be6b-ac4e1fada00b.png)

When you have double or multiple paths in a workflow, Automa will create a new "worker" for each new path even though the blocks are disabled. The job of the worker is to execute blocks inside the workflow. 

And when you connect those multiple paths into a single block like in the image you provide, the block executes multiple times because of those workers. And to prevent that, use the wait connection block like in this discussion https://github.com/AutomaApp/automa/issues/829#issuecomment-1286599429.

![chrome_TeuDKOteH6](https://user-images.githubusercontent.com/22908993/197340207-8bfbdd40-a0a3-40f2-ad09-829a3b3939ea.png)

**Comment by jddcef** [comment]
Oh yes I understand.
So, I thought of a solution..
THe problem is the visual representation of the block, all the flows go into ONE input, which misleads about the multiple executions. 
So the solution is, for every input that comes in, the block should draw another circle, so that there are as many circles as there are inputs. This would make a person realise that yes, this might come in here twice rather than once...
e.g. this is what I propose should happen when dragging two seperate inputs onto a block:

![image](https://user-images.githubusercontent.com/608676/197383339-67a81134-d905-4c5d-90dd-988dd459c5c4.png)
I really think this is the right way to represent it.

**Comment by jddcef** [comment]
OK, I found a real problem case, there's no duplicate paths, but I get a part executing twice...:

![image](https://user-images.githubusercontent.com/608676/197565903-32f6b57c-1c69-4dde-a00f-f449d5cdfb74.png)
It's on a quite a big flow: but it only happens here: 
![image](https://user-images.githubusercontent.com/608676/197566015-0f0e4f80-911f-41a8-88a1-323e5918a8e8.png)

Could an executed workflow block ever "Exit" itself twice? and cause a double run on a single line output?

To help debug this, Could Automa detect if there are possible duplicate flows somewhere and just log it somewhere?  even if it's in console or on the log page as some sort of "possible issues" listing? Like lint warnings almost.
Or, could automata show the stack trace in the logs somehow?

**Comment by jddcef** [comment]
> OK, I found a real problem case, there's no duplicate paths, but I get a part executing twice...:

OK, believe it or not, there was two lines going between the same two blocks, I just tried to randomly delete the link between them, and I had to do it twice! So somehow it's possible to have the  same link between the two blocks. 
Which means that my suggestion of visually showing each incoming link with its own dot would have solved this problem...  
that was a crazy bug

**Comment by jddcef** [comment]
> ![image](https://user-images.githubusercontent.com/608676/197383339-67a81134-d905-4c5d-90dd-988dd459c5c4.png) I really think this is the right way to represent it.


Thanks for all the fixes.
I still believe this will be the way to present multiple inputs going into one block, as they are able to be executed twice, especially if the upstream flow has no conditionals.

**Comment by Kholid060** [comment]
That's actually a good idea, I'll try implement it in the future update
