### ISSUE TITLE
Skip Block On Error

### ISSUE THREAD

**Issue by cueup** [AutomaApp/automa#886]
Hey all,

Has anyone managed to create a block or package that can skip to the next block on error, I don't want the workflow to stop on error but continue to the next block. 

Thanks

**Comment by Kholid060** [comment]
Open the block settings, and in the "On error" tab, select "Continue flow";

![image](https://user-images.githubusercontent.com/22908993/197422567-f76ca5e0-6883-45d3-9e3e-bffaf48a4016.png)

**Comment by cueup** [comment]
@Kholid060 I found this and came back to close this but saw you got here before me, thanks for the quick response.
