### ISSUE TITLE
How can I move the screen using mouse when trigger an event?

### ISSUE THREAD

**Issue by hyperaktiv** [AutomaApp/automa#895]
I use Trigger Event, after that, I use some functions of mouse but it not work.
Is there any help me to I can move the screen to specific (x,y) position?

Thanks a lot.

**Comment by Kholid060** [comment]
Try enable the "Debug mode" in the block settings of the Trigger Event block

![image](https://user-images.githubusercontent.com/22908993/197982535-fb7e90e7-41ec-434e-856a-a446965fb285.png)

**Comment by hyperaktiv** [comment]
thanks very much, It works, and I understand it.
Is this Extension bypass the captchar?

**Comment by Kholid060** [comment]
> Is this Extension bypass the captchar?

No, it can't bypass the captcha

**Comment by hyperaktiv** [comment]
Oh, very good, thank you so much.
Let me ask that how can I action to register or login to email account by google/oauth pop-up? How can I change or active the pop-up and take the action on the google-oauth pop-up?

**Comment by Kholid060** [comment]
> Oh, very good, thank you so much. Let me ask that how can I action to register or login to email account by google/oauth pop-up? How can I change or active the pop-up and take the action on the google-oauth pop-up?

Use the [Switch Tab block](https://docs.automa.site/blocks/switch-tab.html#switch-tab-block), and write the [Match pattern](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#examples)  based on the URL of the popup. For example,

![chrome_qOj8lTPkz0](https://user-images.githubusercontent.com/22908993/198266415-3c411f45-5bef-44a8-abff-3c1ed01dcddc.png)

The Match patterns would be `https://accounts.google.com/o/oauth2/auth/*`
