### ISSUE TITLE
I would like a flow to pause if browser goes offline or no internet connection

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#898]
I would like my flow to have a setting that says, pause this flow if internet goes offline, and then another that says resume if internet restored.

Because most flows will just crash when there's no internet as the actions won't work, it would be graceful if it would wait until internet connectivity is restored.  Wifi can be dodgy at times.

**Comment by simtuzi1** [comment]
If you have long workflow for instance one with a while loops etc. You could try to use `Condition builder` 
Do a Code block with code something akin to this, it checks if your browser is online
`
if (navigator.onLine){
  return true
}
`
