### ISSUE TITLE
In v1.22 clicking the extension button in the browser opens a new window

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#906]
1.22 has now started to open a whole new window onto the Dashboard of AUtomata, instead of the popup that used to appear.

Which means I can't run a flow on a specific tab anymore, as it's not linked to the tab from which I launched automata anymore.

Pretty big problem.

Such a fundamental change in behaviour and functionality should be version 2.x.x if it's intentional.

Chrome and Edge.

**Comment by Kholid060** [comment]
> 1.22 has now started to open a whole new window onto the Dashboard of AUtomata, instead of the popup that used to appear.

I intended to bring back the popup in the next update. And you can still run the workflow on a specific tab, you only need to run the workflow from the dashboard.

https://user-images.githubusercontent.com/22908993/198541006-a329d85d-27b2-4c62-9872-3bdf4cf291f2.mp4

**Comment by jddcef** [comment]
Thanks brother, but I wish it worked that way. It's jumping to a different window with a different tab, definitely not the "Active tab" from which I launched it....

Can't it be a setting that I can switch off perhaps?

**Comment by Kholid060** [comment]
> Thanks brother, but I wish it worked that way. It's jumping to a different window with a different tab, definitely not the "Active tab" from which I launched it....
> 
> Can't it be a setting that I can switch off perhaps?

Currently there's no setting to switch it off, I guess wait for the next update.

**Comment by jddcef** [comment]
> > Thanks brother, but I wish it worked that way. It's jumping to a different window with a different tab, definitely not the "Active tab" from which I launched it....
> > Can't it be a setting that I can switch off perhaps?
> 
> Currently there's no setting to switch it off, I guess wait for the next update.

Ok, i will wait for that, then I can choose between popup or new window for the extension button action

**Comment by jddcef** [comment]
> > Thanks brother, but I wish it worked that way. It's jumping to a different window with a different tab, definitely not the "Active tab" from which I launched it....
> > Can't it be a setting that I can switch off perhaps?
> 
> Currently there's no setting to switch it off, I guess wait for the next update.

Ok, i will wait for that, then I can choose between popup or new window for the extension button action

**Comment by fmbcccc** [comment]
a new window is not that bad. 

the really bad thing is that we cannot close the window, or else all automa tasks are canceled.

in this version, schedule tasks always raise errors. they worked fine before.

automa is a wonderful application. but look this upgrade is a bit too hurry.

**Comment by jddcef** [comment]
I'm getting to like the new window, as it opens much faster than the popup actually, well beause it stays open it doesn't have to be recreated each time.
I didn't know they get cancelled though.

Yeah, it's ok to change things, but then the spirit of the numbering convention should be adhered to: a big change like this should change the it to version 2. so that I'm not shocked when everything is completely different.

Anyway, these things don't take away from the overall greatness of Automata.

**Comment by jddcef** [comment]
I just saw the blog post about the changes, and yeah, it definitely should have bumped the version up to 2.x.x because it's a fundamental change, and things won't work in some scripts at all, like the blocking of javascript on some sites etc. 
If semantic versioning is really being used, this should be indicated. It's definitely considered as "breaking changes" to the api.

**Comment by fmbcccc** [comment]
> 

yep. the current upgrade changes too much. and i still don't know how to fix the workflows to make them work again

**Comment by jddcef** [comment]
To be honest, such a big change, that breaks everything and basically blocks all scripts from accessing some sites because of manifest V3, should actually become a whole new extension. The previous Automa version should be maintained for the next 2 years until manifest v3 is compulsory. In which time users of Automata can figure out workarounds to convert their flows to the entirely new restrictions.

Automata 1 should continue unbroken, and a Automata Beta or Automata Something 2 should be started that is severely restricted, but one can build from scratch. Because now to go back and debug every single flow to check if every path works, is not easy, nor necessary for a few years.

Because now you can't have every single previously made flow suddenly have new restrictions which aren't even alerted in the flows.

**Comment by Fhaohaizi** [comment]
> To be honest, such a big change, that breaks everything and basically blocks all scripts from accessing some sites because of manifest V3, should actually become a whole new extension. The previous Automa version should be maintained for the next 2 years until manifest v3 is compulsory. In which time users of Automata can figure out workarounds to convert their flows to the entirely new restrictions.
> 
> 老实说，这么大的变化，打破了一切，基本上阻止了所有脚本访问一些站点，因为清单 V3，实际上应该成为一个全新的扩展。以前的自动化版本应该维护2年，直到清单 v3是强制性的。在这段时间内，Automata 的用户可以找到变通方法，将他们的流转换为全新的限制。
> 
> Automata 1 should continue unbroken, and a Automata Beta or Automata Something 2 should be started that is severely restricted, but one can build from scratch. Because now to go back and debug every single flow to check if every path works, is not easy, nor necessary for a few years.
> 
> 自动机1应该继续不间断，自动机测试版或自动机某些东西2应该启动，这是严格限制，但一个可以从头开始。因为现在回头调试每一个流程来检查每一条路径是否正常工作，这并不容易，也不是几年就必须的。
> 
> Because now you can't have every single previously made flow suddenly have new restrictions which aren't even alerted in the flows.
> 
> 因为现在你不能让每一个以前制作的流突然有新的限制，甚至在流中都没有警告。

I have the same opinion.

**Comment by onecer** [comment]
> > 1.22 has now started to open a whole new window onto the Dashboard of AUtomata, instead of the popup that used to appear.
> 
> I intended to bring back the popup in the next update. And you can still run the workflow on a specific tab, you only need to run the workflow from the dashboard.
> 
>  active-tab.mp4

I need to reply to emails a lot of days. So I use automa to do those things.  just 2 clicks were done before, Now I need to click 3 times. and dashboard loading is always slow. in my case maybe it will take 3 secs to show up.

**Comment by Kholid060** [comment]
> I need to reply to emails a lot of days. So I use automa to do those things. just 2 clicks were done before, Now I need to click 3 times. and dashboard loading is always slow. in my case maybe it will take 3 secs to show up.

See https://github.com/AutomaApp/automa/issues/911#issuecomment-1298078880
