### ISSUE TITLE
add collect workflows

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#908]
![image](https://user-images.githubusercontent.com/20383505/198573402-7e3c4794-ac2c-44f2-ba55-90f27bf90551.png)

I hvae many workflows，but  i want to add function about   collect workflows, for example:  every workflow have a collect icon and i can click it ,  only display i collect workflow in the  first page

**Comment by jddcef** [comment]
You mean something groups or grouping workflows I guess

**Comment by whwh656** [comment]
yes,thanks you
