### ISSUE TITLE
The shortcut trigger will open the Automa window

### ISSUE THREAD

**Issue by mashidong** [AutomaApp/automa#911]
When using the new version, the shortcut trigger will open the Automa window, but I do not need this behavior. I think it is better to use the previous version. As a plug-in, it should be silent, and the window will be displayed when necessary, instead of popping up a new window every time the shortcut key is clicked!

**Comment by Kholid060** [comment]
In v1.23.0, you can set the workflow to run in the background in the [workflow settings](https://docs.automa.site/workflow/settings.html#workflow-execution), so the popup won't show up.

![image](https://user-images.githubusercontent.com/22908993/199171067-ca390485-1fe6-47e6-a546-50348f21661d.png)
