### ISSUE TITLE
How can I set up the chrome or browser permission for Automa?

### ISSUE THREAD

**Issue by hyperaktiv** [AutomaApp/automa#917]
I met this error while upload file function: "Could not establish connection to the active tab"

How can I fix this error for my case?

Thank you very much.

**Comment by Kholid060** [comment]
> I met this error while upload file function: "Could not establish connection to the active tab"
> 
> How can I fix this error for my case?
> 
> Thank you very much.

Try to reload the tab, if it still not working, restart your browser

**Comment by hyperaktiv** [comment]
![image](https://user-images.githubusercontent.com/44998665/199217508-4c55b02d-2e84-4152-8c90-02c10cbffce1.png)

I met this error while using upload file function with the file path is: "C:/Users/Admin/Downloads/test/2.mp4"

How can I fix this on my browser?

**Comment by Kholid060** [comment]
What browser do you use? And it's not working if you change the file path to another disk like `D:`?

**Comment by hyperaktiv** [comment]
I use chrome for run, and I use the data on the C: disk too.

can you work on it?

**Comment by hyperaktiv** [comment]
How limit of the file can Automa upload?

**Comment by Kholid060** [comment]
> How limit of the file can Automa upload?

It's 20MB if I'm not mistaken. What size of file are you trying to upload?

**Comment by hyperaktiv** [comment]
I upload video, its size are more than 20MB. Can I increase or change the limit of it in the code?

**Comment by Kholid060** [comment]
I'm afraid you can't increase the limit because it's from chrome itself, but you can try.

**Comment by hyperaktiv** [comment]
I don't think about the chrome itselft, cause example, when uploading to youtube, we can upload a video with Gigabytes, not jusst Megabytes.
I think it can be set in source code or It can be change. Do you code for that function?

**Comment by Kholid060** [comment]
> I don't think about the chrome itselft, cause example, when uploading to youtube, we can upload a video with Gigabytes, not jusst Megabytes.

I mean the file size limit that the extension is able to send to the page


> I think it can be set in source code or It can be change. Do you code for that function?

You can find it here

https://github.com/AutomaApp/automa/blob/main/src/content/blocksHandler/handlerUploadFile.js

Basically, when the engine is executed the upload file block, the above code will send a message to [the background](https://github.com/AutomaApp/automa/blob/main/src/background/index.js#L95) to fetch the file and then send it back.

**Comment by hyperaktiv** [comment]
Can you show me the code where it limit 20MB for upload file? I need it

**Comment by Kholid060** [comment]
> Can you show me the code where it limit 20MB for upload file? I need it

There is no code that limits the max file size to upload inside Automa. As I said, 20MB is the maximum file size an extension can send to the page.
