### ISSUE TITLE
How can Automa action the OS command line or run another desktop application?

### ISSUE THREAD

**Issue by hyperaktiv** [AutomaApp/automa#923]
In the flow of running Automa, I need to have action to call another application from desktop? Is there any feature or function or code to do that?

**Comment by Kholid060** [comment]
I don't think that's possible.

**Comment by hyperaktiv** [comment]
ok thank you, Automa is very good for our case

**Comment by hyperaktiv** [comment]
how can I turn off the auto update function of the Automa?

**Comment by JohnsonYuan** [comment]
web cannot interact with the desktop direct I think.

**Comment by hyperaktiv** [comment]
@JohnsonYuan yes, I see it, I found ways to get it with webhook from localhost.
Thanks you guys very much for creating the extensions and very pleased to reply the issues.
