### ISSUE TITLE
Single Page Applications support

### ISSUE THREAD

**Issue by marcelocecin** [AutomaApp/automa#926]
please consider including trigger support for single-page application (SPA)
https://en.wikipedia.org/wiki/Single-page_application

**Comment by marcelocecin** [comment]
Hi @Kholid060 how are you ? in version 1.23.4 issue still remains for [podio.com](https://podio.com/home). thanks.

**Comment by Kholid060** [comment]
Have you tried enabling the "Support SPA website" option in the "when visit a website" trigger?

![image](https://user-images.githubusercontent.com/22908993/203481529-d201bb88-6334-410a-a90a-f63e3addb7f8.png)

**Comment by marcelocecin** [comment]
it worked ! thanks a lot !
