### ISSUE TITLE
How to terminate the infinite workflow?

### ISSUE THREAD

**Issue by JohnsonYuan** [AutomaApp/automa#927]
I have a workflow in a while loop, and I want to stop this job manually but I cannot find how.
By the way, When I set the trigger block to interval trigger, I still cannot stop the work,

**Comment by mzaini30** [comment]
Using "workflow state" block. Choose "stop all workflow" example.

**Comment by mzaini30** [comment]
Or, you can use this workflow
https://www.automa.site/workflow/DcWXNNqTIkohd3vZaepMw
