### ISSUE TITLE
How to pass value between workflow and packages?

### ISSUE THREAD

**Issue by JohnsonYuan** [AutomaApp/automa#928]
I want to pass a value from workflow to package, and read a return value from package in workflow, how can I achieve this?

**Comment by mzaini30** [comment]
Using variables.

**Comment by mzaini30** [comment]
Example in my package
https://www.automa.site/packages/xdg-bjOjzI1DWF978MoVs

**Comment by hyperaktiv** [comment]
@mzaini30 what do you mean? I don't understand your support.
How can I pass or share the variable or table data between executive flow?

**Comment by hyperaktiv** [comment]
@JohnsonYuan have you had the solutions for your problem?

**Comment by Kholid060** [comment]
The package and the workflow are shared the same variables. Meaning that the package can access a variable that is created by the workflow and vice versa. So, if you want to pass a value from the package to the workflow, you can create a variable inside the package and access that variable inside your workflow.
