### ISSUE TITLE
invalid json type 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#933]
rendererror is type of array object 
i use JSON.stringify() to json text
i send http request  but is an invalid json type 
![image](https://user-images.githubusercontent.com/20383505/200472526-77004485-0b12-4081-9e38-aad595922456.png)

![image](https://user-images.githubusercontent.com/20383505/200472242-431fe788-bd3d-44e9-aaed-65cd61bc4c5f.png)

![image](https://user-images.githubusercontent.com/20383505/200472139-e3fd1976-2776-4668-bd53-5ddf630c6554.png)
![image](https://user-images.githubusercontent.com/20383505/200472173-a3155254-ddf8-4d07-a9e7-2bb746efc372.png)

![image](https://user-images.githubusercontent.com/20383505/200471991-8de6d6a3-7d1c-4362-9ae8-9ce6ff857480.png)

**Comment by Kholid060** [comment]
There might be a new line inside the `ccc` variable. To fix it, add an exclamation mark before writing the keyword, for example, 
```json
{
  "content": {{!prevBlockData@ccc}}
}
```

https://docs.automa.site/blocks/webhook.html#writing-expression-inside-the-body

**Comment by whwh656** [comment]
> ```json
> {{!prevBlockData@ccc}}
> ```
Automa 1.23.3
![image](https://user-images.githubusercontent.com/20383505/200488193-bb906624-50e7-49d8-9422-ef62e313cf80.png)
![image](https://user-images.githubusercontent.com/20383505/200488206-da3af800-517e-4fc7-b972-77b8e3e2503c.png)

I try datetype of array is not run 
![image](https://user-images.githubusercontent.com/20383505/200490024-474b5c0c-052f-46f9-a39c-aaedba53e82f.png)

I try thet doesn't work

but below  is run normally 
![image](https://user-images.githubusercontent.com/20383505/200488124-19d8d67e-91ad-4368-8954-6ffc48dd771c.png)

**Comment by Kholid060** [comment]
You don't actually need to stringify it if you want to input an object/array inside the HTTP Request body like
```json
{
  "content": {{ variables@$$rere }}
}
```
Or, if you still want to stringify it, you can stringify the whole payload inside the javascript block. For example,
```js
let ret1 = automaRefData('variables', 'rendererror')
automaSetVariable('ccc', JSON.stringify({
  content: ret1
}))
```

And inside the HTTP Request body

```
{{variables@ccc}}
```

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/200511171-08898910-6d12-439d-adf9-67841e08bb19.png)

![image](https://user-images.githubusercontent.com/20383505/200510803-a2c8f917-ca27-4252-9b7d-6143d7ed4742.png)

 element in arrary object  must user single quote can be run normally
