### ISSUE TITLE
click by clientx and clientY

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#955]
I want to click green dot by clientx,clientyand open a logo picture in new tab  by Automa

document.addEventListener('click', function(e) {
  console.log(
    'page: ' + e.pageX + ',' + e.pageY,
    'client: ' + e.clientX + ',' + e.clientY,
    'screen: ' + e.screenX + ',' + e.screenY)
}, false);

[clickclientxy.automa.txt](https://github.com/AutomaApp/automa/files/10038948/clickclientxy.automa.txt)
console output: page: 955,262 client: 955,262 screen: 955,365

![image](https://user-images.githubusercontent.com/20383505/202643363-6fb8a9d6-4978-4153-8391-1dc24f65e60c.png)
![image](https://user-images.githubusercontent.com/20383505/202644120-5d14c6a5-7409-43d5-98d5-dd996fc2c710.png)

but no effect  i am confused

**Comment by Kholid060** [comment]
You need to enable the "Debug mode" in the block settings of the Trigger Event block

**Comment by Kholid060** [comment]
If the "Debug mode" is not enabled, Automa will only emulate the "Click" event using JavaScript and dispatch that event on the element that matches the selector. It does not simulate the "Click" event based on coordinates if the "Debug mode" is not enabled.
