### ISSUE TITLE
Verify selector doesn't work propertly - "Element not found"

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#958]
I have a clear case where this html is on the page

`<button class="MuiButtonBase-root MuiTab-root MuiTab-textColorInherit MuiTab-fullWidth Mui-selected css-1hqheoo" tabindex="0" type="button" role="tab" aria-selected="true" id="full-width-tab-0" aria-controls="full-width-tabpanel-0">GK(0)<span class="MuiTouchRipple-root css-w0pj6f"></span></button>`

but the Verify element button on the click element block doesn't match the selector `#full-width-tab-0` , it pops up `Element not found`

**Comment by Kholid060** [comment]
But is it working when you running the workflow?

**Comment by jddcef** [comment]
Yes it works, just the verifier is bust
