### ISSUE TITLE
http body support variables 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#960]
http request 
body  {{}} is not support

format: 
text/plain
xxxx={{ globalData.key}}  is not work

**Comment by Kholid060** [comment]
It's working when I tested it, make sure the data you want to access inside `{{}}` exists.

**Comment by whwh656** [comment]
thanks

**Comment by whwh656** [comment]
> It's working when I tested it, make sure the data you want to access inside `{{}}` exists.


![image](https://user-images.githubusercontent.com/20383505/203264656-776969ce-4e17-4c5d-bf23-fe65ff27b100.png)

{{loopData.loopid.key}} is not work , but globalData is work

**Comment by Kholid060** [comment]
Can you show the log data of the workflow 

![chrome_ENqhsxWpTV](https://user-images.githubusercontent.com/22908993/203267784-400a3c01-1d34-4fb3-b674-0095a64293be.png)

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/203271200-248a3111-d55f-4fc2-9fd3-cec8a3f5045b.png)
![image](https://user-images.githubusercontent.com/20383505/203271337-01f0c2c2-c2a3-4975-a67d-45bdf83933d1.png)


i can't get loopdata

**Comment by Kholid060** [comment]
It's not working because you haven't used any Loop block like Loop data block or Loop elements block before the HTTP Request block

**Comment by whwh656** [comment]
> It's not working because you haven't used any Loop block like Loop data block or Loop elements block before the HTTP Request block
![image](https://user-images.githubusercontent.com/20383505/203275077-ebf0e9f9-b497-46c8-bddf-c1fcb17a2172.png)

**Comment by Kholid060** [comment]
You need to enable the Loop data block and Loop breakpoint so you can access the loop data. It works because you disable them.
