### ISSUE TITLE
Can automa be executed on a linux server？

### ISSUE THREAD

**Issue by a947684132** [AutomaApp/automa#962]
For example, I have built a workflow on the client, but I want to execute this workflow on my own server, is it possible?

**Comment by Kholid060** [comment]
Automa is a browser extension meaning that as long as a browser that Automa supported (Chrome & Firefox) is installed on your server, you can run the Automa workflow there.

**Comment by pathboot** [comment]
> Automa is a browser extension meaning that as long as a browser that Automa supported (Chrome & Firefox) is installed on your server, you can run the Automa workflow there.

hi bro salam
did i have ubuntu 20.04 lts
without gui so i use it from terminal
so i can start it automa on it ??
