### ISSUE TITLE
result 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#963]
loop 10 times  send 10 http request 
every http request have a response data 
how can i add 10 response data to one arry when loop end 
![image](https://user-images.githubusercontent.com/20383505/203306093-d51c65f5-d4c2-4428-afbb-a740ac86b4cd.png)
![image](https://user-images.githubusercontent.com/20383505/203305905-742a6a5f-96e5-4333-bc5e-389917eae40e.png)
![image](https://user-images.githubusercontent.com/20383505/203306008-1d655ecf-dd93-472b-81c6-b99b2e4ce6de.png)

I find that gloData no updata only have one value

**Comment by whwh656** [comment]
> ```js
> const data = automaRefData('variables', 'responseData') || [];
> const firstRow = automaRefData('variables', 'mix');
> 
> data.push(firstRow);
> 
> automaSetVariable('responseData', 'data');
> ```

![image](https://user-images.githubusercontent.com/20383505/203466478-40e00a23-081d-4ea6-a79b-9c2b3765ded7.png)

**Comment by Kholid060** [comment]
Try this
```js
const data = automaRefData('variables', 'responseData') || [];
const firstRow = automaRefData('variables', 'mix');

data.push(firstRow);

automaSetVariable('responseData', data);
```

**Comment by whwh656** [comment]
> Try this
> 
> ```js
> const data = automaRefData('variables', 'responseData') || [];
> const firstRow = automaRefData('variables', 'mix');
> 
> data.push(firstRow);
> 
> automaSetVariable('responseData', data);
> ```
![image](https://user-images.githubusercontent.com/20383505/203497046-355b924e-1489-4dea-967e-d95d327b0909.png)
![image](https://user-images.githubusercontent.com/20383505/203497076-018d3fe7-7786-43a4-aeaf-06bc7702e128.png)
[Uploading 查看密文11.automa.txt…]()

**Comment by Kholid060** [comment]
Can you reupload the workflow?

**Comment by whwh656** [comment]
> Can you reupload the workflow?

reload the workflow it works,thanks
I feel  Automa 1.23.3 performance is slower than v1.17.0 run a same workflow
