### ISSUE TITLE
mute execution workflow

### ISSUE THREAD

**Issue by simtuzi1** [AutomaApp/automa#964]
When I execute the workflow it keeps playing very annoying sniper kind of sound. Is there a way to mute the workflow?
My workflow opens a new window everytime.

**Comment by Kholid060** [comment]
It may be your notification sound, you can disable it by going to workflow settings, and disabling the "Workflow notification" option. And select the background option in the "Workflow Execution" if you don't want the workflow to open a new window every time it executes.

![image](https://user-images.githubusercontent.com/22908993/203495922-9a6bd598-4f25-4f59-b25f-b0b3365560bf.png)
