### ISSUE TITLE
After 1.22.0，JavaScript Block went wrong

### ISSUE THREAD

**Issue by LiXin-x** [AutomaApp/automa#971]
**Describe the bug**
After upgrading Automa from 1.21.0 to 1.22.0/1.24.0，Workflows that I created before and contains JavaScript block can't run successfully.

**To Reproduce**
1. new workflow, like below
![image](https://user-images.githubusercontent.com/27121050/204474620-fea87582-7068-4093-8168-835efc0b40d3.png)

2. add an URL in NEW TAB
3. add some code in JS BLOCK, set exec in Active Tab
4. JS Block exits with error
5. log:Error in invocation of scripting.executescript(scripting.ScriptInjection injection，
optional function callback) : Errorat parameter rinjection': Unexpected property:'world'.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 92
 - Extension Version: 1.22.0/1.24.0

**Additional context**
Workflow execution :Popup

**Comment by Kholid060** [comment]
Update your browser to the newest version

**Comment by LiXin-x** [comment]
> Update your browser to the newest version

the web app of my company don't support Chrome version higher than 92, is there anything I can do?

**Comment by LiXin-x** [comment]
And I just reported an issue that was fixed in automa 1.24.0

**Comment by Kholid060** [comment]
I guess you can install Automa which supports your browser version manually. You can do it by 
1. Download the zip file on the [Releases page](https://github.com/AutomaApp/automa/releases)
2. Open the `chrome://extensions` page and enable the "Developer mode" on the top right.
3. Drag & Drop the zip file to that page.

The v1.24.0 only supports chrome version 95 or newer

**Comment by LiXin-x** [comment]
Thanks for your answer. 🙏
