### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by chenyunc123** [AutomaApp/automa#981]
I created an http request in the JavaScript component and did not save the data after obtaining it
![1669968890780](https://user-images.githubusercontent.com/70893402/205248008-4e3d7103-36b1-4f3b-84f0-770e486ae05d.jpg)

**Comment by Kholid060** [comment]
It's because the workflow executes the next block before waiting for the HTTP Request to be done, to fix it add the `automaNextBlock()` function inside the `xhr.onreadystatechange` method. For example, 
```js
xhr.onreadystatechange = function () {
   if (xhr.status == 200) {
      ....
   }
   
   automaNextBlock()
}
```

**Comment by chenyunc123** [comment]
Thank you very much for your reply, but I still want to consult. The part behind the saved variables is gone
![image](https://user-images.githubusercontent.com/70893402/205256929-1ed16d30-8e0b-431a-b0a4-1779b71522e8.png)
![image](https://user-images.githubusercontent.com/70893402/205257526-edbfab93-bb2a-4b55-a468-6796d33b56d7.png)
![image](https://user-images.githubusercontent.com/70893402/205257730-5927738d-0ae2-4160-98cd-e498074bc612.png)
