### ISSUE TITLE
insert data to table bug in loop

### ISSUE THREAD

**Issue by star8ks** [AutomaApp/automa#983]
Hello, thanks for developing Automa!

I'm doing scrape on this [page](https://cvq9mb.csb.app/), see HTML here:

```html
<ul>
  <h2>group 1 title</h2>
  <li><h3>11 no tag</h3></li>
  <li><h3>12 no tag</h3></li>
  <li>
    <h3>13 with tag</h3>
    <span>tag</span>
  </li>
</ul>
<ul>
  <h2>group 2 title</h2>
  <li><h3>21</h3></li>
  <li><h3>22</h3></li>
  <li><h3>23</h3></li>
</ul>
```

but the result is not as I expected.

**To Reproduce**
Please execute the [workflow](https://automa.site/workflow/-ins_NpiuMTUiDt2Eo7Wx)

**Expected behavior**
The workflow produced the result data below
```json
[
  {
    "item-title": "11 no tag",
    "item-tag": "tag"
  },
  {
    "item-title": "12 no tag"
  },
  {
    "item-title": "13 with tag"
  },
  {
    "item-title": "21"
  },
  {
    "item-title": "22"
  },
  {
    "item-title": "23"
  }
]
```

but it should be:
```json
[
  {
    "item-title": "11 no tag"
  },
  {
    "item-title": "12 no tag"
  },
  {
    "item-title": "13 with tag",
    "item-tag": "tag"
  },
  {
    "item-title": "21"
  },
  {
    "item-title": "22"
  },
  {
    "item-title": "23"
  }
]
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome Canary 110.0.5454.0 canary (x86_64)
 - Extension Version: 1.24.1

**Comment by Kholid060** [comment]
It's expected behavior, to fix it, you can add an insert data block in the fallback of the conditions block.
![image](https://user-images.githubusercontent.com/22908993/205477328-a98f2a8e-0379-4355-a3c0-221fd7a0f07c.png)
![image](https://user-images.githubusercontent.com/22908993/205477336-cf013de5-5977-4131-ab4a-78950cabf08f.png)
