### ISSUE TITLE
is it possible to attract specialists to work on my project on this resource ? for payment$$$

### ISSUE THREAD

**Issue by irinaavakumova** [AutomaApp/automa#988]
Hello! I really need to automate several processes on websites. I really want to learn, but time is short, so it's easier to do the work together with a professional and understand the code that has already been created. Is this possible on this site? It is Automa that is interested in automation, since the skills have already been partially acquired 
My telegram
@yadostavka24
for payment

**Comment by simtuzi1** [comment]
I'm not interested for payment nor do I have nesessarily time to do that kind of work.
Can you make a git repo here and backup your workflows on that git repo. Then write a file where you specify how you want it to work. And maybe someone can do that work or even help you, without payment . I can look into it when I have some time.
