### ISSUE TITLE
在表达式里面$date无法接收globalData中的属性作为参数

### ISSUE THREAD

**Issue by AprildreamMI** [AutomaApp/automa#990]
```
{{$date(globalData.date,'YYYY)}}
```
无法生效，第一个参数永远都是当前日期

**Screenshots**
![image](https://user-images.githubusercontent.com/31964372/206090781-d52cb839-beda-4cff-b8f8-e878eedfa0b1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser: [e.g. Google Chrome] google
 - Extension Version: [e.g. v0.12.0] 1.24.1

**Comment by Kholid060** [comment]
Add a bracket between the `globalData.date`; For example, `{{ $date([globalData.date], 'YYYY') }}`

https://docs.automa.site/workflow/expressions.html#access-another-data-inside-the-expressions

**Comment by AprildreamMI** [comment]
好的，谢谢，这里文档或许需要优化更有帮助
