### ISSUE TITLE
希望在Javascript Code Block 里面可以调用`$date`等函数

### ISSUE THREAD

**Issue by AprildreamMI** [AutomaApp/automa#991]
希望在Javascript Code Block 里面可以调用`$date`等表达式使用的函数

**Comment by Kholid060** [comment]
You can add `https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js` as a preload script in the JS block, and write the code like this
```js
const date = automaRefData('globalData', 'date');
const formattedDate = dayjs(date).format('YYYY');

console.log(formattedDate)
```

**Comment by AprildreamMI** [comment]
This is a good way，But it is better to use `$funcName (param)`
