### ISSUE TITLE
`globalData`格式化错误

### ISSUE THREAD

**Issue by AprildreamMI** [AutomaApp/automa#994]
当在`xxx.automa.json`中的`globalData`是一个对象不是字符串时，会在`automa`里的JSON编辑器格式化错误，显示`[object Object]`

**Screenshots**
![image](https://user-images.githubusercontent.com/31964372/206119232-155ed6f8-6556-4edd-ba21-20556158c414.png)

![image](https://user-images.githubusercontent.com/31964372/206119193-92ba99d5-c3ef-4089-b0de-55136048fffa.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows
 - Browser: [e.g. Google Chrome] Chrome
 - Extension Version: [e.g. v0.12.0] 1.24.0

**Additional context**

**Comment by Kholid060** [comment]
It's expected, you need to stringify the JSON of the global data.

**Comment by AprildreamMI** [comment]
> It's expected, you need to stringify the JSON of the global data.

Thanks, maybe it needs to be compatible, `globalData` is probably dynamically added to the `xxx.automa.json` file
