### ISSUE TITLE
How to avoid mustache be convert to variable?

### ISSUE THREAD

**Issue by cs118651** [AutomaApp/automa#995]
**Describe the bug**
I want to output a string of characters into a form，like `${{secrets}}`，But `secrets` is a keyword of automa，so I got a result: `${}`，because secrets is transformed into `{}`

so, I would like to know how to avoid this kind of conversion，i just want to input a pure string

**Comment by Kholid060** [comment]
Currently, you can't avoid it besides changing the `secrets` into something else.
