### ISSUE TITLE
The new window cannot be selected，set as an incognito window

### ISSUE THREAD

**Issue by carls96** [AutomaApp/automa#997]
The new window cannot be selected，set as an incognito window
![20221208161434](https://user-images.githubusercontent.com/59246551/206394445-a0f36efb-1ac4-4c95-aa9b-419c188a6062.png)

**Comment by Kholid060** [comment]
Have you enabled "Allow in incognito" for Automa?

![image](https://user-images.githubusercontent.com/22908993/206395176-c9ace05f-2720-45e5-958d-9e5fe2d35a63.png)

https://docs.automa.site/blocks/new-window.html#incognito-window
